### ISSUE TITLE
Setup/teardown exception capturing as early/late as possible to catch all exceptions

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#105]
I noticed sometimes, an exception happens and PyQt5 calls `abort`, even with `pytest-qt`.

It seems this happens when an exception happens in a virtual Qt method during setup or teardown, e.g. with a `yield_fixture` or when `qtbot` calls `close()` on the widget.

I think `pytest-qt` should do the exception capturing setup/teardown as early/late as possible.

See https://github.com/The-Compiler/qutebrowser/pull/1048#issuecomment-150660769 for an example.

**Comment by nicoddemus** [comment]
Sure. Like I said in #106, I will try to get to this during the week. :smile:
