### ISSUE TITLE
Add qtbot.wait()

### ISSUE THREAD

**Issue by rossant** [pytest-dev/pytest-qt#107]
Would it be possible to add a simple `qtbot.wait()` method to wait for X milliseconds? For example, the following seems to work currently:

```python
def wait(x):
    from pytestqt.qt_compat import QtTest
    QtTest.QTest.qWait(x)
```

**Comment by The-Compiler** [comment]
I just wanted to comment here, but I'll do in #31 then :wink:

**Comment by nicoddemus** [comment]
Thanks @rossant. It was not exposed because PySide does not support it, but it is fine to only expose this methods to PyQt.

@The-Compiler thanks! :smile:
