### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_loop'

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#112]
This is somewhat similar to #69 - I've seen this from time to time on Ubuntu Trusty (on Travis):

```
================ ERRORS ================
 ERROR at setup of TestGitStrSubprocess.test_real_git 
SETUP ERROR: Qt exceptions in virtual methods:
________________________________________________________________________________
  File "/home/travis/build/The-Compiler/qutebrowser/.tox/unittests-nodisp/lib/python3.4/site-packages/pytestqt/wait_signal.py", line 51, in _quit_loop_by_timeout
    self._loop.quit()
AttributeError: 'NoneType' object has no attribute '_loop'
________________________________________________________________________________
  File "/home/travis/build/The-Compiler/qutebrowser/.tox/unittests-nodisp/lib/python3.4/site-packages/pytestqt/wait_signal.py", line 51, in _quit_loop_by_timeout
    self._loop.quit()
AttributeError: 'NoneType' object has no attribute '_loop'
________________________________________________________________________________
  File "/home/travis/build/The-Compiler/qutebrowser/.tox/unittests-nodisp/lib/python3.4/site-packages/pytestqt/wait_signal.py", line 51, in _quit_loop_by_timeout
    self._loop.quit()
AttributeError: 'NoneType' object has no attribute '_loop'
________________________________________________________________________________
  File "/home/travis/build/The-Compiler/qutebrowser/.tox/unittests-nodisp/lib/python3.4/site-packages/pytestqt/wait_signal.py", line 51, in _quit_loop_by_timeout
    self._loop.quit()
AttributeError: 'NoneType' object has no attribute '_loop'
________________________________________________________________________________
  File "/home/travis/build/The-Compiler/qutebrowser/.tox/unittests-nodisp/lib/python3.4/site-packages/pytestqt/wait_signal.py", line 51, in _quit_loop_by_timeout
    self._loop.quit()
AttributeError: 'NoneType' object has no attribute '_loop'
________________________________________________________________________________
```

Rerunning the tests always made them pass so far...

Any idea what could cause this? If not, what are your thoughts on working around this by adding a `if self._loop is None: return` in `_quit_loop_by_timeout`?

**Comment by nicoddemus** [comment]
That's really strange... `self` in this case is `None` (so unfortunately your suggestion wouldn't work). It seems like the signal blocker was destroyed but it was never disconnected, which by all code paths should still work.

How about calling `_cleanup` right after `self._loop.exec_()`?

```python
    def wait(self):
        """
        Waits until either a connected signal is triggered or timeout is reached.

        :raise ValueError: if no signals are connected and timeout is None; in
            this case it would wait forever.
        """
        if self.signal_triggered:
            return
        if self.timeout is None and not self._signals:
            raise ValueError("No signals or timeout specified.")
        if self._timer is not None:
            self._timer.timeout.connect(self._quit_loop_by_timeout)
            self._timer.start()
        self._loop.exec_()
+       self._cleanup()
        if not self.signal_triggered and self.raising:
            raise SignalTimeoutError("Didn't get signal after %sms." %
                                     self.timeout)
```

But it is really a shot in the dark... unless you have any other ideas?

**Comment by The-Compiler** [comment]
I mean checking `if self is None`, sorry. But yeah, sounds hackish :wink:

I'm not sure if this change would help - I'd guess the place it happens (in `_quit_loop_by_timeout`) is still inside that `self._loop.exec_()`, no?

Unfortunately I don't have a better idea... I also don't have an easy way to test this as it only happens on Travis and only once in a while...

**Comment by nicoddemus** [comment]
> I'm not sure if this change would help - I'd guess the place it happens (in _quit_loop_by_timeout) is still inside that self._loop.exec_(), no?

My guess here is that `exec_()` is returning because it was forcefully terminated by Qt somehow, so the usual paths of either timeout or quit by signal were never executed and `_cleanup` was never called.

>  I also don't have an easy way to test this as it only happens on Travis and only once in a while...

How about implementing the change in a branch and install from Git in `qutebrowser` for a while?

**Comment by The-Compiler** [comment]
I haven't seen this for months, no idea why... closing this for now.
