### ISSUE TITLE
MultiSignalBlocker.args

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#117]
It actually would be nice to have an `.args` attribute for `MultiSignalBlocker` too, which is just a list of emitted argument lists, e.g. `[['foo', 2342], ['bar', 1234]]`.

I'll work on this soon (I hope :laughing:)

**Comment by nicoddemus** [comment]
It would be nice to have a solid use case first... For example, I think it might make sense to have a dict of signal/args instead.

**Comment by The-Compiler** [comment]
Hm, I wonder if signals are hashable everywhere.

The only use case where I need it right now is this:

```python
    spy = QSignalSpy(ipc_server.got_args)
    # [...]
    with qtbot.waitSignals([ipc_server.got_args, ipc_server.got_args],
                           raising=True):
        connected_socket.write(data.encode('utf-8'))

    assert len(spy) == 2
    assert spy[0] == [['one'], 'tab', '']
    assert spy[1] == [['two'], '', '']
```

Note that specific usecase wouldn't work with a dict at all, because it's the same signal twice.

I think in general you have a small number of signals (and arguments) anyways, and you might want to easily test *all* arguments. Something like:

```python
with qtbot.waitSignals([signal1, signal2]) as blocker:
    # ...

assert blocker.args == [['one', 1], [True]]
```

seems more natural to me than

```python
with qtbot.waitSignals([signal1, signal2]) as blocker:
    # ...

assert blocker.args[signal1] == ['one', 1]
assert blocker.args[signal2] == [True]
```

**Comment by nicoddemus** [comment]
Hmm... perhaps, but then you will have to be sure about the order the signals are emitted... 

It seems to me we should wait for more use cases before deciding on a good API... once we publish one API, it will be much harder to change it

**Comment by The-Compiler** [comment]
Hm, true, I didn't think about the order being arbitrary.

I wonder if the best thing would be some custom datastructure, somewhat similar to an OrderedDict but with duplicates.

When iterating over it (or comparing it to a list, I guess) it'd behave like an iterable including the duplicates, but when indexing it with a signal it'd behave like a mapping (and probably raise if a signal with >1 emits was requested?).

Not sure yet if it's a good idea, just doing some brainstorming.

**Comment by The-Compiler** [comment]
On a second thought, what do you think about just having `args` as a list of lists, and `arg_dict` as a `signal` -> arguments mapping?

**Comment by nicoddemus** [comment]
I think having both would be OK actually... I see use cases for both of them

**Comment by estan** [comment]
I second this. My use case is that I actually do know the order in which I want the signals emitted, and I want to check that they were emitted in this order. It's a `Project` class which, when `setName` is called, should emit `nameChanged`, `changed` and `dirtyChanged`, in that order, and I also want to check that `nameChanged` was emitted with the argument that was passed to `setName`.

**Comment by nicoddemus** [comment]
This has been introduced in `2.0.0`, `MultiSignalBlocker` now has a `all_signals_and_args` attribute. 😁
