### ISSUE TITLE
Change license to MIT?

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#134]
@nicoddemus and I would like to change the license of pytest-qt to MIT for the upcoming 2.0 release, which means all contributors have to agree.

Could you please either :+1: this comment or add a new comment if you're okay with that?

- [x] @fabioz 
- [x] @montefra
- [x] @jdreaver
- [x] @snorfalorpagus
- [x] @gqmelo
- [x] @estan

**Comment by montefra** [comment]
@The-Compiler: I have nothing against it.
I'm just curious about the reason for the change.

**Comment by The-Compiler** [comment]
@montefra GPL can be problematic for some companies trying to use pytest plugins - it was requested for pytest-mock in https://github.com/pytest-dev/pytest-mock/issues/45 so we thought why not do it here too.

**Comment by fabioz** [comment]
Fine by me.

**Comment by snorfalorpagus** [comment]
I'm fine with this.

**Comment by jdreaver** [comment]
Okay with me!

**Comment by estan** [comment]
@The-Compiler: No problem at all.
