### ISSUE TITLE
Pytest hanging when qtbot fixture is used

### ISSUE THREAD

**Issue by GandaG** [pytest-dev/pytest-qt#143]
It simply [hangs](http://goo.gl/BXrBzW).

I'm in cygwin, under vagrant. The command used, inv test, is an invoke command (a normal py.test command was also used, still hangs) that is pretty much a shortcut to a larger py.test command. The relevant function is here:
```
@task
def clean_test():
    from shutil import rmtree

    rmtree("htmlcov", ignore_errors=True)
    print("Test caches cleaned.")


@task(clean_test)
def test():
    from os import system

    system("py.test --cov=designer --cov-report html --cov-report term -vv tests/")
```

The test function that is being stalled is this:
```
def test_qt(qtbot):
    assert 0
```

Am I doing something wrong?

**Comment by The-Compiler** [comment]
Does Qt and creating a `QApplication` work in general? If yes, can you find out where exactly it hangs, perhaps using `-s` and [hunter](https://pypi.python.org/pypi/hunter), or [pytest-timeout](https://pypi.python.org/pypi/pytest-timeout)?

**Comment by GandaG** [comment]
God, i'm dumb. Qt wasn't working for some random reason. Thanks and sorry.
