### ISSUE TITLE
Missing bits from pytest-qt 2.0 docs

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-qt#147]
@The-Compiler 
>  I'm a bit late, but I just realised check_params_cb and order aren't mentioned in the signal docs at all, and order isn't even in the changelog.

**Comment by nicoddemus** [comment]
Also add `qmodeltester` to `README`, under *Features*.

**Comment by MShekow** [comment]
I volunteer to write the check_param_cb and order documentation.

**Comment by nicoddemus** [comment]
Thanks @MShekow! We appreciate it. :smile:
