### ISSUE TITLE
version 2.0.0 breaks pyqt4 api v2

### ISSUE THREAD

**Issue by montefra** [pytest-dev/pytest-qt#148]
Running tests via tox with pytest-qt==2.0.0 with pyqt4 and api v2 gives me:

> py27 runtests: commands[1] | py.test
> INTERNALERROR> Traceback (most recent call last):
> INTERNALERROR>   File "/.../.tox/py27/local/lib/python2.7/site-packages/_pytest/main.py", line 90, in wrap_session
> INTERNALERROR>     config._do_configure()
> INTERNALERROR>   File "/.../.tox/py27/local/lib/python2.7/site-packages/_pytest/config.py", line 839, in _do_configure
> INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
> INTERNALERROR>   File "/.../.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 729, in call_historic
> INTERNALERROR>     self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
> INTERNALERROR>   File "/.../.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
> INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
> INTERNALERROR>   File "/.../.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
> INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
> INTERNALERROR>   File "/.../.tox/py27/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
> INTERNALERROR>     res = hook_impl.function(*args)
> INTERNALERROR>   File "/.../.tox/py27/local/lib/python2.7/site-packages/pytestqt/plugin.py", line 167, in pytest_configure
> INTERNALERROR>     qt_api.set_qt_api(config.getini('qt_api'))
> INTERNALERROR>   File "/.../.tox/py27/local/lib/python2.7/site-packages/pytestqt/qt_compat.py", line 74, in set_qt_api
> INTERNALERROR>     sip.setapi("QDate", 2)
> INTERNALERROR> ValueError: API 'QDate' has already been set to version 1
> ERROR: InvocationError: '/.../.tox/py27/bin/py.test'

Version 1.11.0 runs correctly.

According to git bisects the offending commit is:

 commit aaada5b98b3b15611f63d2d85a4ef18ba349c09c
Author: Bruno Oliveira <nicoddemus@gmail.com>
Date:   Thu May 12 20:19:54 2016 -0300

    Qt API lazy load in qt_compat and qt_api config option
    
    Fix #129

I think that the problem is that now PyQt4 is loaded before setting the API version. This is a problems only for PyQt4 under python2, but unfortunatly I have it's a combination I have to provide.

For the moment I'll fix the required version to pytest-qt to <= 1.11. If I have I'll try to figure out the issue.

**Comment by montefra** [comment]
Now I'm more puzzled than before:

       | v 1.11 | v2.0
------|---------|--------
.tox/py27/bin/py.test | OK | OK
tox -e py27, **with** ``py27: PYTEST_QT_API = pyqt4v2`` in ``setenv`` | OK | FAIL
tox -e py27, **without** ``py27: PYTEST_QT_API = pyqt4v2`` in ``setenv`` | OK | OK

If I remember correctly once I had to run ``py.test`` like ``PYTEST_QT_API = pyqt4v2 py.test`` to get it work. So I added it into tox.ini to avoid lots of typing.
But now is the other way around.

What happened with the new version?

**Comment by The-Compiler** [comment]
The new version uses PyQt5 instead of PyQt4 by default without `PYTEST_QT_API` FWIW.

**Comment by nicoddemus** [comment]
Hmmm that's really strange if you are setting `PYTEST_QT_API`. This is the relevant line from `qt_compat.py`:

```python
    def set_qt_api(self, api):
        self.pytest_qt_api = api or self._get_qt_api_from_env() or self._guess_qt_api()
``` 

I'm guessing `guess_qt_api` could cause problems in this case because it tries to import `PyQt4` eventually, which would explain your error, but if you are setting `PYTEST_QT_API`, then `self._guess_qt_api` should never be called.

Could you try setting `qt_api=pyqt4v2` in your `pytest.ini` file to see what you get?

**Comment by nicoddemus** [comment]
Oh this just occurred to me: before 2.0 pytest-qt would load PyQt bindings during import time, so it might be the case that before it would set the API version to v2 before importing PYQt4. In version 2 though importing PyQt4 is delayed until `pytest_configure` executes, so perhaps what might be happening is that some other code is importing PyQt4 (perhaps a `conftest.py` file for example).

**Comment by montefra** [comment]
As usual, when it gets late, mistakes happen. That's the correct matrix

       | v 1.11 | v2.0
------|---------|--------
.tox/py27/bin/py.test | FAIL | OK
PYTEST_QT_API=pyqt4v2 .tox/py27/bin/py.test | OK | FAIL
PYTEST_QT_API=pyqt4 .tox/py27/bin/py.test | FAIL | OK
.tox/py27/bin/py.test, with ``qt_api=pyqt4v2`` in pytest.ini | FAIL | FAIL
tox -e py27, **with** ``py27: PYTEST_QT_API = pyqt4v2`` in ``setenv`` | OK | FAIL
tox -e py27, **without** ``py27: PYTEST_QT_API = pyqt4v2`` in ``setenv`` | FAIL | OK
tox -e py27, **with** ``py27: PYTEST_QT_API = pyqt4`` in ``setenv`` | FAIL | OK

When it fails with v1.11 I get the following traceback:

> Traceback (most recent call last):
>   File "/.../.tox/py27/local/lib/python2.7/site-packages/_pytest/config.py", line 320, in _importconftest
>     mod = conftestpath.pyimport()
>   File "/.../.tox/py27/local/lib/python2.7/site-packages/py/_path/local.py", line 650, in pyimport
>     __import__(modname)
>   File "/.../tests/conftest.py", line 12, in <module>
>     sip.setapi('QString', 2)  # for ginga compatibility
> ValueError: API 'QString' has already been set to version 1
> ERROR: could not load /.../tests/conftest.py

When it fails with v2 I get the one at  the beginning of the issue.

In my conf test I do:

    import sip                                                                                                                                                            
    sip.setapi('QString', 2)  # for ginga compatibility
    sip.setapi('QVariant', 2)

and then I import a bunch of modules that import PyQt4.

I don't set other things to API 2 because I don't need. In the light of @nicoddemus clarification, this explain why it complains about ``API 'QDate'``.

If I don't set the ``qt_api`` it tries to guess it as following:
* PyQt5: fails because PyQt4 is already imported
* PySide: fails because I don't have it
* PyQt4: success!

If I had PySide I must set the ``qt_api=pyqt4``.

Are all the test modules loaded **before** pytest-qt loads PyQt/PySide?

We probably should update the documentation with something like:

* ``qt_api=pyqt4v2`` is useful and usable only if: 
  * all PyQt4 and sip imports are done within functions/methods, i.e. are executed at run time
  * ``sip.setapi`` is used for all the types it's used by pytest-qt
* If PyQt4 is imported at the module level and the api is set in the package/conftest.py/test_*.py, use ``qt_api=pyqt4``

Does it make sense?

**Comment by nicoddemus** [comment]
Thanks for the detailed followup!

> Are all the test modules loaded before pytest-qt loads PyQt/PySide?

I think test modules will be imported only after `conftest.py` file has been imported, which is the root of your problem as far as I can tell: in 2.0 `pytest-qt` will only import qt modules during `pytest_configure`, which will be called only after your `conftest.py` was already imported and `sip.setapi` was called. In versions < 2.0, pytest-qt would import qt modules when the plugin was loaded, long before `conftest.py` files were imported.

> We probably should update the documentation with something like: <snip>

I agree, `pyqt4v2` is probably only useful if one wants to use all types in v2 (which I personally find a little odd to not be your case).

One minor correction: *"all PyQt4 and sip imports are done within functions/methods, i.e. are executed at run time"* is not true for test modules, only for `conftest.py` files: the `pytest_configure` hook will be called before any other test modules are imported, so it should be fine to make global PyQt4 imports for test modules .

**Comment by montefra** [comment]
Thank you again for the detailed information

> I agree, pyqt4v2 is probably only useful if one wants to use all types in v2 (which I personally find a little odd to not be your case).

I never had problems using only two objects with the API v2. I'll investigate if this is indeed a problem.
Actually: the API is set in the conftest.py or in any of the packages imported there, pyqt4v2 is superfluous and (in cases like mine)  leads to errors.

> One minor correction: "all PyQt4 and sip imports are done within functions/methods, i.e. are executed at run time" is not true for test modules, only for conftest.py files: the pytest_configure hook will be called before any other test modules are imported, so it should be fine to make global PyQt4 imports for test modules .

Thanks for the correction.

I see if I find some time in the next days to do a PR to update the documentation with some of those information.

**Comment by nicoddemus** [comment]
> I see if I find some time in the next days to do a PR to update the documentation with some of those information.

If you could, that would be great! :+1: :grin:
