### ISSUE TITLE
waitForWindowShown doesn't handle timeout

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#158]
Qt's [`qWaitForWindowShown`](https://doc.qt.io/qt-5/qtest-obsolete.html#qWaitForWindowShown) (or [`qWaitForWindowExposed`](https://doc.qt.io/qt-5/qtest.html#qWaitForWindowExposed) which supersedes it since Qt 5.0) has a `timeout` argument, and returns a `bool` saying if the waiting has timed out or not.

pytest-qt's wrapper over it doesn't have the `timeout` argument, discards the return value and doesn't raise an exception either in case there was a timeout.

**Comment by nicoddemus** [comment]
Oh thanks, didn't realize that.

I think we should have the same semantics (receive `timeout` and return `bool`), do you agree?

**Comment by nicoddemus** [comment]
Superseded by #159
