### ISSUE TITLE
Add ability to specify custom QApplication subclass for qapp() fixture

### ISSUE THREAD

**Issue by timmwagener** [pytest-dev/pytest-qt#172]
## Add ability to specify custom `QApplication` subclass for `qapp()` fixture
:information_source: _I didn't find any guide on that in the docs or a related/answered issue, so I'm opening up one anew about this._

#### Proposal in a nutshell

---
Many Pyside projects seem to implement their own custom `QApplication` subclasses to handle project specific setup. It would be great if the `qapp()` fixture could be customized with a `QApplication` subclass type that is then used for instantiation instead of the default `QtGui.QApplication`.

#### Pseudo-code mockup

---
A quick peak into the source code makes me believe that maybe some edits in `qt_compat._QtApi` might do the trick. _(However, maybe that's too easy...)_. Here is some quick pseudo-code:
```python
# qt_compat.py

class _QtApi:

    ...

    def _get_qt_application_from_pytest_configuration(self):
        """Pseudo-code. Reads standard import path as configuration parameter
        from pytest.ini. Returns None if no parameter specified.

        Example:
            # pytest.ini
            ...
            [pytest-qt]
            CustomQApplication = myproject.ui.core.custom_application:CustomQApplication
            ...
        """
        return pytest.get_value_from_config("CustomQApplication")

    def get_custom_qt_application_class(self):
        """Pseudo-code"""

        qapplication_config_value = self._get_qt_application_from_pytest_configuration()

        # config value not set
        if (qapplication_config_value is None):
            raise KeyError("No custom QApplication specified")

        # config value wrong
        if (isinstance(qapplication_config_value, basestring) is False):
            raise ValueError("Custom QApplication specified with wrong format")

        # check correct syntax (path.x.y:class_name)

        # possibly more checks...

        # extract import path and qapplication class name
        import_path, application_class_name = qapplication_config_value.split(":")

        # import, check and return
        _module = __import__(import_path, globals(), locals(), [application_class_name], 0)
        application_class = getattr(_module, application_class_name)
        assert issubclass(application_class, self.QApplication)
        
        return application_class

    def set_qt_api(self, api):
        
        ...

            self.extract_from_variant = extract_from_variant
            self.make_variant = make_variant

        # exchange custom QApplication at the end
        try:
            custom_application_class = self.get_custom_qt_application_class()
        except KeyError:
            pass
        except (ValueError, ImportError, AssertionError, ) as  exception_instance:
            msg = "Error loading custom QApplication, using default. ({0})"
            msg = msg.format(exception_instance)
            raise RuntimeError(msg)
        else:
            self.QApplication = custom_application_class



qt_api = _QtApi()
```
#### Notes

---
* Does this seem feasible?
* Did I miss some obvious way, how it should be done? Some hooks or such?
* Is this something that points to a design flaw, when widgets are coupled tightly with custom `QApplication` classes? However I think it is a pretty common pattern to store globally accessable state/handlers on the qApp.

**Comment by The-Compiler** [comment]
I think you can simply supply a `qapp` fixture in your `conftest.py`, and it should be used by the rest of the plugin too?

**Comment by timmwagener** [comment]
Ha, sounds good! This seems to work, thanks.
```python
# root conftest.py
this = sys.modules[__name__]
this.qapplication = None

@pytest.fixture(scope='session')
def qapp():
    if (this.qapplication is None):
        this.qapplication = CustomQApplication(tuple())
    yield this.qapplication
```
_One question though:_ Why is it a `yield` fixture if there is no teardown? And with it being a `yield` fixture at session scope, wouldn't theoretically the `_qapp_instance` module level variable be unnecessary if a variable to the QApplication instance was assigned in the generator stackframe? _(as opposed to `global _qapp_instance; _qapp_instance = qt_api.QApplication([])`)_. I'd assume a session scoped generator would be kept alive until the end of the session.

**Comment by The-Compiler** [comment]
Looks like this was an oversight in a3a382f0ba951a33a34a68cf048850f003f28de2

**Comment by timmwagener** [comment]
Ok, if its done for a reason, i'll leave my fixture to assign to a module level variable aswell. Thanks and this issue can probably be closed.

**Comment by hansonap** [comment]
I am new to pytest and pytest-qt and don't quite understand why the above works, but it does. There is no documentation on this topic in pytest-qt but I think it would be helpful as creating custom QApplications is frequent.

**Comment by nicoddemus** [comment]
@hansonap good point, created #224 to track this.

**Comment by josiahlaivins** [comment]
I added the above code, and the py test starts up the application, but none of my qbot tests run.
```python
import sys
from typing import Union
import pytest
from ..app.pyside_app.components.Application import Application

# root conftest.py
this = sys.modules[__name__]
this.qapplication: Union[Application, None] = None

@pytest.fixture(scope='session')
def qapp():
	if this.qapplication is None: this.qapplication = Application(False)
	yield this.qapplication
```
Then I have an actual test:
```python
from pytestqt import qtbot

def test_iot_controller(qapp, qtbot: qtbot):
	print('hello')
	qapp.close()
```
But that test never gegts executed. I also don't understand how to close the application.
