### ISSUE TITLE
New release of pytest-qt

### ISSUE THREAD

**Issue by ghisvail** [pytest-dev/pytest-qt#173]
Please consider uploading a new release with the recent fixes introduced for Python 3.6. The latter is due to become the default Python in Debian, so it is essential that the package builds and tests properly with this version onwards.

I'd also be interested in having both the docs and tests (#171) included in the source tarball uploaded on PyPI. PyPI is the preferred canonical location for Python source code on Debian.

Cheers,

**Comment by nicoddemus** [comment]
Will do, thanks for the ping!

**Comment by nicoddemus** [comment]
Hi @ghisvail,

> I'd also be interested in having both the docs and tests (#171) included in the source tarball uploaded on PyPI.

I just checked an version 2.1.0 already contains tests and docs, thanks to `setuptools_scm`.

Noted about a new release with the `3.6` test fixes.

**Comment by ghisvail** [comment]
> thanks to `setuptools_scm`

The downside of it is that you get a lot of useless files included in the release tarball, like project dotfiles or CI config files.

**Comment by nicoddemus** [comment]
Indeed but as a maintainer I find it worth the few extra kbytes in the source tarball of it means not having to deal with manifest files. :wink:

**Comment by ghisvail** [comment]
Your manifest file should be 3 lines tops. It's not as if `pytest-qt` was such a big code base that maintaining a `MANIFEST.in` file was so demanding. I don't buy it, sorry.

**Comment by nicoddemus** [comment]
> I don't buy it, sorry.

No problem. 👍

**Comment by ghisvail** [comment]
Importing the latest tarball introduced a huge diff compared to version `2.1.0`. On further inspection, It looks like all line endings have changed from UNIX to Windows. This is not good. Please consider sticking to one format (UNIX preferably, since it is the one that was used until now).

**Comment by nicoddemus** [comment]
Ouch, definitely. Usually Travis publishes the packages, but because of #175 I had to make the release on my own box.

**Comment by ghisvail** [comment]
Could you fix that with a new upload?

**Comment by nicoddemus** [comment]
Only with a new release, one can't replace published tarballs on PyPI.

I just noticed that #168 should be merged, so I will see to it and make a 2.1.2 release.

**Comment by nicoddemus** [comment]
Just released `2.1.2` with the correct line endings. 👍
