### ISSUE TITLE
Consider using conda for CI environement

### ISSUE THREAD

**Issue by rth** [pytest-dev/pytest-qt#180]
I have been trying to setup PySide2 CI for  https://github.com/pytest-dev/pytest-qt/pull/161 following the [installation instructions from PySide2 wheels](https://github.com/fredrikaverpil/pyside2-wheels/blob/master/QUICKSTART.md#ubuntu-1404-trusty) and after a few hours, I'm still not able to make Travis install PySide2 correctly  (cf last build [status here](https://travis-ci.org/rth/pytest-qt/jobs/275061857) ):
  - on PY3 This is due to PySide2 not being able to see some environment variables that should have been set by sourcing `/opt/qt56/bin/qt56-env.sh` (but sourcing this file fails on Travis or file doesn't exist etc) and so it cannot find `libQt5Core`
  - ~~on PY2 installing the Pyside2 wheel produces the `PySide2-5.6-cp27-cp34m-linux_x86_64.whl is not a supported wheel on this platform.` error.~~ **Edit**: The download URL was wrong.

 Anyway, my point is that `scripts/install-qt.py` a bit complicated as it is and adding PySide2 setup will add [even more custom installation logic](https://github.com/pytest-dev/pytest-qt/compare/master...rth:pyside2-support?expand=1#diff-7bba75ab0917e3ebc7e3cd551194d185). All of this is also specific to Ubuntu 14.04 currently on Travis and will probably need updating for the next Ubuntu release. I have not even started looking into the Appveyor setup.

My question is whether you would consider using conda for setting up the CI environments? PySide2 [is now on conda-forge](https://github.com/conda-forge/pyside2-feedstock), so all the installation could be done  roughly with,
```
conda create -n test-env -c conda-forge pyside2 pytest python=3.4
source activate test-env
```
The advantages is that,
  * it would allow a much simpler  (and easier to maintain) installation setup that would be more consistent between Linux and Windows
  * would allow migrating [from legacy to container-baser Travis CI setup](https://docs.travis-ci.com/user/migrating-from-legacy/)

The limitation is that I'm not sure how well conda integrates with tox...

Might be related to https://github.com/pytest-dev/pytest-qt/pull/165

What do you think?

**Comment by nicoddemus** [comment]
Definitely! I'm a daily user of conda and contribute several packages to conda-forge, so I'm definitely 👍 

It could probably do as conda-forge does and use https://github.com/astropy/ci-helpers to help setting up conda.

Would you like to open a PR with that?

**Comment by rth** [comment]
Thanks for the feedback, @nicoddemus ! Submitted a PR for Travis CI (https://github.com/pytest-dev/pytest-qt/pull/181).

For Appveyor the situation is more complicated because it uses tox (that apparently has some [assumptions as to where the python executables are located](https://github.com/pytest-dev/pytest-qt/blob/master/tox.ini#L2)) and also uses `scripts/link_pyqt.py` to symlink PyQt into vitualenvs. So I'm not quite sure how to best approach that problem...

**Comment by rth** [comment]
For instance here is the [appveyor.yml setup used by qtpy](https://github.com/spyder-ide/qtpy/blob/master/appveyor.yml)  that tests all 4 Python Qt backend. They just have a build matrix with a subset of all PyQT backend combinations, which removes the need for something like `scripts/link_pyqt.py` though it would probably take longer to run and is less thorough about testing all combinations of cases than the current setup on pytest-qt...

**Comment by nicoddemus** [comment]
@rth that's awesome thanks! Made a few comments but the end result is great.

I think we can go with the same approach used by qtpy for testing on Travis. Would you like to try that as well? Feel free to add it to the same PR if you do.
