### ISSUE TITLE
Integration with qtpy

### ISSUE THREAD

**Issue by rth** [pytest-dev/pytest-qt#184]
The support of multiple PyQt / PySide backends is a recurrent problem for any project working with Qt in Python. In pytest-qt it is solved by providing a compatibility `_QtApi` interface in `qt_compat.py` (that is not in the public interface). At the same time there are packages that specialize in providing such a compatibility interface, namely [spyder-ide/qtpy](https://github.com/spyder-ide/qtpy) and [mottosso/Qt.py](https://github.com/mottosso/Qt.py). For project that use one of those packages (e.g. matplotlib is [considering it](https://github.com/matplotlib/matplotlib/issues/6118)), and wanting to test it with with pytest-qt it would mean that they would not, technically be testing the project in the same conditions (and it would also mean setting differently named environment variables twice `PYTEST_QT_API` and `QT_API` or `QT_PREFERRED_BINDING`.) 

I think the integration could be straightforward: e.g. to integrate with qtpy, the following should almost work,

At the end of [**pytestqt/qt_compat.py**](https://github.com/pytest-dev/pytest-qt/blob/master/pytestqt/qt_compat.py#L192)
```py
try:
    if 'QT_API' not in os.environ and 'PYTEST_QT_API' in os.environ:
        os.environ['QT_API'] = os.environ['PYTEST_QT_API']
    import qtpy
    qt_api = qtpy
    qt_api.pytest_qt_api = qtpy.API
except ImportError:
     # fallback to the built-in compatibility layer..
    qt_api = _QtApi()
```

And maybe one extra environment in TravisCI for testing..

What do you think?

**Comment by nicoddemus** [comment]
Hi @rth,

I wouldn't mind ditching the current API layer if `qtpy` fits the bill, it would mean less code to maintain. 

Does `qtpy` support lazy loading?

My preference would be to completely remove the compatibility API and use `qtpy` directly, if we can maintain backward compatibility with `PYTEST_QT_API` configuration and lazy loading.

**Comment by rth** [comment]
> Does qtpy support lazy loading?


Aww right, that's another challenge. No qtpy doesn't and expect explicit imports e.g. `import qtpy.QtCore`. Qt.py (!=qtpy the names are just not confusing)  seems to import everything by default if I understood correctly. Maybe one could just wrap qtpy in something like this example https://github.com/mottosso/Qt.py/issues/152#issuecomment-268862636 as a way around it? 

Though this would add one extra layer of indirection for the wrapper around the wrapper around Qt :/

**Comment by The-Compiler** [comment]
There's already some discussion about this at https://github.com/pytest-dev/pytest-qt/pull/130#issuecomment-219218794 FWIW.

**Comment by machinekoder** [comment]
`python_qt_bindings` is another wrapper provided by the ROS project: http://wiki.ros.org/python_qt_binding

**Comment by nicoddemus** [comment]
Thanks for the pointer @machinekoder.

But as commented in https://github.com/pytest-dev/pytest-qt/pull/130#issuecomment-219218794 it is probably not worth to use a wrapper, the qt_compat module provides lazy loading and doesn't really add too much to maintenance because we don't need to import the entire API anyway, just a few symbols.
