### ISSUE TITLE
Properly clear exceptions after test

### ISSUE THREAD

**Issue by fabioz** [pytest-dev/pytest-qt#187]
If an exception is thrown and is captured by pytestqt, it's keep alive (found it while trying to discover why PySide was crashing on the process exit when a test failed -- the reason was that pytestqt was keeping variables alive longer than it should and variables weren't cleared in the proper order because of that).

Will provide a fix shortly.

**Comment by fabioz** [comment]
Is this fixed now?

**Comment by nicoddemus** [comment]
Oh yeah, thanks for the ping. I have fixed the problem in pytest, we should be able to produce a proper test now.

**Comment by nicoddemus** [comment]
Thanks @fabioz, and sorry for the delay!

**Comment by fabioz** [comment]
No problems. Thanks for the fix ;)
