### ISSUE TITLE
exception when no Qt available - is it necessary?

### ISSUE THREAD

**Issue by p0las** [pytest-dev/pytest-qt#192]
INTERNALERROR>   File "site-packages\pytestqt\plugin.py", line 167, in pytest_configure
INTERNALERROR>     qt_api.set_qt_api(config.getini('qt_api'))
INTERNALERROR>   File "site-packages\pytestqt\qt_compat.py", line 60, in set_qt_api
INTERNALERROR>     raise RuntimeError(msg)
INTERNALERROR> RuntimeError: pytest-qt requires either PySide, PySide2, PyQt4 or PyQt5 to be installed

on our system we have multiple python versions available on demand and we try to keep compatible site-packages outside of them. This includes one version of pytest to serve all of them. Some of python configurations are very clean and do not have any interface related libraries. Just having pytest-qt in the environment makes unittests (that do not use it) break with the above runtime error.
is there a way to remove the compatibility checks?

(btw we are loving pytest-qt :-))

**Comment by nicoddemus** [comment]
Howdy, sorry for the delay.

If you pass `-p no:qt` to pytest it will completely disable the `pytest-qt` plugin. Would that be enough to solve your use case perhaps?

**Comment by p0las** [comment]
didn't know about it. This is perfect. thank you.

**Comment by nicoddemus** [comment]
Great, thanks for the follow up.
