### ISSUE TITLE
QtBot Interaction with QTreeView / QListView

### ISSUE THREAD

**Issue by CameronJRAllan** [pytest-dev/pytest-qt#194]
Is there functionality available for clicking a particular index in a QListView or QTreeView in a window? I.e, click the top item in the list widget?

I've looked at the documentation for help on this with no luck, as well as experimenting with the qtbot.mouseClick function to see if I could find the relevant syntax.

**Comment by nicoddemus** [comment]
One way is to find the rect of the item using [`visualRect`](http://doc.qt.io/qt-5/qabstractitemview.html#visualRect) and then `qtbot.mouseClick`, but do you need to actually click on the item or you just want something to get selected? If the latter, a more robust way is to use a select function directly (for example [`setCurrentIndex`](http://doc.qt.io/qt-5/qabstractitemview.html#setCurrentIndex)).

**Comment by CameronJRAllan** [comment]
Thanks for the quick and useful response! Do I need to reference the QRect in a particular way? I'm getting an error as follows:
`E         mouseClick(QWindow, Qt.MouseButton, modifier: Union[Qt.KeyboardModifiers, Qt.KeyboardModifier] = Qt.KeyboardModifiers(), pos: QPoint = QPoint(), delay: int = -1): argument 1 has unexpected type 'QRect'
`

Calling the function as:
`    qtbot.mouseClick(viewRect, QtCore.Qt.LeftButton)
`

How would I reference the QWidget type to match the function parameters, while still specifying the specific visualRect I wish to click on?

**Comment by nicoddemus** [comment]
As I said, this can be tricky because the item you want selected might not be even visible. Take a look at the docs for `QListView`, I recall there's a function which gives you the visible rect of an item (sorry I can't look for it right now).

Did you try the approach of selecting the index explicitly like I suggested? It is easier to implement and maintain, I really recommend you go with that route.

**Comment by CameronJRAllan** [comment]
I've verified that the item should be visible, but I think the issue I have is that the function parameters request either a _QWindow_ or _QWidget_, but once I get the visible rect it has type _QRect_ and this doesn't match either of the overloaded function's parameters:
```
TypeError: arguments did not match any overloaded call:
E         mouseClick(QWidget, Qt.MouseButton, modifier: Union[Qt.KeyboardModifiers, Qt.KeyboardModifier] = 0, pos: QPoint = QPoint(), delay: int = -1): argument 1 has unexpected type 'QRect'
E         mouseClick(QWindow, Qt.MouseButton, modifier: Union[Qt.KeyboardModifiers, Qt.KeyboardModifier] = Qt.KeyboardModifiers(), pos: QPoint = QPoint(), delay: int = -1): argument 1 has unexpected type 'QRect'

```
I tried the option of selecting the index, but this causes issues with my signals / slots so am hoping to avoid if possible. Thanks again for the quick response, this library so far has been brilliant to use.

**Comment by nicoddemus** [comment]
It seems you are not passing the `QListView` as the first argument to `mouseClick`. Can you show the code you are using?

**Comment by CameronJRAllan** [comment]
```
  def test_expand_item(self, qtbot):
    # Search for band
    qtbot.addWidget(self.prog.quickFilter)
    qtbot.keyClicks(self.prog.quickFilter, "Grateful Dead")

    # Click top result in filter
    qtbot.addWidget(self.prog.browseList)
    viewRect = self.prog.browseList.visualRect(self.prog.browseList.model().index(0, 0))
    qtbot.mouseClick(viewRect, QtCore.Qt.LeftButton)

```

Prog is an instance of _QWindow_, which contains my various widgets. You're absolutely right, I'm not passing in the widget, but I'm unsure how to pass the widget, will still referencing the _rect_ previously found (stored in _viewRect_).

**Comment by nicoddemus** [comment]
Just pass `browseList` as first argument, and the position must be a `QPoint` so get the center of the rectangle you have:

```python
qtbot.mouseClick(self.prog.browseList, QtCore.Qt.LeftButton, pos=viewRect.center())
```

**Comment by CameronJRAllan** [comment]
Brilliant! Thank-you again for your help.

**Comment by nicoddemus** [comment]
Glad I could help, I'm closing this for now then. 👍

**Comment by andreabrambilla** [comment]
I'm having a similar issue, but with a custom QTreeView

```Python
class MyView(QTreeView):
    def __init__(self, parent=None):
        super(MyView, self).__init__(parent)
        self._proxymodel = _MyModel(self) # used to add one fake column
        self.dclick_positions = []

    def mouseDoubleClickEvent(self, ev):
        self.dclick_positions.append(ev.pos())

def test_my_view(qtbot)
    my_view = MyView()
    ... # setup model
    qtbot.add_widget(my_view)
    my_view.show()
    idx = my_view._proxymodel.index(0, 0) 
    center = my_view.visualRect(idx).center()  # QPoint(59, 13), seems ok
    qtbot.mouseDClick(my_view, Qt.LeftButton, pos=center)
    assert len(my_view.dclick_positions) == 1
```
At the end the test fails because the list is empty. Any idea?

**Comment by Willowlululu** [comment]
```
    def result(*args, **kwargs):
>       return qtest_method(*args, **kwargs)
E       TypeError: 'PySide2.QtTest.QTest.mouseDClick' called with wrong argument types:
E         PySide2.QtTest.QTest.mouseDClick(MyView, MouseButton)
E       Supported signatures:
E         PySide2.QtTest.QTest.mouseDClick(PySide2.QtWidgets.QWidget, PySide2.QtCore.Qt.MouseButton, PySide2.QtCore.Qt.KeyboardModifiers = Qt.KeyboardModifiers(), PySide2.QtCore.QPoint = QPoint(), int = -1)
E         PySide2.QtTest.QTest.mouseDClick(PySide2.QtGui.QWindow, PySide2.QtCore.Qt.MouseButton, PySide2.QtCore.Qt.KeyboardModifiers = Qt.KeyboardModifiers(), PySide2.QtCore.QPoint = QPoint(), int = -1)

../.virtualenvs/visiontool/lib/python3.6/site-packages/pytestqt/qtbot.py:622: TypeError
```
this simple demo I run it successfully  about two weeks ago, but now it comes out some problems as above ， and my test.py has also attached underneath. 
Hope you can help me , Thanks a lot!

**Comment by nicoddemus** [comment]
Hi everyone, sorry about the delay.

> At the end the test fails because the list is empty. Any idea?

Hmm not really. I suggest to call `qtbot.debugHere()` and see if looking at the widget provides any clues.

> this simple demo I run it successfully about two weeks ago, but now it comes out some problems as above ， and my test.py has also attached underneath.

It seems `MyView` is not a QWidget subclass. I suggest to add this line before your `mouseDClick` call:

```
assert isinstance(mywidget, QWidget)
```

My guess is that this assertion will fail.
