### ISSUE TITLE
Click on a menu action

### ISSUE THREAD

**Issue by dhenryFabrice** [pytest-dev/pytest-qt#195]
Hi,

How can I simulate a click on a menu action?

Best regards

**Comment by nicoddemus** [comment]
This is hard to accomplish using actual click events; menus are actually dialogs with their own event loops. I suggest to keep around the `QAction` objects that are built when the menu is created, and call their `trigger()` method directly.

Hope this helps!

**Comment by hmaarrfk** [comment]
Would it be appropriate to reopen this issue?

Testing actions would be quite a helpful addition.

**Comment by nicoddemus** [comment]
Hi @hmaarrfk,

We could, but I thought the question was answered... given a `QMenu`, one can access the list of actions through [actions()](https://doc.qt.io/qt-5/qwidget.html#actions), and then it is just a matter of triggering it manually using [trigger.emit()](https://doc.qt.io/qt-5/qaction.html#trigger).

Perhaps adding something to the docs?

**Comment by Tomas1337** [comment]
Hi, not sure how you mean to do it by `trigger.emit()`. Is it something like this?
 
```
form = MainWindow(args=dummy_args
menu = form.bar
source_menu = menu.actions()[0]
qtbot.keyClicks(source_menu.trigger(), Qt.LeftButton)
```

I'm not sure how you use the trigger.emit in this case

**Comment by nicoddemus** [comment]
Ahh sorry, I've meant `action.trigger()` (I fixed the original post).

```python
source_action = menu.actions()[0]
source_action.trigger()
```

(Note that `menu.actions()` returns a list of `QAction`, so `source_menu` is a bit misleading, should be `source_action`).

**Comment by Tomas1337** [comment]
Thanks for that! it seems this works to trigger it but did not work for my program since I apparently was using the `.aboutToShow.connect` method on a `QMenu`. 
So instead of using `.trigger()` as you mentioned, I used `.aboutToShow.emit()` on the test file.

Thanks for the hint!

**Comment by anhduy1202** [comment]
> Thanks for that! it seems this works to trigger it but did not work for my program since I apparently was using the `.aboutToShow.connect` method on a `QMenu`. So instead of using `.trigger()` as you mentioned, I used `.aboutToShow.emit()` on the test file.
> 
> Thanks for the hint!
