### ISSUE TITLE
High memory usage, possible memory leakage?

### ISSUE THREAD

**Issue by CameronJRAllan** [pytest-dev/pytest-qt#200]
I have ~200 tests, spread across several files, most of which have a structure as shown below:

```python
class TestAppPoC():
  @pytest.fixture(scope="function", autouse=True)
  # Fixture to run before every function begins
  def setup(self, qtbot):
    # Dialog
    self.dialog = QtWidgets.QMainWindow()

    # Event loop
    self.app = application.mainWindow(self.dialog)

  def test_volumeSlider(self):
    assert(self.app.vSlider.value() == 100)
```

As it stands, there is no teardown fixture specified, as I assumed from the documentation that this is handled automatically (as is the creation of a qApp instance). Many of the tests do not require qtBot, but rather the programmatic availability of the objects created by the dialog window in PyQt.

When running my tests, while previously I had no issue, it now gets to approximately 50 tests run before memory usage is at 5GB and my system freezes to a halt. When running only a single containing 20 tests the memory usage hits 4GB.

I ran PyTest from the terminal, rather than PyCharm and experienced the same behaviour.

Is my fixture set-up incorrect, or is there a memory leak / teardown issue occurring with pytest-qt? It appears that after a test has completed, the entire state of the dialog remains in memory (by default ~200MB) and hence when several tests have run, the memory usage grows hugely. I'm afraid I lack the knowledge to fully debug myself but any pointers would be appreciated.

Library information (taken from PyCharm):    
```
============================= test session starts ==============================
platform linux -- Python 3.6.4, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
PyQt5 5.10.1 -- Qt runtime 5.10.1 -- Qt compiled 5.10.1
rootdir: /home/cameron/PycharmProjects/Meta-Data/tests, inifile: pytest.ini
plugins: qt-2.3.1, mock-1.6.2, leaks-0.2.2
collected 21 items
```

**Comment by nicoddemus** [comment]
Hi @CameronJRAllan,

First of all sorry about the delay!

`pytest-qt` won't try to clean up automatically all widgets created, it is recommended to always call `qtbot.add_widget` with any widget you create so then `qtbot` will destroy them at the end of the test.

Your example then should become:

```python
class TestAppPoC():
  @pytest.fixture(scope="function", autouse=True)
  # Fixture to run before every function begins
  def setup(self, qtbot):
    # Dialog
    self.dialog = QtWidgets.QMainWindow()
    qtbot.add_widget(self.dialog)

    # Event loop
    self.app = application.mainWindow(self.dialog)

  def test_volumeSlider(self):
    assert(self.app.vSlider.value() == 100)
```

**Comment by CameronJRAllan** [comment]
Brilliant, I feel very stupid now in hindsight, I didn't realise adding the dialog would handle everything. Thank-you very much.

**Comment by nicoddemus** [comment]
Sure, no problem, glad it worked.
