### ISSUE TITLE
PySide2 segmentation faults after test session in Travis and AppVeyor

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-qt#202]
Sample builds:

* https://ci.appveyor.com/project/nicoddemus/pytest-qt/build/1.0.480
* https://travis-ci.org/pytest-dev/pytest-qt/builds/353613828

**Comment by nicoddemus** [comment]
The jobs are marked as "allowed to fail" on Travis and removed from AppVeyor for now.

**Comment by rth** [comment]
Possibly due to https://bugreports.qt.io/browse/PYSIDE-585 (fixed in the dev version of PySide2).

**Comment by nicoddemus** [comment]
@rth thanks for the heads up, appreciate it!

**Comment by The-Compiler** [comment]
This doesn't seem to be an issue nowadays anymore.
