### ISSUE TITLE
[Question] Can I use for QML applications?

### ISSUE THREAD

**Issue by rafaeldelucena** [pytest-dev/pytest-qt#204]

**Comment by nicoddemus** [comment]
Hi,

In theory yes, there's nothing in `pytest-qt` that would prevent that; `pytest-qt` is responsible for creating the `QApplication` object for you. There are no fixtures to help with testing `QML` specific features though that would be a nice thing to have.

**Comment by nicoddemus** [comment]
@rafaeldelucena it seems your question has been resolved so I'm closing this for now. Feel free to followup with further questions.

**Comment by machinekoder** [comment]
@rafaeldelucena Have you been successful? I would be interested in how you solved the problem.

**Comment by rafaeldelucena** [comment]
@machinekoder I'm using https://github.com/parkouss/funq, because my target runs in an embedded Linux platform.

**Comment by machinekoder** [comment]
@rafaeldelucena Nice find, I will check it out.
