### ISSUE TITLE
qtbot mouseClick doesn't seem to generate the mouse button click event

### ISSUE THREAD

**Issue by hmbui** [pytest-dev/pytest-qt#208]
I'm new to Qt, and I've been trying to figure out why this pytest code doesn't work:

```python
import pytest
from ...PyQt import QtCore
from ...PyQt.QtCore import Qt
from ...PyQt.QtGui import QLabel, QMenu

class TextLabel(QLabel):
    def __init__(self, parent=None):
        super(QLabel, self).__init__(parent)
        self.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.contextMenuEvent = self.open_context_menu

    def generate_context_menu(self):
        menu = QMenu(parent=self)
        return menu

    def open_context_menu(self, ev):
        menu = self.generate_context_menu()
        action = menu.exec_(self.mapToGlobal(ev.pos()))
        del menu


def test_open_context_menu(qtbot):
    label = TextLabel()
    label.resize(200, 300)
    label.move(0, 0)
    qtbot.addWidget(label)

    with qtbot.waitExposed(label):
        label.show()

    #qtbot.waitActive(label, timeout=5000)
    assert label.isVisible()

    #label.grabMouse()
    #mouse_grabber = label.mouseGrabber()
    #assert isinstance(mouse_grabber, TextLabel)

    #qtbot.stopForInteraction()
    qtbot.mouseClick(label, QtCore.Qt.RightButton, pos=QtCore.QPoint(100, 100))

    #label.releaseMouse()
```

What this code is supposed to do is that it generates a right-button mouse click, which, during debugging, will hit the breakpoints placed at open_context_menu() and generate_context_menu(). These breakpoints are not hit, however, hence the issue.

The commented code is what I was trying, but didn't work. In fact, I don't think grabbing the mouse would be necessary, but I'm not sure.

I found issue #27, and suspect my qtbot could be hitting outside of the client area of the widget. That was when I added the move(0, 0) and added the pos param to mouseClick(), but that didn't help.

When I used stopForInteraction(), and right click on the active widget, I was able to trigger open_context_menu() and generate_context_menu(), as expected.

**Comment by hmbui** [comment]
@nicoddemus, thanks! I can also verify that the mousePressEvent was sent.

A colleague (@hhslepicka) found this Qt bug report:
https://bugreports.qt.io/browse/QTBUG-52552

which I think explains the phenomenon. It's been open since April 2016.

The best I could do was to vote for it :-( So, this is a known bug.

**Comment by nicoddemus** [comment]
Ah good find, thanks for sharing.

Well not much we can do then, I guess. Care to close this issue?

**Comment by hmbui** [comment]
Certainly. Thanks for looking at this issue.

**Comment by nicoddemus** [comment]
Thanks!
