### ISSUE TITLE
blocker.all_signals_and_args is empty when using PySide2

### ISSUE THREAD

**Issue by zephmann** [pytest-dev/pytest-qt#211]
First and foremost, pytest-qt has been tremendously useful. Thank you!

I am working on a UI that needs to be compatible with both PyQt5 and PySide2. When testing I noticed that with PyQt5, the all_signals_and_args seems to be populated correctly with the args from the multile signals, however, when testing with PySide2, the list is empty.

```
def test_status_complete(qtbot):
    app = Application()

    signals = [app.worker.status, app.worker.finished]
    with qtbot.waitSignals(signals, raising=True) as blocker:
        app.worker.start()

    print(blocker.all_signals_and_args)
    assert False
```

testing with PyQt5
```
>>> [<pytestqt.wait_signal.SignalAndArgs instance at 0x7f93c771fdd0>, <pytestqt.wait_signal.SignalAndArgs instance at 0x7f93c771fef0>]
```

testing with PySide2
```
>>> []
```

Just wanted to pass this along. Thanks again!

**Comment by nicoddemus** [comment]
Thanks for the report @zephmann! It might be a problem with PySide2 though.

**Comment by zephmann** [comment]
@nicoddemus True, wouldn't be too surprising if it was a PySide2 problem. Thanks!

**Comment by The-Compiler** [comment]
This is because pytest-qt can't get a signal's name from the signal object on PySide2, so apparently (from reading the code) it doesn't record the signals at all.

It works when instead using `signals = [(app.worker.status, 'status'), (app.worker.finished, 'finished')]` instead, though. It doesn't look like that's documented, though.

**Comment by nicoddemus** [comment]
Closing in favor of updating the docs in #261. 

Thanks again @zephmann again for the report. 👍
