### ISSUE TITLE
Pytest-qt doesn't recognise Python 3.4 + PyQt5 5.11.2

### ISSUE THREAD

**Issue by Julian-O** [pytest-dev/pytest-qt#218]
A new version of PyQt5 was released in the last 24 hours.

Since around then, some of the CI tests on the nucleic\enaml project have stopped working on Python 3.5 (on Windows), because pytest-qt complains:

> INTERNALERROR> RuntimeError: pytest-qt requires either PySide, PySide2, PyQt4 or PyQt5 to be installed

conda list confirms (excerpted):

    > conda list
    PyQt5                     5.11.2                    <pip>
    PyQt5_sip                 4.19.11                   <pip>
    pytest                    3.6.2                     <pip>
    pytest-cov                2.5.1                     <pip>
    pytest-qt                 2.4.1                     <pip>
    python                    3.5.2                         0  
    QtPy                      1.4.2                     <pip>

It continues to work on Python 2.7 and 3.6.
It continues to work if the installed version of PyQT5 is fixed to the previous version.

(I haven't researched the changes, and whether it is best to be fixed in Pytest-qt or PyQt5.)

**Comment by Julian-O** [comment]
Okay, I have pretty much got as far as I can.

The following code works with the previous version of PyQT5, but doesn't work with latest, on Python 3.5 (but is okay on Python 3.6), on Windows (haven't tested other platforms).

    import PyQt5.QtCore
    print(PyQt5.QtCore)

It seems likely that it is nothing to do with Pytest-qt, and this issue can be closed...

... but I am not a commercial customer of PyQT5, so it'd be great if someone else could escalate this to Riverbank for me.

**Comment by The-Compiler** [comment]
Yeah, definitely not a pytest-qt issue. You don't need to be a commercial customer to [post to their mailinglist](https://www.riverbankcomputing.com/mailman/listinfo/pyqt), however, someone else recently [brought up the same issue](https://www.riverbankcomputing.com/pipermail/pyqt/2018-July/040492.html) already.
