### ISSUE TITLE
Improve waitUntil timeout message

### ISSUE THREAD

**Issue by Sup3rGeo** [pytest-dev/pytest-qt#222]
Documentation says:

> If a timeout is reached, the last assertion error re-raised and the test will fail

I actually wasn't aware of the timeout and took some time to go back to documentation and understand why the waitUntil function was raising, when previously it had never raised (of course on this specific case the wait took more than 1 second, the default).

So I would like to propose that something informing that a Timeout has actually happen. This would be helpful and possibly save some time for new users.

**Comment by nicoddemus** [comment]
Hi @Sup3rGeo, thanks for the suggestion.

You mean raising a new exception while keep the message from the previous one?

**Comment by karlch** [comment]
Is this still a planned enhancement? If so, I would like to take a shot at it :smiley:

**Comment by nicoddemus** [comment]
Yes @karlch, thanks for the interest!

In this case I think it suffice to raise another exception from the last exception and let Python 3's exception chaining take care of the rest.

**Comment by karlch** [comment]
I agree, I was planning on raising the existing `TimeoutError`.
