### ISSUE TITLE
How to troubleshoot post-test hang?

### ISSUE THREAD

**Issue by enkore** [pytest-dev/pytest-qt#223]
What are possible causes for pytest-qt to hang *after* the test function returns but *before* py.test prints the "dot of success"?

Aborting with ^C always yields this message:

```
ICE default IO error handler doing an exit(), pid = 27288, errno = 4
```

**Comment by The-Compiler** [comment]
Maybe [pytest-faulthandler](https://github.com/pytest-dev/pytest-faulthandler) with `--faulthandler-timeout`, or [pytest-timeout](https://bitbucket.org/pytest-dev/pytest-timeout/) can tell you more about where it hangs.
