### ISSUE TITLE
Add docs on how to create custom QApplications

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-qt#224]
Follow up from https://github.com/pytest-dev/pytest-qt/issues/172#issuecomment-415588753

**Comment by josiahlaivins** [comment]
I added the referenced code, and the py test starts up the application, but none of my qbot tests run.
```python
import sys
from typing import Union
import pytest
from ..app.pyside_app.components.Application import Application

# root conftest.py
this = sys.modules[__name__]
this.qapplication: Union[Application, None] = None

@pytest.fixture(scope='session')
def qapp():
	if this.qapplication is None: this.qapplication = Application(False)
	yield this.qapplication
```
Then I have an actual test:
```python
from pytestqt import qtbot

def test_iot_controller(qapp, qtbot: qtbot):
	print('hello')
	qapp.close()  # Where Application has a method:     def close(self):  self.exit()
```
But that test never gets executed. I also don't understand how to close the application.

**Comment by nicoddemus** [comment]
> But that test never gets executed

That's strange, what's the name of the test file? What output are you getting?

> I also don't understand how to close the application.

Fixture teardown is done after the `yield`:

```python
@pytest.fixture(scope='session')
def qapp():
	if this.qapplication is None: this.qapplication = Application(False)
	yield this.qapplication
    # close this.qapplication here
```

**Comment by m3nu** [comment]
Took a shot at adding this, by merging it with the existing `QApplication.exit()` docs. Let me know if you want any changes, @nicoddemus
