### ISSUE TITLE
Drop support for Python 2.7 and PyQt4 

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-qt#228]
Dropping this we can also use plain `pip` to install `PyQt5` and `PySide2`, getting the latest versions.

**Comment by The-Compiler** [comment]
Given that Conda is currently broken (#237), maybe now is the right time for this? Qt 4 has been [unsupported](https://blog.qt.io/blog/2015/05/26/qt-4-8-7-released/) for almost three years now.

**Comment by nicoddemus** [comment]
Problem is that AFAIK there's no pip build for PyQt for Python 2.7, so we can't really migrate to pip until we drop support for Python 2.7. 😞 

I get the point of dropping PyQt4 (I don't use it personally as well), but I think it is better justified if we can make our CI easier.

**Comment by nicoddemus** [comment]
> True, but there we could probably easily use system-wide Ubuntu packages on Travis for that. Still might be easier than Conda?

Conda is easy if you know your way around it, and the system wide packages for Ubuntu had other problems IIRC, like only having PyQt for 3.4 for example. I guess we can try that.

> Alternatively, maybe let's be bold and drop Python 2?

We still use Python 2.7 at work, so I would prefer to wait a little bit more as otherwise it will make my life harder, because we need to still support Python 2 and 3 in our codebase. We have already migrated almost all projects, and we expect to be able to drop Python 2 entirely early next year.

> If people need to stay on Python 2 for a bit longer, they can as well just stay on an older pytest-qt version (and I think with the right markers, pip can also automatically install the older version there).

Indeed, and the python_requires marks are already in place as well 👍. Not sure, you are probably right, the chance of having to make a new `pytest-qt` release due to a serious bug is slim given that the code has been stable for quite some time.

Not sure, let me sleep a bit on it. I think the major decision here is not to drop only PyQt4 but Python 2 as well. I'll update the title to reflect that. 👍

**Comment by scott-wilson** [comment]
As someone in the VFX industry, dropping Python 2.7 would be not great. I realize we can use an earlier version, but some studios are basically locked off the internet, and host their own pip repositories (and may only keep the last version of a package). I know that the industry is moving to Python 3.6+ for 2020. See http://www.vfxplatform.com/ for more information.

However, the industry is either using Qt 5 (and Python bindings) or will be soon, so I'm not sure of many studios that will complain. But dropping Python 2.7 would hurt.

**Comment by nicoddemus** [comment]
Hi @scott-wilson, thanks for the feedback!

> But dropping Python 2.7 would hurt.

Python 2.7 users will still be able to use old versions, with `pip` using the old versions automatically in Python 2.7. 

pytest-qt has been stable for some time now, I doubt a critical fix would be needed once Python 2.7 is dropped, say in version 4, in the space of 2019-2020. Nevertheless, we will be open if outside contributors would like to contribute a fix and will gladly make a new bug-fix release of the version that still supports 2.7 (say 3.X).

**Comment by nicoddemus** [comment]
> I realize we can use an earlier version, but some studios are basically locked off the internet, and host their own pip repositories (and may only keep the last version of a package)

Oh sorry I must have missed that part. Oh that sucks, never heard about DevOps done that way.

But rest assured that dropping Python 2.7 support is not something that we will do lightly. Unfortunately supporting Python 2.7 comes at a cost, and that cost is increasing  with services moving forward and making harder to support old versions of PyQt. Being volunteer driven, we have to balance how much we are willing to work to support old Python versions vs making our work easier and more pleasant.

**Comment by altendky** [comment]
> Python 3 in CY2020 is a firm commitment at this point, it will be a required upgrade as Python 2 will no longer be supported beyond 2020.

That's something, but perhaps they misread the date?  Python 2 will no longer be supported _in_ 2020 (beyond 2019).

**Comment by nicoddemus** [comment]
Yes, according to https://www.python.org/dev/peps/pep-0373/#maintenance-releases

> Specifically, 2.7 will receive bugfix support until January 1, 2020. After the last release, 2.7 will receive no support.

**Comment by scott-wilson** [comment]
If you work at a company that has to meet the security criteria of certain large comic book companies owned by certain large companies that basically own your childhood, then you will have to deal with extremely tight security protocols that makes military level security look like nothing. In other words, good luck trying to get work done.

Either way, how's Python 2 making things harder? I may not be able to help out much, but I'll do what I can to keep Python 2 support up until 2020.

**Comment by nicoddemus** [comment]
> If you work at a company that has to meet the security criteria of certain large comic book companies owned by certain large companies that basically own your childhood, then you will have to deal with extremely tight security protocols that makes military level security look like nothing. In other words, good luck trying to get work done.

Heh that sucks. 😁 

> Either way, how's Python 2 making things harder?

It would make our CI jobs very simple and reduce the amount of special casing which we need to do for Python 2. Also it would allow us to drop PyQt4 and PySide. But nothing really ground breaking, that's why we are only discussing it at the moment.

**Comment by scott-wilson** [comment]
Yeah, PyQt4 and Pyside 1 are probably okay to toss at this point. I can't speak on behalf of the whole industry, but I know that any new apps using Python and Qt are going to be Python 2.7, and Qt 5 (PyQt5 or Pyside2), and VFX vendors are only expected to support that.

**Comment by altendky** [comment]
As I said, I've dealt with silly IT (is devops the term now?).  But running old Python past the EOL or only having the latest PyPI artifacts available are certainly not ways to achieve security.  Anyways, as I said before, those of us unlucky enough to deal with those situations luckily get help compensating for them from the community.

**Comment by rerpha** [comment]
done in https://github.com/pytest-dev/pytest-qt/commit/2fc8f680d927b5eeb2de7a66628e7806a06a58f4 ?

Can this be closed?

**Comment by nicoddemus** [comment]
Yes thank you!
