### ISSUE TITLE
Proper tests for qInfo when it becomes fully available

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-qt#232]
Followup to #225, `qInfo` is not currently exposed by the bindings. As suggested in https://github.com/pytest-dev/pytest-qt/issues/225#issuecomment-417868188, we can workaround that by using `QMessageLogger`, but sadly that's not exposed by `PySide` yet.

For now we can make a simple test for INFO messages, but when `QMessageLogger` is available (or even better `qInfo`) we should update the other tests to issue/capture INFO messages.

**Comment by The-Compiler** [comment]
Closing this as the PR was merged. I also [sent a mail](https://www.riverbankcomputing.com/pipermail/pyqt/2018-September/040862.html) to the PyQt mailinglist, so I'd expect it to show up in PyQt soon :wink:

**Comment by nicoddemus** [comment]
Thanks!

**Comment by The-Compiler** [comment]
FWIW I got the usual "Should be in tonight's snapshot." answer, so `qInfo()` should be in PyQt 5.11.3, which is planned for after Qt 5.11.2, which in turn is planned the coming week or so :wink:
