### ISSUE TITLE
model tester testParent fails on assertion that seems incorrect

### ISSUE THREAD

**Issue by p0las** [pytest-dev/pytest-qt#246]
line 377
```
   top_left_child = self._model.index(0, 0, parent)
        assert not self._model.hasIndex(rows, 0, parent)
        assert not self._model.hasIndex(rows + 1, 0, parent)

        for r in range(rows):
            assert not self._model.hasIndex(r, columns, parent)
```
In the loop **"r"** starts from 0 which means the first index tested is (0, columns, parent)
in my case columns=0 so the element is the same as **"top_left_child"** which, in turn, has a valid index. Does it expect "columns">0 and my model gives it a wrong value? 
Am I missing something?

**Comment by p0las** [comment]
my model had no columns and that was the reason for this assertion to fail. It might be nice to add a test for the number of columns with a cleaner error message.
Love model tester BTW. Every now and then it catches something like this and helps me to improve my models

**Comment by nicoddemus** [comment]
Thanks, glad to hear you find the model tester useful! (We have @The-Compiler for that, as he has pushed the feature and done most of the work).

> It might be nice to add a test for the number of columns with a cleaner error message.

A PR with that would be welcome. 😁

**Comment by The-Compiler** [comment]
Hmm, the C++ modeltester [does seem to do](https://github.com/qt/qtbase/blob/v5.11.2/src/testlib/qabstractitemmodeltester.cpp#L521-L523) the same thing. Wonder if that's a bug there?
