### ISSUE TITLE
typo in modeltest._on_rows_about_to_be_inserted

### ISSUE THREAD

**Issue by ext-jmmugnes** [pytest-dev/pytest-qt#248]
Hello,

just to mention that, in modeltest._on_rows_about_to_be_inserted,  the following line (549):

`last_data = self._model.data(last_index) if start - 1 > 0 else None`

should be:

`last_data = self._model.data(last_index) if start - 1 >= 0 else None`

since start can be equal to 1.

It is actually like this in the [qt5 source code](https://code.woboq.org/qt5/qtbase/src/testlib/qabstractitemmodeltester.cpp.html#_ZN31QAbstractItemModelTesterPrivate21rowsAboutToBeInsertedERK11QModelIndexii) (line 643):

`c.last = (start - 1 >= 0) ? model->index(start - 1, 0, parent).data() : QVariant();`

Thank you.

**Comment by The-Compiler** [comment]
Good catch! Do you want to open a PR with the change, so you get credit for it? :+1:
