### ISSUE TITLE
Any way to run qtmodeltester on QFileSystemModel?

### ISSUE THREAD

**Issue by willsALMANJ** [pytest-dev/pytest-qt#250]
I was hoping to be able to run the model tester on a subclass of `QFileSystemModel`. However, `QFileSystemModel` uses the root of the file system as the top level parent of the model. When you call `setRootPath()` on the model, it changes the file system level that is shown in a view but the underlying model still encompasses the entire file system. The model tester starts at the root of the model and walks down 10 levels deep checking child items. This much walking of the file system for me causes the test to work at max CPU for hours without ending. Is there any way to work around this or should I just not use the model tester in this case?

**Comment by nicoddemus** [comment]
Hi @willsALMANJ,

Not sure if `qmodeltester` is configurable like this, and if we want to add this capability to it: adding it would deviate from the original implementation, which is not something we want to do lightly.

I suggest to ask also on Qt forums/channels for advice, as your question applies to C++ as well.

**Comment by The-Compiler** [comment]
I agree with @nicoddemus - the aim of the model tester is to be a 1:1 reimplementation of Qt's (and with newer pytest-qt/PyQt5 versions, Qt's tester will be used).
