### ISSUE TITLE
QTimer taking twice as long with waitSignal

### ISSUE THREAD

**Issue by Wallboy** [pytest-dev/pytest-qt#253]
```
import pytest

from PyQt5.QtCore import QTimer


def test_testing123(qtbot):
    timer = QTimer()
    timer.setSingleShot(True)
    with qtbot.waitSignal(timer.timeout, timeout=None):
        timer.start(5000)
    assert False


pytest.main()
```

I just started using pytest and pytest-qt and wanted to run a quick test to make sure I'm understanding it's usage. I would expect this test to take 5 seconds, but instead it takes 10 seconds (twice as long as the timer) before the assert is finally reached. 

What am I not doing right?

**EDIT:** The problem only happens when using the `pytest.main()` invocation method. If I run the test from the command line using `pytest test_module.py` the test completes in 5 seconds.

**EDIT 2:** Putting `pytest.main()` in a `if __name__ == '__main__':` condition and it works fine now.

**Comment by The-Compiler** [comment]
Calling `pytest.main()` like so in your test module makes pytest run twice: Once when you run `pytest` on the commandline, and once when it imports your test module, causing it to call `pytest.main()`. You normally wouldn't call `pytest.main()` inside your test module at all, just write your tests and let pytest discover them.
