### ISSUE TITLE
qtbot.keyClicks does not trigger QPushButton shortcuts

### ISSUE THREAD

**Issue by jnslmk** [pytest-dev/pytest-qt#254]
I stumbled upon some unexpected behaviour when trying to unit test the activation of a QPushButton.

Consider this minimal example:
The following code creates a dialog window containing a QPushButton.
The button increments a variable and can be triggered with the shortcut `Ctrl+Up`.
```
from PyQt5 import QtWidgets


class Window(QtWidgets.QDialog):
    def __init__(self):
        super(Window, self).__init__()

        self.var = 0
        btn = QtWidgets.QPushButton()
        btn.clicked.connect(self.inc)
        btn.setShortcut('Ctrl+Up')

        layout = QtWidgets.QHBoxLayout()
        layout.addWidget(btn)
        self.setLayout(layout)

    def inc(self):
        self.var += 1
        print(self.var)


if __name__ == '__main__':

    import sys

    app = QtWidgets.QApplication(sys.argv)
    window = Window()
    window.show()
    sys.exit(app.exec_())
```

Testing the implementation with the following unit test fails:
```
# from PyQt5 import QtCore

from minimal_shortcut import Window

def test_shortcut(qtbot):
    window = Window()
    qtbot.keyClicks(window, 'Ctrl+Up')
    # qtbot.keyClick(window, QtCore.Qt.Key_Up, modifier=QtCore.Qt.ControlModifier)
    assert window.var == 1
```
Output:
```
============================= test session starts =============================
platform win32 -- Python 3.7.1, pytest-4.2.0, py-1.7.0, pluggy-0.8.1
PyQt5 5.11.3 -- Qt runtime 5.11.2 -- Qt compiled 5.11.2
rootdir: C:\Users\<user>\<dir> inifile:
plugins: qt-3.2.2, cov-2.6.1
collected 1 item

test_minimal_shortcut.py F                                               [100%]

================================== FAILURES ===================================
________________________________ test_shortcut ________________________________

qtbot = <pytestqt.qtbot.QtBot object at 0x000002A0BABDD400>

    def test_shortcut(qtbot):
        window = Window()
        qtbot.keyClicks(window, 'Ctrl+Up')
>       assert window.var == 1
E       assert 0 == 1
E        +  where 0 = <minimal_shortcut.Window object at 0x000002A0BABA4DC8>.var

test_minimal_shortcut.py:8: AssertionError
========================== 1 failed in 0.06 seconds ==========================
```

I expected the keyClicks function to trigger the assigned button shortcut.
Variations like `qtbot.keyClick(window, QtCore.Qt.Key_Up>, modifier=QtCore.Qt.ShiftModifier` result in the same behaviour.

**Comment by nicoddemus** [comment]
Hi @jnslmk,

Thanks for the report. `qtbot.keyClicks` just calls `QTest.keyClicks` directly, so I suspect that `QTest´ has the same problem. 

I wonder if posting a [QShortcutEvent](https://doc.qt.io/qt-5/qshortcutevent.html) would result in the shortcut being triggered?

**Comment by jnslmk** [comment]
Hi @nicoddemus,

thank your for your suggestion.

I created an event with `event = QtGui.QShortcutEvent(QtGui.QKeySequence('Ctrl+Up'), 0)` and tried both sending and posting it with `QtCore.QCoreApplication.sendEvent(window, event)` and `QtCore.QCoreApplication.postEvent(window, event)` respectively.
None of the triggered the shortcut.
I also tried various event IDs because I am not sure what they do.

**Comment by nicoddemus** [comment]
Hmm bummer. Thanks for following up.

I'm out of suggestions, seems more like a Qt issue than a pytest-qt one.

If we find a solution it would be great to mention it in the docs at least. 👍

**Comment by eyllanesc** [comment]
Unfortunately it is not possible to implement this test with the public Qt API since the [spontaneous() ](https://doc.qt.io/qt-5/qevent.html#spontaneous)property has to be enabled to emulate OS events since this is enabled by the [QSpontaneKeyEvent](https://github.com/qt/qtbase/blob/5.13.2/src/testlib/qtestspontaneevent.h#L86) class.

A workaround is to emulate those events through the libraries of the OS using pyautogui:

```
import pyautogui

from PyQt5 import QtCore, QtGui, QtTest

from minimal_shortcut import Window


def test_shortcut(qtbot):
    window = Window()
    assert window.var == 0
    window.show()
    qtbot.waitUntil(lambda: window.isVisible())
    QtTest.QTest.qWait(1000)
    pyautogui.hotkey("ctrl", "up")
    QtTest.QTest.qWait(1000)
    assert window.var == 1
```

Output:

```
===================================== test session starts =====================================
platform linux -- Python 3.8.0, pytest-5.3.1, py-1.8.0, pluggy-0.13.1
PyQt5 5.13.2 -- Qt runtime 5.13.2 -- Qt compiled 5.13.2
rootdir: /home/user/pytest-qt-254, inifile: pytest.ini
plugins: qt-3.2.2
collected 1 item                                                                              

test_minimal_shortcut.py .                                                              [100%]

====================================== 1 passed in 2.49s ======================================
```

**Comment by eyllanesc** [comment]
Unfortunately it is not possible to implement this test with the public Qt API since the [spontaneous() ](https://doc.qt.io/qt-5/qevent.html#spontaneous)property has to be enabled to emulate OS events since this is enabled by the [QSpontaneKeyEvent](https://github.com/qt/qtbase/blob/5.13.2/src/testlib/qtestspontaneevent.h#L86) class.

A workaround is to emulate those events through the libraries of the OS using pyautogui:

```python
import pyautogui

from PyQt5 import QtCore, QtTest

from minimal_shortcut import Window


def test_shortcut(qtbot):
    window = Window()
    assert window.var == 0
    window.show()
    qtbot.waitUntil(lambda: window.isVisible())
    QtTest.QTest.qWait(1000)
    pyautogui.hotkey("ctrl", "up")
    QtTest.QTest.qWait(1000)
    assert window.var == 1
```

Output:

```console
================================== test session starts ==================================
platform linux -- Python 3.8.0, pytest-5.3.1, py-1.8.0, pluggy-0.13.1
PyQt5 5.13.2 -- Qt runtime 5.13.2 -- Qt compiled 5.13.2
rootdir: /home/user/pytest-qt-254, inifile: pytest.ini
plugins: qt-3.2.2
collected 1 item                                                                        

test_minimal_shortcut.py .                                                        [100%]

=================================== 1 passed in 2.48s ===================================
```

**Comment by nicoddemus** [comment]
Thanks @eyllanesc, that's very helpful. 👍

**Comment by The-Compiler** [comment]
Should we close this, given that it's an issue in the underlying Qt? I suppose we could add @eyllanesc's snippet to #86 so we don't forget about adding it to the docs.

**Comment by nicoddemus** [comment]
> Should we close this, given that it's an issue in the underlying Qt? I suppose we could add @eyllanesc's snippet to #86 so we don't forget about adding it to the docs.

Agreed, added.

Thanks everyone!

**Comment by bersbersbers** [comment]
I stumbled across this issue when running across similar problems. For the record, here's my repro code. `pyautogui` solves this issue.

```python
from PySide6.QtGui import QKeySequence, QShortcut
from PySide6.QtWidgets import QApplication, QMainWindow


class Window(QMainWindow):
    def __init__(self):
        super().__init__()
        QShortcut(QKeySequence("Shift+V"), self).activated.connect(self.V)
        self.show()

    def V(event_arg):
        print(event_arg)  # This is called from main(), but not from test()


def test(qtbot) -> None:
    window = Window()
    qtbot.addWidget(window)
    qtbot.keySequence(window, QKeySequence("Shift+V"))


def main():
    application = QApplication()
    window = Window()
    application.exec()


if __name__ == "__main__":
    main()
```

**Comment by bersbersbers** [comment]
I have investigated this a bit more. Run the following example code to see that "V" is not caught - until you set `DELAY` to any positive value, including 1. This may be a viable solution to make keyClicks work, including via `qtbot`:

```python
"""keyClicks works with any *positive* delay!"""
from PySide6 import QtGui, QtTest, QtWidgets

DELAY = 0  # set to 1 to make it work

app = QtWidgets.QApplication()
window = QtWidgets.QMainWindow()
window.show()
QtGui.QShortcut("V", window).activated.connect(lambda: print("Caught V."))
QtTest.QTest.keyClicks(window, "V", delay=DELAY)
print("Done.")
```
