### ISSUE TITLE
Is there a way to interact to the pyqt GUI through sources other than qtbot during a test?

### ISSUE THREAD

**Issue by Nagendraprasath-R** [pytest-dev/pytest-qt#257]
Is there any way to interact with the GUI in the middle of a test, through sources other than qtbot like manual mouse/key clicks, windows dll calls or some other UI automation libraries like pywinauto?

**stopForInteraction** will not work since the GUI has to be closed after interacting from other source and the state of the GUI will be restored before the function call.

**Comment by The-Compiler** [comment]
I don't see why it wouldn't be possible, as long as you get the test to wait (for a signal, condition, etc.) until you're finished with your manual interaction.

**Comment by Nagendraprasath-R** [comment]
Hi @The-Compiler , Yeah I can interact with the GUI after calling **stopForInteraction** method and close the GUI so that the test can resume from the state in which it was before calling **stopForInteraction**. But I want the test to continue with the GUI's state after the interactions(pytest should not restore the GUI's state before the external interactions )

**Comment by The-Compiler** [comment]
So how do you determine that your interaction is finished and pytest-qt continues? Use that to wait (e.g. using `wait` or `waitSignal` or whatever) instead of `stopForInteraction`.

**Comment by Nagendraprasath-R** [comment]
@The-Compiler , I could use `wait `or `waitSignal` to make pytest-qt wait but the actual problem is `qtbot` doesn't allow manual interactions with the GUI.

**Comment by The-Compiler** [comment]
I don't follow. How does it not allow them?

**Comment by Nagendraprasath-R** [comment]
@The-Compiler,From my understanding, pytest-qt creates an instance of the gui, runs it and adds it to qtbot and then starts the test execution. During the test execution qtbot is the only way in which we can send mouseclicks or keystrokes to the GUI under test.  `stopForInteraction` can be used if manual interaction is needed. Below is the documentation of `stopForInteractionfor` for your reference.
 
```
def stopForInteraction(self):
        """
        Stops the current test flow, letting the user interact with any visible widget.
        This is mainly useful so that you can verify the current state of the program while writing
        tests.
        Closing the windows should resume the test run, with ``qtbot`` attempting to restore visibility
        of the widgets as they were before this call.
        .. note:: As a convenience, it is also aliased as `stop`.
        """
```

I am actually trying to perform mouseclick from any other python library(like pywinauto or pyautogui) in one of the test-cases that I have in pytest-qt. I am trying this as a work around to handle modal dialogs without mocking it. Please refer #256 as well where I have explained this issue.

I have attached the example code that I am trying with.
[Pyqt example.zip](https://github.com/pytest-dev/pytest-qt/files/3019294/Pyqt.example.zip)


Thank you very much for your responses :). It would be really helpful in case you have any suggestions.

**Comment by nicoddemus** [comment]
@Nagendraprasath-R all `qtbot.mouseClick` does (and all other input-related methods for that matter) is to call `QTest.mouseClick`, which basically posts a `QMouseEvent` properly configured into the Qt event loop.

> I am actually trying to perform mouseclick from any other python library(like pywinauto or pyautogui)

If they can simulate mouse/keybord events through the OS, it should just work. I suggest you first try to send events to your GUI using those external libraries in a simple runnable example, instead of mixing it with `pytest-qt`; this way you will have less moving parts, which will help you isolate and understand the problem better.

> I have attached the example code that I am trying with.

In that example I don't see any attempt of using other libraries to send input events to the GUI...

**Comment by The-Compiler** [comment]
Should we close this?

**Comment by The-Compiler** [comment]
Ah, I also just noticed https://github.com/pytest-dev/pytest-qt/issues/254#issuecomment-561848689 using `pyautogui`, which seems quite similar to what's described here.

**Comment by Nagendraprasath-R** [comment]
> Should we close this?
Yes, Sure!
