### ISSUE TITLE
Simple test fails on Azure Pipelines (but passes locally)

### ISSUE THREAD

**Issue by cbrnr** [pytest-dev/pytest-qt#259]
I have set up Azure Pipelines to test my PyQt5 app, but the following simple test (which passes locally) fails:

```
from PyQt5.QtWidgets import QWidget

def test_pyqt(qtbot):
    widget = QWidget()
```

The detailed log can be accessed here (click on the failed task): https://dev.azure.com/clemensbrunner/clemensbrunner/_build/results?buildId=72

Any ideas what the issue might be?

**Comment by The-Compiler** [comment]
Qt aborts when creating a QApplication - if you run pytest with `-s` (so it doesn't capture output) you should get more information.

I'm guessing that no display server (X11) is running, which is needed for QApplication. You might want to try using [pytest-xvfb](https://github.com/The-Compiler/pytest-xvfb) (shameless plug :wink:)

**Comment by cbrnr** [comment]
I installed `pytest-xvfb`, but I still get the same error (I assume that  Xvfb is installed because I didn't see the warning message). I also ran pytest with `-s`, but the output looks the same: https://dev.azure.com/clemensbrunner/clemensbrunner/_build/results?buildId=77

**Comment by altendky** [comment]
On 2019-04-24 06:53, Clemens Brunner wrote:

> I installed pytest-xvfb, but I still get the same error (I assume that 
> Xvfb is installed because I didn't see the warning message). I also ran 
> pytest with -s, but the output looks the same: 
> https://dev.azure.com/clemensbrunner/clemensbrunner/_build/results?buildId=77

I cheated and got a little diagnostic help from Florian...  but it seems 
you need to `sudo apt-get install libxkbcommon-x11-0`.  Here's my 
minimal attempt (without pytest).  Well, Azure may have some other 
mechanism for installing system packages but this at least works.

   sudo apt-get install xvfb libxkbcommon-x11-0
   python -m pip install pyqt5
   export QT_DEBUG_PLUGINS=1
   xvfb-run python -c "import faulthandler; faulthandler.enable(); from 
PyQt5 import Qt; app = Qt.QApplication([])"

https://dev.azure.com/altendky/romp-on/_build/results?buildId=2673&view=logs&jobId=723ae2ca-1875-54fe-1d9e-d340dbadee77&taskId=f379ea76-adc2-5887-1a71-4d6b1da78c6b&lineStart=354&lineEnd=362&colStart=1&colEnd=55

QT_DEBUG_PLUGINS=1 did have helpful output, even if Florian guessed the 
issue first.

   Cannot load library 
/opt/hostedtoolcache/Python/3.6.8/x64/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so: 
(libxkbcommon-x11.so.0: cannot open shared object file: No such file or 
directory)

https://dev.azure.com/altendky/romp-on/_build/results?buildId=2665&view=logs&jobId=723ae2ca-1875-54fe-1d9e-d340dbadee77&taskId=f379ea76-adc2-5887-1a71-4d6b1da78c6b&lineStart=233&lineEnd=234&colStart=1&colEnd=1

Cheers,
-kyle

**Comment by cbrnr** [comment]
Thank you @The-Compiler and @altendky - using `pytest-xvfb` and installing `libxkbcommon-x11-0` on Linux solved the issue! I guess the missing package could even be considered a bug, so I should probably ask if they can pre-install this package on their Ubuntu VM.

**Comment by The-Compiler** [comment]
FWIW it's only needed when you need to run a graphical application, which probably doesn't apply to most projects.

**Comment by cbrnr** [comment]
True, but they have all other packages required for GUI testing pre-installed, so adding this tiny package might be worth it (given that their other agents running Windows and macOS work out of the box).

**Comment by j9ac9k** [comment]
Just wanted to thank you folks for references to libxkbcommon-x11-0 ...had no idea how to troubleshoot the core-dumped errors I was getting with pyside2 5.12.1+ (but CI was passing w/ pyside2 5.12.0).
