### ISSUE TITLE
How i can test code with QMessageBox?

### ISSUE THREAD

**Issue by theperelomov** [pytest-dev/pytest-qt#262]
Sorry if something is wrong, I just started to learn automatic testing, and I'm sorry, I'm not English speaking.
Here is my code:
```
def button_start_clicked(self):
    try:
        vertices_count = int(self.line_edit_count_vertices.text())
        if vertices_count < 5:
            raise ValueError
    except ValueError:
        QMessageBox.warning(self, "header", "text", QMessageBox.Close, QMessageBox.Close)
```
The problem is that the QMessageBox does not close. 
Please explain how to test this code correctly.

Here is my simple test
```
@pytest.mark.parametrize("value", [4, 5, "text"])
def test_button_start_clicked(value):
    window = Window()
    window.line_edit_count_vertices.setText(str(value))
    window.button_start_clicked()
```
UPD after 30 minutes of thinking: 
here is my simple solution, but I think that it is not perfect
```
application = QApplication()
    
@pytest.mark.parametrize("value", [4, 5, "text"])
def test_button_start_clicked(self, value):
    def close_window():
        sleep(0.5)
        if type(application.activeWindow()) is QMessageBox:
            application.activeWindow().accept()
    window = Window()
    window.line_edit_count_vertices.setText(str(value))
    ThreadPoolExecutor().submit(close_window)
    window.button_start_clicked()
```

**Comment by The-Compiler** [comment]
> Sorry if something is wrong, I just started to learn automatic testing, and I'm sorry, I'm not English speaking.

Don't worry! Your English is fine :smile:

There are some ideas about this in #256 and in the docs: https://pytest-qt.readthedocs.io/en/latest/note_dialogs.html

**Comment by theperelomov** [comment]
> Don't worry! Your English is fine 😄

Don't worry Google Translate 😄

Thanks for the links provided.
