### ISSUE TITLE
Is there a problem when PyQt5 is installed in .eggs instead of site-packages?

### ISSUE THREAD

**Issue by RichardFetzel** [pytest-dev/pytest-qt#265]
I am using setup.cfg and the install_requires variable to manage my project dependencies. When I run "python setup.py test" in my project, the dependencies are downloaded and installed to the ".eggs" folder in my project. When the tests are executed pytest-qt does not find PyQt5 in the .eggs folder (all the other dependencies are found). 
If I install PyQt5 using pip, everything works fine. PyQt5 is then in the site-packages folder of my virtualenv.
I have this problem on Windows and Linux using python 3.6.7 and 3.5.2

Error message:
RuntimeError: pytest-qt requires either PySide, PySide2, PyQt4 or PyQt5 to be installed
  PyQt4.QtCore: No module named 'PyQt4'
  PyQt5.QtCore: No module named 'PyQt5.sip'
  PySide.QtCore: No module named 'PySide'
  PySide2.QtCore: No module named 'PySide2'

**Comment by altendky** [comment]
What about `tests_require`?

https://docs.pytest.org/en/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner

Though it is my impression that `setup.py test` is not really a favored mechanism for running tests.  Probably in part because of the differences in how things are 'made available' instead of being 'installed'.  But, pytest-qt may certainly still want to support this, we'll see.

For reference on the special 'making available' approach:
https://setuptools.readthedocs.io/en/latest/setuptools.html#test

**Comment by nicoddemus** [comment]
I'm not sure, seems like an issue with `PyQt*` in general supporting eggs, I don't think this is `pytest-qt` related.

`python setup.py test` has been declared by some (*citation needed*) to be a "failed experiment", not sure how much the community as a whole will go out of its way to support it... 🤔

**Comment by RichardFetzel** [comment]
Thanks for you answers. I was using [pyscaffold](https://pypi.org/project/PyScaffold/) to create my projects and they suggest to use "python setup.py test" to run unittests and coverage. How would you suggest to install dependencies and run pytest in a continous integration system?

**Comment by The-Compiler** [comment]
[tox](https://tox.readthedocs.io/en/latest/) is commonly used for that purpose (and I can recommend [cookiecutter](https://github.com/audreyr/cookiecutter) as a more generic scaffolding tool).

**Comment by nicoddemus** [comment]
Yes, while `python setup.py test` is very little used, `tox` is used in pretty much every Python project and defacto standard nowadays. 👍 

I'm closing this for now, but feel free to follow with further questions @RichardFetzel!

**Comment by RichardFetzel** [comment]
Thank you all for your help. I will try to use tox as soon as I have some time.
