### ISSUE TITLE
Pytest-qt on travis

### ISSUE THREAD

**Issue by Czaki** [pytest-dev/pytest-qt#266]
Add 
```
before_install:
        - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
```
to .travis.yml allows to run qt interface test on travis (xenial) without miniconda. 
Maybe add this to documentation?

**Comment by nicoddemus** [comment]
Hi @Czaki, thanks for the suggestion.

We have section in the FAQ which already suggests a travis configuration:

https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#xvfb-assertionerror-timeouterror-when-using-waituntil-waitexposed-and-ui-events

Do you know if that one is obsolete now because of `xenial`?

**Comment by Czaki** [comment]
My qui test are basic and I do not use wait for ui events, I wait only for signal. 
The problem which I meet is that during initialization of qt the test was Aborted:

**Comment by nicoddemus** [comment]
I see, thanks.

Basically Qt will `abort()` on many operations unless you have a `QApplication` created.

Perhaps we can change the title of that FAQ entry to also mention "aborted" errors like the one you were experiencing?

**Comment by Czaki** [comment]
Maybe add such section to help

## Abort Troubleshooting
if during launching test on travis or docker GUI test end with abort it may be connected with missing libraries. 
to check if it is connected with starting QApplication run code:
```python -c 'from PyQt5.QtWidgets import QApplication; QApplication([])' ```
If it end with such text on terminal:

> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
>
> Aborted (core dumped)
 
It suggest that some libraries are missing. 
For ubuntu xenial based docker and travis machines it could be  `libdbus-1-3 libxkbcommon-x11-0` to fix it in travis configuration add given lines to `.travis.yml` 
```
before_install:
  - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
```

For debugging missing libraries `ldd` program may be useful. This code checks which libraries are needed for xcb plugin:

``` 
ldd `python -c 'import PyQt5; import os.path; print(os.path.join(os.path.dirname(PyQt5.__file__), "Qt", "plugins", "platforms", "libqxcb.so"))'` 
```

and lines like `libxkbcommon.so.0 => not found` inform which libraries are missing.

**Comment by The-Compiler** [comment]
Merging this into #261 which seems quite similar.

**Comment by Rexeh** [comment]
> Maybe add such section to help
> 
> ## Abort Troubleshooting
> if during launching test on travis or docker GUI test end with abort it may be connected with missing libraries.
> to check if it is connected with starting QApplication run code:
> `python -c 'from PyQt5.QtWidgets import QApplication; QApplication([])' `
> If it end with such text on terminal:
> 
> > qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> > This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> > Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
> > Aborted (core dumped)
> 
> It suggest that some libraries are missing.
> For ubuntu xenial based docker and travis machines it could be `libdbus-1-3 libxkbcommon-x11-0` to fix it in travis configuration add given lines to `.travis.yml`
> 
> ```
> before_install:
>   - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
> ```
> 
> For debugging missing libraries `ldd` program may be useful. This code checks which libraries are needed for xcb plugin:
> 
> ```
> ldd `python -c 'import PyQt5; import os.path; print(os.path.join(os.path.dirname(PyQt5.__file__), "Qt", "plugins", "platforms", "libqxcb.so"))'` 
> ```
> 
> and lines like `libxkbcommon.so.0 => not found` inform which libraries are missing.

Thanks so much for this detail. I'm using pytest-qt with very basic QT functionality (no signals etc) and had a mare fixing this.

The last command saved my bacon, ended up needing to manually install

sudo apt-get install libxcb-randr0-dev libxcb-xtest0-dev libxcb-xinerama0-dev libxcb-shape0-dev libxcb-xkb-dev
sudo apt-get install -y libxcb-render-util0
sudo apt-get install -y libxcb-icccm4
sudo apt-get install -y libxcb-keysyms1
sudo apt-get install -y libxcb-image0

Now I'm up and running on Travis-Ci thanks!

**Comment by The-Compiler** [comment]
FWIW this is documented here: https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions

**Comment by Rexeh** [comment]
> FWIW this is documented here: https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions

Thanks, maybe needs updating as only said GitHub actions or azure but definitely needed for Travis also.

**Comment by adam-grant-hendry** [comment]
What about Windows OS support? There seems to be very minimal information in the documentation. e.g. the mentioned libraries are all for Linux users. How would a windows developer running Travis achieve the same thing?

**Comment by The-Compiler** [comment]
Yup - pytest-qt should work just fine out of the box on Windows, and also runs [its selftests there](https://github.com/pytest-dev/pytest-qt/blob/0a21e15f9af8ad4f1a487da03900b05bf1f7b915/.github/workflows/main.yml#L15). Not sure what more information you would expect, @adam-grant-hendry?
