### ISSUE TITLE
Have a complete example to quick started?

### ISSUE THREAD

**Issue by 625781186** [pytest-dev/pytest-qt#268]
can push doc's [Tutorial](https://pytest-qt.readthedocs.io/en/latest/tutorial.html) to github repo? 

I think it's too fragmented to affect my reading.

It's best to have a working example.

**Comment by The-Compiler** [comment]
I'm not sure what you mean - it's here: https://github.com/pytest-dev/pytest-qt/blob/master/docs/tutorial.rst

**Comment by 625781186** [comment]
@The-Compiler 
I think it's best to add an Example folder to the repository

![image](https://user-images.githubusercontent.com/30521429/61859894-9e74f480-aefb-11e9-9270-6249637a76e4.png)
