### ISSUE TITLE
Is it possible to use qbot outside of pytest?

### ISSUE THREAD

**Issue by jfemiani** [pytest-dev/pytest-qt#271]
This is a question. 
I want to work out how to test the UI by interactively controlling it using qbot in a terminal. 
That is, I want to type code using qbot, see the app respond, and decide what to type next. In this way I think I can more easily create the code for test cases.

**Comment by nicoddemus** [comment]
Hi @jfemiani,

I'm afraid that is not possible currently, `QtBot` is tightly integrated with pytest (it needs a `request` object).

I suggest you use `QTest` directly, which should provide all the functionality you need.

I'm closing this for now, but feel free to follow up with further questions. 👍
