### ISSUE TITLE
Can some one explain how to use or init qtbot with some example

### ISSUE THREAD

**Issue by santoshreddy254** [pytest-dev/pytest-qt#275]

**Comment by The-Compiler** [comment]
What's unclear from e.g. the first code snippet in the [README](https://github.com/pytest-dev/pytest-qt/blob/master/README.rst), or the [Tutorial](https://pytest-qt.readthedocs.io/en/latest/tutorial.html) in the documentation?

**Comment by santoshreddy254** [comment]
I figured out Sorry
