### ISSUE TITLE
Using QThread causes sefault

### ISSUE THREAD

**Issue by drone-ah** [pytest-dev/pytest-qt#276]
Hi,

I have just started using pytest-qt and have run across an issue with the use of `QThread`.

I have been able to isolate it into a simple example:

```
from PySide2.QtCore import QThread


def test_load(qtbot):
    thread = QThread()
    thread.start()

```

Running on Linux:
```
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.7.3rc1, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
PySide2 5.13.0 -- Qt runtime 5.13.0 -- Qt compiled 5.13.0
rootdir: /mnt/e/Projects/Desktop/YerToob.py
plugins: cov-2.7.1, mock-1.10.4, qt-3.2.2, testmon-0.9.16
collected 1 item                                                                                                                                                                                                  

../../tests/ui/test_login.py Aborted (core dumped)
```

Running on Windows (through pycharm)
```
aunching pytest with arguments E:/Projects/Desktop/YerToob.py/tests/ui/test_login.py in E:\Projects\Desktop\YerToob.py\tests\ui

============================= test session starts =============================
platform win32 -- Python 3.6.5, pytest-4.6.3, py-1.8.0, pluggy-0.12.0 -- E:\Projects\Desktop\YerToob.py\venv\Scripts\python.exe
cachedir: .pytest_cache
PySide2 5.13.0 -- Qt runtime 5.13.0 -- Qt compiled 5.13.0
rootdir: E:\Projects\Desktop\YerToob.py
plugins: cov-2.7.1, mock-1.10.4, qt-3.2.2, testmon-0.9.16
collecting ... collected 1 item

test_login.py::test_load 
Process finished with exit code -1073740791 (0xC0000409)
```

Any ideas on what might be causing this? Googling did not help me much though it does suggest the loading of multiple app instances as a possibility.

Any help in getting to the bottom of this would be appreciated.

Thank you :D

**Comment by The-Compiler** [comment]
That's a bug in your code, you can reproduce it without pytest easily:

```python3
import time

from PySide2.QtCore import QThread

def func():
    thread = QThread()
    thread.start()

func()
time.sleep(10)
```

from the [QThread documentation](https://doc.qt.io/qt-5/qthread.html#dtor.QThread):

> Deleting a running QThread (i.e. isFinished() returns false) will result in a program crash. Wait for the finished() signal before deleting the QThread.

When the QThread object goes out of scope, it'll be deleted by Python, and the aforementioned crash will happen.

To avoid that, you should clean up your thread properly, by e.g. calling `.exit()` and `.wait()` on it (you might want to move it to a fixture instead of doing that in a test).

**Comment by drone-ah** [comment]
Wow - easy when you know how eh?! ;) Thank you so much for your help :D
