### ISSUE TITLE
Core dump occurs when running tests on Travis CI with xvfb

### ISSUE THREAD

**Issue by luyuhuang** [pytest-dev/pytest-qt#282]
Hi All,

I'm using pytest-qt on Travis CI, but it aborted while running `pytest`. This is the Travis Job:

https://travis-ci.org/luyuhuang/DWords/jobs/627603386

And This is my test case:

```py
import random
from DWords import danmuku

def test_danmuku(qtbot):
    widget = danmuku.Danmuku("apple", "苹果", random.randrange(0, 200))
    qtbot.addWidget(widget)

    assert widget._word_label.text() == "apple"

def test_danmuku_with_paraphrase(qtbot):
    widget = danmuku.Danmuku("apple", "苹果", random.randrange(0, 200), True)
    qtbot.addWidget(widget)

    assert widget._word_label.text() == "apple 苹果"
```

I also tried running tests using `xvfb-run -a pytest`, but it also failed. See https://travis-ci.org/luyuhuang/DWords/jobs/627597976

Could you help me resolve this issue? Thank you very much.

**Comment by The-Compiler** [comment]
Can you try installing `libxkbcommon-x11-0` via apt?

**Comment by luyuhuang** [comment]
This works! Thank you very much!

**Comment by nicoddemus** [comment]
Great! Can you please close the issue @luyuhuang?

**Comment by luyuhuang** [comment]
> Great! Can you please close the issue @luyuhuang?

I closed. Thanks.
