### ISSUE TITLE
ReadTheDocs is not up to date

### ISSUE THREAD

**Issue by mchlnix** [pytest-dev/pytest-qt#285]
Just wanted to update the "QTest API" link in the reference section, since it was pointing to a dead link, only to find, that it already is updated in the source code.

Could it be, that the docs weren't built recently, so that the online version is out of date?

**Comment by nicoddemus** [comment]
Hi @mchlnix,

Yeah thanks for noticing! Somehow it lost the link with GitHub. It is now fixed.

Thanks!
