### ISSUE TITLE
sockets automatically terminated while running with pytest-qt

### ISSUE THREAD

**Issue by danielhrisca** [pytest-dev/pytest-qt#291]
I'm trying to test a PyQt application using pytest and pytest-qt. The setup is this:

1. the SERVER (the tested application) is running a TCP server for remote control. The MainWindow is handed to the qtbot
2. a CLIENT driver class sends commands to the SERVER

The CLIENT successfully connects to the TCP server. The CLIENT then sends the first message to the SERVER. When the SERVER tries to send back the reply, the sockets on both ends are terminated by the operating system.

There is no problem running the SERVER and CLIENT as regular python scripts, the problem only appears running with pytest.

**Comment by The-Compiler** [comment]
Do you have a way to reproduce this issue? Ideally, a minimal but runnable example - but if your project is public, that might work as well.
