### ISSUE TITLE
Qt5 application built on C++

### ISSUE THREAD

**Issue by cnachiappan** [pytest-dev/pytest-qt#296]
Thanks for developing this super useful plugin!!

From the documentation I understand it supports PyQt5 and PySide2 applications
Just curious to know if it will support native Qt5 applications developed in C++

**Comment by The-Compiler** [comment]
I don't think this makes sense - pytest-qt does "whitebox-testing" of your application, not blackbox-testing by using it "from the outside". If you wanted to test a C++ Qt application, you'd first need to write a Python wrapper for it so you can use it from Python (and thus pytest-qt).
