### ISSUE TITLE
Increase default timeout for waitExposed?

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#297]
Currently, the `waitExposed` default timeout is `1000`, i.e. one second. The default for the underlying [qWaitForWindowExposed](https://doc.qt.io/qt-5/qtest.html#qWaitForWindowExposed-1) has a default timeout of `5000`, i.e. 5 seconds.

In my experience, 1s is sometimes too short on Travis CI (when under heavy load), even for relatively simple widgets. Is there a good reason to deviate from the default 5s timeout Qt has? Maybe we should set it to `5000` instead as well?

**Comment by nicoddemus** [comment]
Oh I agree, if the default for `qWaitForWindowExposed` is 5000ms, we should do the same for `waitExposed`. I suspect it was an oversight rather than a conscious decision. 👍

**Comment by nicoddemus** [comment]
The timing out would be good, as the 4.0.0 release is not out yet. 👍
