### ISSUE TITLE
Use PyPI token in GitHub actions

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#303]
I just noticed this:

https://github.com/pytest-dev/pytest-qt/blob/e8080068d3ed215051231d5d5fd43fd1268e4eaa/.github/workflows/main.yml#L83-L86

It looks like https://github.com/pypa/pypi-support/issues/98 was taken care of.

**Comment by nicoddemus** [comment]
Thanks for noticing: https://github.com/pytest-dev/pytest-qt/pull/304
