### ISSUE TITLE
API break suggestions for 4.0

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#306]
As mentioned in https://github.com/pytest-dev/pytest-qt/pull/302#issuecomment-629513007 I went through the docs/code and thought about possible API breaks which would make sense for 4.0. Here are a couple of ideas:

- [x] 1. One thing that always irked me a bit is that we have two naming conventions (`add_widget` vs. `addWidget`). Is it really a good idea to support both? At least in my project, it only lead to using both inconsistently over the years without noticing. Should we get rid of one of those? On the other hand, that's probably a lot of churn for projects using pytest-qt, so I'm not sure if it's worth it. Maybe as an alternative, we could make it possible to configure the desired API style in `pytest.ini` so that the other style would raise an exception (that could be done after 4.0)?
- [x] 2. Right now the user needs to decide between `waitActive`, `waitExposed` and `waitForWindowShown` (which might be a hurdle if using the same tests for two different backends). Should we have a wrapper which decides what to use instead?
- [x] 3. Shouldn't `waitForWindowShown` have a `timeout` as well? (can be done after 4.0)
- [x] 4. Does anyone really use `qtbot.stopForInteraction()` instead of `qtbot.stop()`? A GitHub search [reveals 60 results](https://github.com/search?q=qtbot.stopForInteraction&type=Code), vs. [122 results](https://github.com/search?q=%22qtbot.stop%22&type=Code) for `.stop()`, though I guess it's mostly used interactively for debugging without being added to the code. Should we remove the long name?
- [x] 5. Should we raise the default timeout for `waitSignal()` to 5000, similar to [QSignalSpy.wait()](https://doc.qt.io/qt-5/qsignalspy.html#wait) in Qt and the other default timeouts in pytest-qt?
- [x] 6. `waitSignal` and `waitSignals` can take `None` instead of a signal, in which case they just wait until the timeout occurred. But we already have `qtbot.wait()` for that, so is there a reason to support it?
- [x] 7. Can we get rid of the `SignalTimeoutError` compatibility alias for `TimeoutError`?
- [x] 8. The docs for `pytestqt.logging.Record` says that `context` is only available for Qt 5, that can probably be removed now (can be done after 4.0)
- [x] 9. (new, see below) Get rid of `qt_wait_signal_raising`
- [x] 10. (new, see below) Get rid of aliases in `plugin.py`

**Comment by nicoddemus** [comment]
Thanks a lot for working on this list Florian!

1. Indeed, that's something I regret. Today, I would have rather started with PEP-8, but that not being the case, adding an alternative API is also a regret. I agree it is probably a lot of churn. Not sure about the option, it is very weird (never seen an option like this).

2. Good idea, if that is possible. 👍 

3. Sounds good.

4. Agreed, once users learn the short form, there's really no reason to use the long one. Also this is a simple find replace on a very uncommon name, so 👍 from me.

5. Definitely!

6. Sounds good too.

7. 👍 

8. 👍 

Given all the breaking changes we are planning for 4.0, we might write a short "upgrade guide" (for example, replace all `.stopForInteraction` calls by `.stop`, check timeouts for `waitForWindowShown`, etc).

We might decide to put those in the CHANGELOG though: we announce the change, and also what to do to upgrade.

**Comment by The-Compiler** [comment]
Another one: We should probably remove `qt_wait_signal_raising` (legacy alias for `qt_default_raising`).

**Comment by The-Compiler** [comment]
And yet another one, in `plugin.py`:

```python
# classes/functions imported here just for backward compatibility before we
# split the implementation of this file in several modules
assert QtBot
assert SignalBlocker
assert MultiSignalBlocker
assert Record
assert capture_exceptions
assert format_captured_exceptions
```

I suppose those can go away?

**Comment by nicoddemus** [comment]
> Another one: We should probably remove qt_wait_signal_raising (legacy alias for qt_default_raising).

Agree. 👍 

> I suppose those can go away?

Not sure, this will force whoever is importing this to import from the actual module. Perhaps it makes sense to still have every name being imported from `pytestqt.plugin` instead of where they are declared?

**Comment by The-Compiler** [comment]
> Not sure, this will force whoever is importing this to import from the actual module. Perhaps it makes sense to still have every name being imported from `pytestqt.plugin` instead of where they are declared?

But the `pytestqt.plugin` module seems like a weird place for such convenience imports (if you ignore the historical reason why they're there) - I can see how this would make sense in `__init__.py` (so that people could import directly from the `pytestqt` package), but `plugin.py` for me says "this is the interface to pytest" and wouldn't be the place I'd look for classes to use "manually".

I did a quick [GitHub code search](https://github.com/search?q=pytestqt.plugin+-extension%3Ajson&type=Code) (also tried [grep.app](https://grep.app/search?q=pytestqt.plugin) and [Debian Code search](https://codesearch.debian.net/search?q=pytestqt.plugin&literal=1), with less results). It looks like this'd affect almost nobody:

- Spyder IDE [imports QtBot](https://github.com/spyder-ide/spyder/blob/01d9195b1a33d02f42faf3c8e0047412966a24ce/spyder/plugins/completion/tests/conftest.py#L29) to create a module-scoped qtbot fixture.
- Same for Spyder and QtBot [in another place](https://github.com/spyder-ide/spyder-terminal/blob/a3ed2d5f1602de453f1a6cc1b3babf51f95f14df/spyder_terminal/tests/test_terminal.py#L130)
- Spyder and QtBot [again](https://github.com/spyder-ide/spyder/blob/01d9195b1a33d02f42faf3c8e0047412966a24ce/spyder/plugins/completion/providers/languageserver/tests/conftest.py#L13), unused import
- Phy [uses QtBot](https://github.com/cortex-lab/phy/blob/master/phy/apps/tests/test_base.py#L251) to have it on the test class instead of using a fixture
- qutebrowser [uses SignalBlocker](https://github.com/qutebrowser/qutebrowser/blob/master/tests/end2end/fixtures/testprocess.py#L201) for some custom API needing to wait for signals
- Various places using `pytestqt.plugin.QtBot` in Sphinx docstrings

Compare that to a search for [pytestqt.qtbot](https://github.com/search?q=pytestqt.qtbot+-extension%3Ajson&type=code) which yields 125 results, mostly from people using `pytestqt.qtbot.QtBot` in type annotations.

As for the split modules:

- Nobody uses [`pytestqt.wait_signal`](https://github.com/search?q=pytestqt.wait_signal+-extension%3Ajson&type=Code)
- One project [uses `pytestqt.logging`](https://github.com/Transpyler/qturtle/blob/79ecc3a452c8dfdcc15007b500f7b95864148525/tests/conftest.py) for some monkeypatching involving private APIs
- 15 or so [use `pytestqt.exceptions.TimeoutError`](https://github.com/search?q=pytestqt.exceptions+-extension%3Ajson+-extension%3Aebuild&type=Code)
-  One project [uses `pytestqt.exceptions.capture_exceptions`](https://github.com/ilastik/ilastik/blob/7e973b17f45921598735371b466cb9e668212834/tests/test_ilastik/test_applets/batchProcessing/test_batchProcessingGui.py#L5)

So it looks like direct usage of the API (outside of `qtbot`) is incredibly rare, and for those who use it, they already use split modules. The only exception maybe is `pytestqt.plugin.QtBot` which is used in a couple of places, but I'd still prefer to have one genuine place for it, even if Spyder and Phy will need to adjust.

**Comment by nicoddemus** [comment]
Thanks for the research! Agreed then, let's ditch those convenience imports. 👍

**Comment by The-Compiler** [comment]
So I had a quick look at the `waitActive`, `waitExposed` and `waitForWindowShown` situation, and here's what I gathered:

- [qWaitForWindowActive](https://doc.qt.io/qt-6/qtest.html#qWaitForWindowActive) and [qWaitForWindowExposed](https://doc.qt.io/qt-6/qtest.html#qWaitForWindowExposed) (which we expose as `waitActive` and `waitExposed`) were added in Qt 5.0 and still exist in Qt 6.
- qWaitForWindowShown is [obsolete in Qt 5](https://doc.qt.io/qt-5/qtest-obsolete.html) and removed in Qt 6. In other words, it's what to use with Qt 4.
- It looks like the problem with `qWaitForWindowShown` is [indeed that the name is confusing](https://codereview.qt-project.org/c/qt/qtbase/+/20233), and it's [indeed just an alias to `qWaitForWindowActive`](https://github.com/qt/qtbase/blob/v5.15.2/src/widgets/kernel/qtestsupport_widgets.h#L55)
- In pytest-qt, we [originally used `qWaitForWindowShown` if available](https://github.com/pytest-dev/pytest-qt/commit/d9491cec90aec5dcfb2b74db76e95fab933ad976#diff-5ff7915065f4b0576143e7d1cb228a31bc57d65e4112969cddd0399065e46074) (falling back to `qWaitForWindowExposed` otherwise), but this was changed later [as part](https://github.com/pytest-dev/pytest-qt/pull/159/files#diff-5d28845d0c2a3c460c8c8afe776c66b1d7f9f681539bc73adeb1d6307a743965L158) of #159.

Now with Qt 4 support dropped, in theory we could also drop `waitForWindowShown` entirely. However, it seems quite widely used:

- GitHub search: [238 results camel case](https://github.com/search?q=qtbot.waitForWindowShown&type=code), [13 results snake case](https://github.com/search?q=qtbot.wait_for_window_shown&type=code)
- grep.app: [60 results](https://grep.app/search?q=qtbot%5C.%28waitForWindowShown%7Cwait_for_window_shown%29&regexp=true)
- Debian Code Search: [1 result](https://codesearch.debian.net/search?q=qtbot%5C.%28waitForWindowShown%7Cwait_for_window_shown%29&literal=0) (plus pytest-qt)

So I'm not sure how to proceed here. Options I can think of:

- Keep the wrapper but add a deprecation warning
- As above, but fail hard if `PYTEST_QT_API` is set to PySide6/PyQt6 (because the upstream method is fully gone there)
- Remove the wrapper and force people to adjust, given that this has been deprecated in Qt for 9 years and we're doing a major release here

What do you think @nicoddemus?

**Comment by nicoddemus** [comment]
Thanks for the detailed info!

> Remove the wrapper and force people to adjust, given that this has been deprecated in Qt for 9 years and we're doing a major release here

I like this, but how about we keep the wrapper, but raise a hard error instead? Something like `raise RuntimeError("qtbot.waitForWindowShown() is no longer available, please use qtbot.waitActive() instead")`. This will force everyone to upgrade, but with a nice message pointing them in the right direction, rather than a simple `AttributeError: waitForWindowShown`. What do you think?

**Comment by The-Compiler** [comment]
Not sure honestly. It would be the easiest method for sure, but with something so widely used (and `waitActive` / `waitExposed` being unavailable with PySide2) it seems a bit harsh to remove it without any kind of deprecation period?

**Comment by nicoddemus** [comment]
Hmm good point, no problem then, I think we can keep the wrapper but add a deprecation warning. 👍

**Comment by The-Compiler** [comment]
Ugh, it gets worse: `waitForWindowShown` does *not* raise `TimeoutError` on timeout, so it can totally happen that it just waits for 5s without the window being exposed, and then the code continues to run.

In fact, we have a mistake like that in our own testsuite:

https://github.com/pytest-dev/pytest-qt/blob/5ea3a3d292dd30b721ef333d9372a221abbbd5a9/tests/test_basics.py#L103-L111

We never call `.show()` here, which seems to cause QTest to [bail out early](https://github.com/qt/qtbase/blob/v5.15.2/src/widgets/kernel/qtestsupport_widgets.cpp#L87), so this `waitForWindowShown` call actually didn't do anything at all.

But given the widespread usage, I still think deprecating it is the right thing to do - I guess typically it's not that people want to really know whether a window was shown or not, they just want to wait before e.g. starting to click.

**Comment by The-Compiler** [comment]
Ugh, it gets worse: `waitForWindowShown` does *not* raise `TimeoutError` on timeout, so it can totally happen that it just waits for 5s without the window being exposed, and then the code continues to run.

In fact, we have a mistake like that in our own testsuite (ever since the test was added in 19661b4bb359b3118826badbd6dd38fc79e32b61):

https://github.com/pytest-dev/pytest-qt/blob/5ea3a3d292dd30b721ef333d9372a221abbbd5a9/tests/test_basics.py#L103-L111

We never call `.show()` here, which seems to cause QTest to [bail out early](https://github.com/qt/qtbase/blob/v5.15.2/src/widgets/kernel/qtestsupport_widgets.cpp#L87), so this `waitForWindowShown` call actually didn't do anything at all.

But given the widespread usage, I still think deprecating it is the right thing to do - I guess typically it's not that people want to really know whether a window was shown or not, they just want to wait before e.g. starting to click.

**Comment by The-Compiler** [comment]
All done! :tada:

**Comment by nicoddemus** [comment]
Awesome! 

All credits go to @The-Compiler which did nearly all the work here. 🎉
