### ISSUE TITLE
Expose qWait and qSleep

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-qt#31]

**Comment by nicoddemus** [comment]
Unfortunately PySide does not expose those functions... they're simple though so it's no big loss.

**Comment by nicoddemus** [comment]
Reopened per request on #107

**Comment by The-Compiler** [comment]
I don't think `qSleep` is needed, as it seems equal to `time.sleep`.

As for `qWait` which is a non blocking wait, maybe something simple in `pytest-qt` instead would be better, i.e. basically just an alias for `qtbot.waitSignal(None, timeout=x)` or so?

**Comment by nicoddemus** [comment]
> I don't think qSleep is needed, as it seems equal to time.sleep

Agreed.

> As for qWait which is a non blocking wait, maybe something simple in pytest-qt instead would be better, i.e. basically just an alias for qtbot.waitSignal(None, timeout=x) or so?

Hmm seems reasonable, but then I would name it just `qtbot.wait` since it is not calling the original `qWait` implementation.

**Comment by The-Compiler** [comment]
Yeah, sure - I thought it'd be named `qtbot.wait` anyways, like with `waitForWindowShown`.

**Comment by nicoddemus** [comment]
Cool. :sunglasses:

**Comment by The-Compiler** [comment]
This was fixed in #110.
