### ISSUE TITLE
Should macOS be included in CI?

### ISSUE THREAD

**Issue by altendky** [pytest-dev/pytest-qt#311]
I was having some trouble over in https://github.com/altendky/qtrio/pull/126 with the macOS builds and a test where I `qtbot.mouseClick(button, QtCore.Qt.LeftButton)`.  Switching to `button.click()` seemed to fix it.  Sometimes the signal processing would be delayed or maybe just not happen.  This is admittedly mixing Qt with Trio so sure, extra stuff to worry about.  But I went ahead and tried running pytest-qt against macOS in GitHub Actions and found it does in fact fail a few signal related tests.  I have included the failures below but really addressing them would presumably belong in another/other ticket(s).  Possibly against Qt, I don't know.

So, should macOS testing be added to pytest-qt CI?  (at least after the tests pass)

I'll admit that the issue does seem at least a bit specific to GitHub Actions.  The QTrio tests passed fine on my MacStadium-donated macOS system.

https://github.com/altendky/pytest-qt/pull/1/checks?check_run_id=938879883
https://gist.github.com/altendky/36f75acb06ffdc9b49d7658c11b88543#file-gistfile1-txt-L674-L677
```
2020-08-03T02:51:36.1804550Z FAILED tests/test_wait_signal.py::test_signal_triggered[200-None-True-context_manager_wait-True]
2020-08-03T02:51:36.1805670Z FAILED tests/test_wait_signal.py::test_signal_triggered[200-None-True-context_manager_wait-False]
2020-08-03T02:51:36.1806460Z FAILED tests/test_wait_signal.py::test_signal_triggered_multiple[200-300-400-True-explicit_wait-True]
2020-08-03T02:51:36.1807260Z FAILED tests/test_wait_signal.py::test_signal_triggered_multiple[200-300-400-True-context_manager_wait-True]
```

**Comment by The-Compiler** [comment]
FWIW those failures just look timing-related, increasing the deadlines a bit would probably help. I'm guessing macOS runs a bit slower on GitHub Actions than what the testsuite expects.

**Comment by nicoddemus** [comment]
I wouldn't mind adding it in a PR and see what happens. If we can get it to pass, we can then include it in the official CI, no problem.

@altendky it seems you already have something in place, would you like to open a PR with that?

**Comment by altendky** [comment]
@The-Compiler, yeah, I've definitely had issues with the macOS runners being slow.  Intermittently very slow.  I finally kicked out my run-a-single-trivial-test-in-a-subprocess timeout to 40 seconds.  We'll see if that cuts it.

And yeah, I'll check the errors, extend timeouts, etc and see where we get.
