### ISSUE TITLE
Failure in test_qt_tester_invalid returned FALSE (qabstractitemmodeltester.cpp:*)'

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [pytest-dev/pytest-qt#314]
With qtcore-5.15.0 and qttest-5.15.0, I'm getting a failure in `test_qt_tester_invalid` in `tests/test_modeltest.py`:

This seems to be the problem:
```
E       nomatch: '* QtWarningMsg: FAIL! model->columnCount(QModelIndex()) >= 0 () returned FALSE (qabstractitemmodeltester.cpp:*)'
E           and: '    QtWarningMsg: FAIL! model->columnCount(QModelIndex()) >= 0 () returned FALSE (/var/tmp/portage/dev-qt/qttest-5.15.0/work/qtbase-everywhere-src-5.15.0/src/testlib/qabstractitemmodeltester.cpp:324)'
```

For some reason it is getting the whole build path of `qabstractitemmodeltester.cpp` instead of just the file name. An easy solution would be to use `*qabstractitemmodeltester.cpp:*` instead of `qabstractitemmodeltester.cpp:*` or python's `basename()` function. But as I'm unsure of what this should be doing, I'm hesitant to just patch it, perhaps there is some deeper underlying issue (either here or in qttest)? This used to work just fine with earlier qt versions.

Bug has been reported here: https://bugs.gentoo.org/738264
Full build log: [build.log](https://github.com/pytest-dev/pytest-qt/files/5146520/build.log)

**Comment by nicoddemus** [comment]
Hi @AndrewAmmerlaan,

A patch seems fine, that match (AFAIR) doesn't need to be exact. An upstream patch would be appreciated as well.

**Comment by AndrewAmmerlaan** [comment]
> Hi @AndrewAmmerlaan,
> 
> A patch seems fine, that match (AFAIR) doesn't need to be exact. An upstream patch would be appreciated as well.

Hi @nicoddemus 

I just created a Pull Request that fixes the problem for me, let me know if it needs any changes :smile:

**Comment by nicoddemus** [comment]
That looks great, thank you!
