### ISSUE TITLE
Tested versions in readme dont match actual tested versions

### ISSUE THREAD

**Issue by farisachugthai** [pytest-dev/pytest-qt#318]
https://img.shields.io/pypi/pyversions/pytest-qt.svg

Shows different tested versions than whats listed in the github workflows. Currently it lists 2.7, 3.4, 3.5, 3.6 but 3.6 to 3.8 are tested.

I assume that this occured with an update to the main.yml without a new release, otherwise Im not sure how this happened.

**Comment by nicoddemus** [comment]
That badge shows the state of the latest release in PyPI, which is 3.3.0, and that is correct. 👍 

The current `master` is for 4.0.0, which indeed only tests >=3.6.
