### ISSUE TITLE
How to use the scope="module"

### ISSUE THREAD

**Issue by maniachhz** [pytest-dev/pytest-qt#32]
Dear all,

I want to test my PyQt software with pytest-qt. I want to use "module"  scope, but the qtbot limit is "function",  My testing code is as bellows:
```pthon
#!/usr/bin/env python

import pytest

from mainwindow import *
from productive_maintenance import *
from PyQt4 import QtGui, QtCore

class Window:
    def __init__(self, qtbot):
        app = QApplication(sys.argv)
        connx = connectDB()
        logDialog = LoginDialog(connx)  # login dialog
        qtbot.addWidget(logDialog)
        qtbot.keyClicks(logDialog.lineEditUsername, "huang")
        qtbot.keyClicks(logDialog.lineEditPassword, "123456")
        qtbot.mouseClick(logDialog.pushButtonLogin, QtCore.Qt.LeftButton)
        assert logDialog.result() == True
        self.window = MainWindow(connx)  # main window
        self.window.show()
        qtbot.addWidget(self.window)


@pytest.fixture(scope='module')
def ui(qtbot):
    return Window(qtbot).window

class TestProductiveMaintenance:
    def test_username(self,ui):
        assert ui.userInfo['userid'] == "huang"
        
    def test_user_group(self, ui):
        assert ui.userInfo['user_group'] == 'administrator'
```
After i run py.test, i got the errors:
ScopeMismatchError: you tried to access the "function" scope  fixture "qtbot".....

How to use the qtbot fixture to module? Thanks.

**Comment by nicoddemus** [comment]
Hi,

*Short answer*

Due to pytest's scope rules you can't use a narrow scope fixture (`"function"`) from within a broad scope fixture (`"session"`). You can however copy the code used to define `qtbot` and generate a new `"session"` scoped-fixture:

```python
@pytest.yield_fixture(scope="session")
def qtbot_session(qapp, request):
    result = QtBot(qapp)
    with capture_exceptions() as exceptions:
        yield result
    if exceptions:
        pytest.fail(format_captured_exceptions(exceptions))
    result._close()
```

And use that in your `ui` fixture.

*Long answer*

`qtbot` is `"function"` scoped because you don't want tests to interfere with each other. `"session"` scoped fixtures should be used only to initialize slow resources which are read-only and don't change during a test run, and thus can be reused without problems by different tests. From your example, that does not seem to be the case for the `ui` fixture you created. Can you elaborate a little on why you want your `ui` fixture to be `"session"` scoped?

Also, your `Window` class seems to be doing a lot of unrelated work, like creating a `connectDB` instance and attempting to login using another dialog, plus it is creating a `QApplication` instance again, when it should probably be using the instance already initialized in `QApplication.instance()`. Is `Window` meant to be used in production, or for testing only?

**Comment by maniachhz** [comment]
@nicoddemus , thank you.

My software need to connect to remote database and execute sql commands to get or insert datas to database. 
So i want to instance  ```connectDB``` and  main window UI  "session"  or "module" scoped just once time, then i can test  insert commands  interactive with remote database, no need to instance connecting the database each test_function.  What's your opinion? May be you can help me.

```Is Window meant to be used in production, or for testing only?```
It's just for testing only.

I copy the code 
```
#!/usr/bin/env python

import pytest

from mainwindow import *
from productive_maintenance import *
from PyQt4 import QtGui, QtCore


class Window:
    def __init__(self, qtbot):
        app = QApplication.instance()
        connx = connectDB()
        logDialog = LoginDialog(connx)  # login dialog
        qtbot.addWidget(logDialog)
        qtbot.keyClicks(logDialog.lineEditUsername, "huanghanzhen")
        qtbot.keyClicks(logDialog.lineEditPassword, "123456")
        qtbot.mouseClick(logDialog.pushButtonLogin, QtCore.Qt.LeftButton)
        assert logDialog.result() == True
        self.window = MainWindow(connx)  # main window
        self.window.show()
        qtbot.addWidget(self.window)

@pytest.yield_fixture(scope="session")
def qtbot_session(qapp, request):
    result = QtBot(qapp)
    with capture_exceptions() as exceptions:
        yield result
    if exceptions:
        pytest.fail(format_captured_exceptions(exceptions))
    result._close()

@pytest.fixture(scope='session')
def ui(qtbot_session):
    return Window(qtbot_session).window

class TestProductiveMaintenance:
    def test_username(self,ui):
        assert ui.userInfo['userid'] == "huanghanzhen"
        
    def test_user_group(self, ui):
        assert ui.userInfo['user_group'] == 'administrator'
```
but I got the erros:
```global name 'QtBot' is not defined...```

**Comment by nicoddemus** [comment]
Sorry, I forgot to add the import statements needed:

```python
from pytestqt.plugin import format_captured_exceptions, QtBot
```

But in my opinion you should separate the logic of creating a database connection out of `LoginDialog` class by refactoring it into a separate function (say, `create_connection`), which can then be used by both `LoginDialog` class and in your tests like this:

```python
@pytest.fixture(scope='session')
def db_connection(request):
    conn = create_connection("huanghanzhen", "123456")
    request.addfinalizer(conn.finalize)
    return conn

@pytest.fixture
def ui(qtbot, db_connection):
    return MainWindow(connectDB)
```

This will improve your code by making it easier to test it while taking care of your performance concerns by initializing the connection exactly once.

Cheers,

**Comment by maniachhz** [comment]
@nicoddemus ,
You are right. Thank you very mach!
