### ISSUE TITLE
Fatal Python error when pytest initializes fixture (qtbot, qapp)

### ISSUE THREAD

**Issue by mcow** [pytest-dev/pytest-qt#324]
Sorry if this is gauche, but I'm just going to leave a link to my [stackoverflow](https://stackoverflow.com/questions/64959516/why-a-fatal-python-error-when-testing-using-pytest-qt) question. There is a short test script there that reproduces the problem, at least on my system.

I've been looking through issues here, both open and closed, looking for something similar, but I haven't seen it. I did link from my SO question to another question there with a similar complaint.

**Comment by The-Compiler** [comment]
You might want to check the [troubleshooting page](https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html) in the docs. Also, running without output capturing (`pytest -s`) might tell you more about what's going on.

**Comment by mcow** [comment]
I'm not programming in Qt myself, I'm just trying to write a test that verifies the signals (written by someone else, for their UI) are getting triggered. I don't recognize most of what's described at that Troubleshooting page, but it doesn't look like any of it pertains. There is a `DISPLAY` defined, for whatever that's worth.

Running pytest with `-s` yields no difference in the printed output.

**Comment by The-Compiler** [comment]
Are you sure the required libraries are installed as well?

I forgot that we didn't release #300 yet, can you try with `-s --no-qt-log` instead?

**Comment by mcow** [comment]
Thanks; running with `-s --no-qt-log` results in the following additional information:
```test_min.py qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""```

I see the Troubleshooting page mentions xcb: "Since Qt in version 5.15 xcb libraries are not distributed with Qt so this library in version at least 1.11 on runner." The part of that after "not distributed with Qt" is incomprehensible (not grammatical). I searched PyPI for "xcb" and found three unpromising entries. 

The Qt5.12 used here may in fact be incomplete, but libqxcb.so is present. (As I noted at the Stackoverflow question, my system has Qt5.9 installed systemwide but 5.12 is used by our software, and those libraries are kept in a private folder; my `LD_LIBRARY_PATH` points to that folder. )

  = = =

FWIW: I looked at the pytest-qt source at the point of the crash: pytestqt/plugin.py", line 57 in qapp.
`_qapp_instance = qt_api.QApplication(qapp_args)`

But my test is using qtbot, not qapp. I saw the qtbot fixture accepts qapp as a parameter, but does nothing with it. I tried removing the qapp parameter from the qtbot function and re-ran: this did **not** result in the Fatal Python error; I did get other errors that I don't understand yet, but at least they don't abort the pytest process.

**Comment by The-Compiler** [comment]
Those are system-wide libraries which you need to install, not Python ones.

I assume if you run something like:

```python3
from PyQt5.QtWidgets import QApplication
app = QApplication([])
```

on your system, you'll see the exact same issue.

Your change would avoid creating a QApplication, but pytest-qt (or even your signals and slots) won't work without one.

**Comment by mcow** [comment]
Thanks again. That gave me enough to go on, along with a hint from a coworker to define `QT_DEBUG_PLUGINS`, to create a workaround: I created `/usr/bin/platforms` and added a soft link to the `libqxcb.so` that's in the folder with the Qt5.12 libraries. 

With this, I can run my sample test without needing to modify pytest-qt. That's enough for me to proceed with my test development, and I'll leave it up the people working on our software's installation to figure out how to get the Qt installation "right".
