### ISSUE TITLE
Is there a way to query for widgets?

### ISSUE THREAD

**Issue by samfrances** [pytest-dev/pytest-qt#325]
Does pytest-qt provide some way to query for widgets in the "tree" of the UI without making them "public" attributes of some parent widget? I'm thinking of something similar to the `queryByTestId()` facility that some testing libraries use in the context of javascript frontend applications.

**Comment by The-Compiler** [comment]
pytest-qt mainly exposes Qt's APIs - here, you could use `QObject.findChild(ren)` on some parent object or `QApplication.topLevelWidgets()`/`QApplication.allWidgets()`. I don't think there's anything that pytest-qt could/should do here.
