### ISSUE TITLE
Update for PyQt6 compatibility

### ISSUE THREAD

**Issue by othalan** [pytest-dev/pytest-qt#328]
[PyQt6 has been released](https://www.riverbankcomputing.com/news/PyQt_v6.0.0_Released) but pytest-qt does not yet support the new version. This causes most tests in my project to fail with the following error, though the application works as expected.

Example error (last few lines only):

```
INTERNALERROR>   File "/usr/local/var/pyenv/versions/3.9.0/envs/mn390/lib/python3.9/site-packages/pytestqt/qt_compat.py", line 83, in set_qt_api
INTERNALERROR>     raise RuntimeError(msg)
INTERNALERROR> RuntimeError: pytest-qt requires either PySide, PySide2, PyQt4 or PyQt5 to be installed
INTERNALERROR>   PyQt4.QtCore: No module named 'PyQt4'
INTERNALERROR>   PyQt5.QtCore: No module named 'PyQt5'
INTERNALERROR>   PySide.QtCore: No module named 'PySide'
INTERNALERROR>   PySide2.QtCore: No module named 'PySide2'
```

**Comment by nicoddemus** [comment]
Thanks @othalan, indeed we need to take some time to add Qt 6 support. 👍

**Comment by The-Compiler** [comment]
FWIW I'm unlikely to work on this until we get closer to Qt 6.1 or 6.2 (when QtWebEngine and other modules are coming back).

**Comment by The-Compiler** [comment]
@othalan @GuillaumeFavelier @rbreu If anyone of you has a PyQt6 project to test with, it'd be great if you could try #340. For my own project I'm still waiting for QtWebEngine to come back with Qt 6.2, but at least pytest-qt's selftests now work with PyQt6 :tada:

**Comment by GuillaumeFavelier** [comment]
Thanks for the heads-up! I will definitely start experimenting with it soon :)

**Comment by rbreu** [comment]
Hi, I just wanted to let you know that I have ported all my unit tests from my previous workaround to pytest-qt and it works. Thank you so much!
