### ISSUE TITLE
Port to PyQt5

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-qt#33]

**Comment by jdreaver** [comment]
:thumbsup: 

I just started using PyQt5, and I would love to help! I will get to it this weekend unless you are already working on it.

**Comment by nicoddemus** [comment]
Hi @jdreaver!

I already completed the porting, you can see it in the [pyqt5 branch](https://github.com/pytest-dev/pytest-qt/tree/pyqt5). :smile:

I plan to release it soon, I was just holding it a bit because I'm helping porting [qutebrowser](https://github.com/The-Compiler/qutebrowser) to pytest in the [adopt pytest month](http://pytest.org/latest/adopt.html) effort so I'm using it as a test bed to ensure everything works appropriately. 

If you need this right away, let me know... I can rush the release a bit if you need it.

Cheers, :beers:

**Comment by nicoddemus** [comment]
Here's the [PR](https://github.com/pytest-dev/pytest-qt/pull/34) if you would like to comment on.

**Comment by jdreaver** [comment]
My goodness, I should have looked at the pull requests... I just did this too on [my fork](https://github.com/jdreaver/pytest-qt/tree/pyqt5) haha. Oh well!

It looks like I did exactly what you did:
* Choose between PyQt4, PyQt5, and PySide with an environment variable (your name of `PYTEST_QT_API` is better)
* Fix obvious API changes (qWaitForWindowShown, QApplication, QWidget, etc)
* Update travis (w/ Python 3.4 testing)

An early release would be cool if you have the time. I am doing a ton of PyQt5 porting over the weekend and I use continuous integration, so it would be nice to just update the version number. I will play with your fork to help test it.

Thanks!

**Comment by nicoddemus** [comment]
Haha! :smile: 

About the release, if you could help test it, it would be great. Let me know once you're done testing and I'll make a release, no problem!

Cheers! :beers:

**Comment by nicoddemus** [comment]
I'm actually having trouble running python `3.4` on travis... see the [build log](https://travis-ci.org/pytest-dev/pytest-qt/jobs/57088832). Are you having the same problem, or do you use another CI service?

**Comment by jdreaver** [comment]
I use a custom buildbot application, not Travis :/ I looked at the log, search the error, and I found [this thread](https://github.com/travis-ci/travis-ci/issues/2219#issuecomment-41804942). It looks like you can't use python 3.4 with system site packages because they are using an old OS. I would just stick to Python 3.2 I suppose.

**Comment by nicoddemus** [comment]
Yep, I have found that thread earlier this week... bummer. Oh well. :)

I will make the release shortly.

**Comment by The-Compiler** [comment]
I really hope Travis will update their OS at some point... The lack of Qt5 (or outdated Qt5, I don't remember) is also the reason I can't use it...

**Comment by nicoddemus** [comment]
Release [1.3.0](https://github.com/pytest-dev/pytest-qt/releases/tag/1.3.0) is out! Thanks for the help @jdreaver! :smile:

**Comment by jdreaver** [comment]
@nicoddemus and @The-Compiler, just so you know, I am working on putting pyqt5 in conda. I currently have a linux version [here on binstar](https://binstar.org/jdreaver/pyqt5). I have only tried it on my Arch Linux machine, so I haven't advertised it as ready yet. Maybe in the future, people can use conda on Travis CI for their pyqt5 builds, and just use my binstar package.

It's an option if you are willing to use conda. I wish Anaconda just officially included pyqt5 anyway though :)

**Comment by nicoddemus** [comment]
I seen your commits on [conda-recipes](https://github.com/conda/conda-recipes), hehehe. Thanks for the info!

When I have some time I will try to use your package from travis using conda. :smile:

**Comment by nicoddemus** [comment]
For future reference: http://conda.pydata.org/docs/travis.html
