### ISSUE TITLE
Release of Version 4.0.0

### ISSUE THREAD

**Issue by Shahprogrammer** [pytest-dev/pytest-qt#352]
When will the version 4.0.0 will be released?

**Comment by nicoddemus** [comment]
Hi @Shahprogrammer,

Probably shortly after https://github.com/pytest-dev/pytest-qt/pull/340 gets merged, I would say.

**Comment by Shahprogrammer** [comment]
Ok. Thanks. @nicoddemus

**Comment by The-Compiler** [comment]
I'd like to take care of #306 too first. I plan to get back to both next week finally.

**Comment by The-Compiler** [comment]
#340 is now finished in my eyes, will proceed with the rest once that's merged. I've also created [a new milestone](https://github.com/pytest-dev/pytest-qt/issues?q=is%3Aopen+is%3Aissue+milestone%3Av4.0.0) for v4.0.0 which seems like a better way to track what's remaining, so I'm now closing this issue.

**Comment by The-Compiler** [comment]
4.0.0 [is out now](https://twitter.com/the_compiler/status/1400490856549949452)! :tada:
