### ISSUE TITLE
Use kwonly arguments for wait*

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#366]
While reading this I realized `waitSignal` (and friends) have this signature:

```python
def waitSignal(self, signal, timeout=5000, raising=None, check_params_cb=None):
```

While IMHO this would be better:

```python
def waitSignal(self, signal, *, timeout=5000, raising=None, check_params_cb=None):
```

(Of course this is an artifact from Python 2 support).

Don't want to pile this on for 4.0, just commenting to see what you think.

_Originally posted by @nicoddemus in https://github.com/pytest-dev/pytest-qt/pull/363#discussion_r644240304_

**Comment by The-Compiler** [comment]
I'm a bit torn about `timeout` - should it be kwonly as well, or not?

Doing `waitSignal(some_signal, 1000)` seems relatively clear, and the pytest-qt testsuite uses `waitUntil` like that even:

https://github.com/pytest-dev/pytest-qt/blob/ad2c0bd068a7925811dc4d84d700c6ee20f6929f/tests/test_wait_until.py#L8

on the other hand, there only seem to be [two other projects on grep.app](https://grep.app/search?q=qtbot%5C.wait.%2A%2C%5B%5E%3D%5Cn%2A%5D%2A%5C%29%24&regexp=true) using it this way.

**Comment by nicoddemus** [comment]
I personally prefer `timeout=1000` to be crystal clear; it is a few keystrokes which improve readability.
