### ISSUE TITLE
QApplication.exit in test makes subsequent tests fail

### ISSUE THREAD

**Issue by storax** [pytest-dev/pytest-qt#37]
I am testing an application. When the application quits, it calls QApplication.exit. This could happen, because of a teardown, or because I want to test, how the application quits.
In all subsequent tests, the QApplication is still in an exit state. Things like qtbot.waitSignal will stop working. I can workaround that problem for now, but it seems like an unexpected behaviour. The qtbot fixture should make sure, that the QApplication has not already quit, for each function.

**Comment by nicoddemus** [comment]
Hi @storax,

Thanks for reporting this.

I can reproduce this problem easily by adding `QApplication.exit()` at the end of `test_signal_blocker_exception` in `test_wait_signal`, causing subsequent tests to fail. I of course agree that actions done in a test should not affect others.

The reason seems that `QEventLoop.exec()`, which is used by `waitSignal`, returns `-1` instead of `0` in this situation. 

I will have to investigate this further to see how to work around it.

Cheers! :beers:

**Comment by jdreaver** [comment]
I have two ideas off of the top of my head:
* Make `qtbot` a fixture with `scope='function'`. Every time it is called, check if the current `QApplication.instance()` is alive. If not, then create a new one. The key here is that `QApplication.instance()` doesn't create a new application, so I think the overhead will be quite low. Unfortunately, this might break backwards compatibility with derived test fixtures that expect a session-scoped test.
* Alternatively, we could subscribe to the `QApplication.aboutToQuit` signal with an auxiliary function that will recreate an application once the test is over. Unfortunately, I think any version of this would require function-level fixtures as well.


If I have better ideas, I'll post them. I am pretty busy this weekend though.

**Comment by nicoddemus** [comment]
Thanks for chipping in @jdreaver.

I thought about this, but it seems `exit()` doesn't actually kill the `QApplication` global object, and trying to create a new `QApplication` after one has already been created raises an error, regardless if `exit()` was called or not. :disappointed: 

```
>>> from PySide.QtGui import QApplication
>>> QApplication.instance()
>>> print QApplication.instance()
None
>>> QApplication([])
>>> print QApplication.instance()
<PySide.QtGui.QApplication object at 0x03D35878>
>>> QApplication.instance().exit()
>>> print QApplication.instance()
<PySide.QtGui.QApplication object at 0x03D35878>
>>> QApplication([])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: A QApplication instance already exists.
```

I try come up with another solution on how to *ressurrect* the `QApplication` object after `exit()` has been called, although I don't discard the possibility that it might not be possible after all.

@storax, out of curiosity, what was the workaround you applied in your test suite?

**Comment by The-Compiler** [comment]
I don't think there's any good solution to reuse or resurrect a `QApplication`.

Another solution I could think of is to subclass `QApplication`, there override `quit`/`exit`, and simulate the original behaviour as close as possible (e.g. emit `aboutToQuit`), but don't actually quit.

...but that might cause more problems than it's worth.

**Comment by nicoddemus** [comment]
Thinks for chipping in @The-Compiler  :smile:

If we follow that route, we could `monkeypatch` the function `exit()` then, using a new fixture for that, `patch_qapp_exit` perhaps, or an ini configuration option.

But first I would like to hear about @storax's use case and if that would suffice it.

**Comment by storax** [comment]
I looked at the C++ source and this could be helpful:
```
void QCoreApplication::exit(int returnCode)
{
    if (!self)
        return;
    QThreadData *data = self->d_func()->threadData;
    data->quitNow = true;
    for (int i = 0; i < data->eventLoops.size(); ++i) {
        QEventLoop *eventLoop = data->eventLoops.at(i);
        eventLoop->exit(returnCode);
    }
}
```
A wild guess: it is exiting all event loops, also the ones of the SignalBlockers. I still don't get, why subsequent eventloops fail. But my point is, that monkeypatching exit might be a bad idea, if somebody really expects their own eventloops to exit.

About my usecase and workaround:
I have an application that has a simple quit action in the contextmenu of a system tray. Because launching the application calls QApplication.exec_(), quiting should also quit the QApplication.
I guess there are far more (better) usecases. Especially when you run multiple event loops, and need certain teardown on exit and want to test against that.

To be able to test, i just made my application not call exec_ and quit for tests. This is not optimal, but i can continue testing for now.

**Comment by nicoddemus** [comment]
Thanks @storax,

Monkeypatching automatically does indeed seems dangerous. For your use case specifically, you could monkeypatch `exit` in your test and make sure it is being called as you expect, if you want to avoid touching the original code. 

All in all, I'm afraid there's not much that can done from pytest-qt's side to work around this issue, other than mentioning this in the documentation... any more thoughts?

**Comment by storax** [comment]
After looking at the c++ source for some time, there might be a way, but it will take me some testing to find out. I guess for now, mentioning it in the documentation is the best way.

I will just post here, what i found out so far. If I get some time, i'll try and make some tests:

1. `QCoreApplication.exit` will set `QThreadData.quitNow` to `True`. Only `exec()` will set it back to `False` again.
2. `QEventLoop.exec` starts out like this:
```
int QEventLoop::exec(ProcessEventsFlags flags)
{
    Q_D(QEventLoop);
    if (d->threadData->quitNow)
        return -1;
...
...
```
3. As you you can see, as long as `QThreadData.quitNow` is true, `QEventLoops` will return `-1`. I guess that is the real reason, why subsequent calls fail, because the `QEventLoop` of `SignalBlocker` will not execute properly.
4. I'm not sure what the best approach would be to workaround this. If anybody has some clever thoughts, let me now. The problem is, that it's hard to estimate any side effects.

**Comment by nicoddemus** [comment]
Hi @storax,

Thanks for researching this!

I think the safest approach is to mention this in the docs, and propose a common workaround in this case, like monkeypatching `QApplication.exit()`.

**Comment by storax** [comment]
Yes, I agree. I haven't found a workaround yet. Thanks for the help. I really enjoy working with pytest-qt!

**Comment by jbrezmorf** [comment]
I encountered same or similar problem, running many tests using python-qt, each test as its own QApplication. I tried monkeypatch QApplication.exit, but still didn't solve the problem as the QApplication is 
created in tested code in several tests. 

However it seems, that I can create new QApplication for every test, call QApplication.exit, and explicitely delete the application object. This way I have now problems.

**Comment by nicoddemus** [comment]
Hi @jbrezmorf 

> However it seems, that I can create new QApplication for every test, call QApplication.exit, and explicitely delete the application object. This way I have no problems.

Hmm interesting, how did you manage to delete the `QApplication` object from Python?

**Comment by jbrezmorf** [comment]
Single test  goes like:

    app = QApplication()
    ... setup
    app.exec()
    ... function triggered by a QTimer and ended by app.quit()
    del app

Nevertheless after further testing I realize:
- this Issue is pytest-qt related which use just single instance of QApplication, I tried to solve the problem  out of pytest-qt
- What works for 2-3 tests didn't work when more tests are executed in one pytest call. I observe freeze or seg fault depending on presence of tests in no meaningful way. I'm turning back to pytest-qt approach with single QApplication instance although it can have issues with encapsulating individual tests. 
Another drawback is that some classes to test create QApplication instance on its own so I have to fix all these and test existence of the instance (through QCoreApplication.instance()).
Is there a simple way to get unique QApplication instance?

**Comment by altendky** [comment]
`del` doesn't actually guarantee deletion of anything except the variable and the corresponding reference to the object.  Even Python objects can live on after `del`'ing even the last variable that refers to them.  I'm not optimistic, but perhaps [`deleteLater()`](http://doc.qt.io/qt-5/qobject.html#deleteLater) might work?  Seems unlikely though since I would expect the event loop to get shutdown  before we'd want the `QApplication` to actually get deleted.  Maybe [`QTest`](http://doc.qt.io/qt-5/qtest-overview.html) could shed some light on how to test application termination?

I had an issue with my process not terminating and I just subprocessed it with some hooks to trigger the action I wanted so I could have a test for that.

@jbrezmorf, are you concerned about testing the details of the application actually terminating or could you just have a signal to quit that your application connects to `app.quit()` but your tests just `qtbot.waitSignal()` for?  (Sorry if this is obvious and already considered)

**Comment by The-Compiler** [comment]
I think even Qt itself [doesn't support recreating QApplication](https://doc.qt.io/qt-5/qapplication.html#details):

> For any GUI application using Qt, there is precisely one QApplication object

So if this works, it's probably more luck than anything else.

**Comment by jbrezmorf** [comment]
@altendky Running in subprocess although obvious was not considered yet. Thanks.
@The-Compiler, you are right, recreation works by luck if the number of tests is small.

**Comment by altendky** [comment]
@jbrezmorf, if you are testing for issues getting your process to terminate like I was then I'd think a subprocess would be the only way to properly recreate the scenario.  If you just want to make sure that your function tries to quit I would make that code more testable with an intermediate signal you can wait for. Then you don't have to provide cli access to everything you would want to control for the test.

**Comment by adam-grant-hendry** [comment]
> Thanks for chipping in @jdreaver.
> 
> I thought about this, but it seems `exit()` doesn't actually kill the `QApplication` global object, and trying to create a new `QApplication` after one has already been created raises an error, regardless if `exit()` was called or not. 😞
> 
> ```
> >>> from PySide.QtGui import QApplication
> >>> QApplication.instance()
> >>> print QApplication.instance()
> None
> >>> QApplication([])
> >>> print QApplication.instance()
> <PySide.QtGui.QApplication object at 0x03D35878>
> >>> QApplication.instance().exit()
> >>> print QApplication.instance()
> <PySide.QtGui.QApplication object at 0x03D35878>
> >>> QApplication([])
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> RuntimeError: A QApplication instance already exists.
> ```
> 
> I try come up with another solution on how to _ressurrect_ the `QApplication` object after `exit()` has been called, although I don't discard the possibility that it might not be possible after all.
> 
> @storax, out of curiosity, what was the workaround you applied in your test suite?

I think you're forgetting that in CPython, the last expression in the REPL is stored in the underscore variable, so you haven't garbage collected yet, which is why you're getting therror. To do so, you need to evaluate another expression:

```python
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from qtpy.QtWidgets import QApplication
>>> QApplication.instance()
>>> print(QApplication.instance())
None
>>> QApplication([])
<PyQt5.QtWidgets.QApplication object at 0x000002EBBD7014C0>
>>> print(QApplication.instance())
<PyQt5.QtWidgets.QApplication object at 0x000002EBBD7014C0>
>>> QApplication.instance().exit()
>>> 1
1   
>>> print(QApplication.instance())
None
>>> QApplication([])
<PyQt5.QtWidgets.QApplication object at 0x000002EBBD7014C0>
>>> 
```
