### ISSUE TITLE
Incompatible with pyside 5.11 (shiboken2 missing)

### ISSUE THREAD

**Issue by tlambert03** [pytest-dev/pytest-qt#373]
it looks like the pyside 5.11 (at least the one distributed on pypi) is lacking shiboken2, and a simple test errors after #340:

```sh
conda create -n test python
conda activate test
pip install pytest pytest-qt pyside2==5.11
pytest test_example.py
```

where `test_example.py` is:

```python
def test_something(qtbot):
    pass
```

```pytb
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/talley/miniconda3/envs/test/lib/python3.9/site-packages/_pytest/main.py", line 265, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/Users/talley/miniconda3/envs/test/lib/python3.9/site-packages/_pytest/config/__init__.py", line 982, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/Users/talley/miniconda3/envs/test/lib/python3.9/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/talley/miniconda3/envs/test/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/talley/miniconda3/envs/test/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Users/talley/miniconda3/envs/test/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/talley/miniconda3/envs/test/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/talley/miniconda3/envs/test/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/talley/miniconda3/envs/test/lib/python3.9/site-packages/pytestqt/plugin.py", line 203, in pytest_configure
INTERNALERROR>     qt_api.set_qt_api(config.getini("qt_api"))
INTERNALERROR>   File "/Users/talley/miniconda3/envs/test/lib/python3.9/site-packages/pytestqt/qt_compat.py", line 135, in set_qt_api
INTERNALERROR>     import shiboken2
INTERNALERROR> ModuleNotFoundError: No module named 'shiboken2'
```

from the looks of https://github.com/pytest-dev/pytest-qt/pull/340#issuecomment-805339916,  pyside 5.11 should still be supported after #340?

**Comment by nicoddemus** [comment]
I guess `shiboken2` just needs to be installed separately then?

**Comment by tlambert03** [comment]
yes, installing shiboken2 manually certainly fixes it... which is what I'm doing for those test cases, but from a user perspective, that's a bit of a change... (i.e. my CI was working, and then it wasn't after updating pytest-qt...).  Just thought you'd like to know, since it really comes down to a [one line change](https://github.com/pytest-dev/pytest-qt/pull/340/files#diff-04278337b26277c6d10e922eba6f555e9883405df1485c40ead631156499d7b3R162) to recover compatibility with 5.11:

```python
try:
    import shiboken2

    self.isdeleted = lambda obj: not shiboken2.isValid(obj)
except ImportError:
    # just an example... not sure what fallback behavior you'd rather have
    self.isdeleted = lambda obj: False
```

**Comment by nicoddemus** [comment]
> Just thought you'd like to know, since it really comes down to a one line change to recover compatibility with 5.11:

Not really, that certainly will cause problems... unfortunately there's no fallback really, we need to ask the underlying runtime if the object has been deleted before accessing it in some cases.

**Comment by nicoddemus** [comment]
> which is what I'm doing for those test cases, but from a user perspective, that's a bit of a change... (i.e. my CI was working, and then it wasn't after updating pytest-qt...

I see, not sure what has changed on pytest-qt side regarding `shiboken2`... @The-Compiler might be able to shime in here.

**Comment by nicoddemus** [comment]
Another idea just occurred to me too, we could have extras, which would then install any extra dependencies required:

```shell
$ pip install pytest-qt[pyside2]
```

**Comment by tlambert03** [comment]
> I see, not sure what has changed on pytest-qt side regarding shiboken2... @The-Compiler might be able to shime in here.

what changed was the explicit import of shiboken2 in #340 on [these two lines](https://github.com/pytest-dev/pytest-qt/pull/340/files#diff-04278337b26277c6d10e922eba6f555e9883405df1485c40ead631156499d7b3R161-R162)

**Comment by The-Compiler** [comment]
Yep, we [had a test](https://github.com/pytest-dev/pytest-qt/pull/340/files#diff-330ca2f78658e78c1c74495f01973cb0d56fa301535a48d99990ff9a79b9579f) which was marked as PyQt5 only (due to needing `sip.isdeleted`), but the test actually worked for all Qt APIs, so that's why I added `isdeleted` to `qt_compat`.

I wasn't aware about the situation with `shiboken2` and PySide2 5.11 - since we only need it for the test and there are other ways to check what this test needs to check, let's get rid of it - see #374.

**Comment by tlambert03** [comment]
thanks!
