### ISSUE TITLE
--strict-markers requires pytest >= 4.5.0

### ISSUE THREAD

**Issue by bnavigator** [pytest-dev/pytest-qt#376]
#339 introduced `--strict-markers` and `--strict-config` into setup.cfg. This raises the minimum pytest requirement to [4.5.0](https://docs.pytest.org/en/stable/changelog.html#pytest-4-5-0-2019-05-11)

**Comment by The-Compiler** [comment]
Only when running pytest-qt's own tests, though. As a plugin for other testsuites, I believe 3.0.0+ should still be correct.
