### ISSUE TITLE
Allow PyQt5 versions < 5.11

### ISSUE THREAD

**Issue by cafhach** [pytest-dev/pytest-qt#400]
Thank you for your amazing work. I'm currently using a modified version of `pytest-qt` which allows usage with `PyQt 5.9.2`
So far I haven't had any issues. Where does the restriction for `5.11` come from? Is it arbitrary because you didn't test any lower version number with your package or is there an actual known problem with lower version numbers?

If it is arbitrary, I would like to help getting 5.9 "greenlighted".

**Comment by nicoddemus** [comment]
Hi @cafhach,

I can trace that restriction to https://github.com/pytest-dev/pytest-qt/pull/340:

> Note that with the scoped enum access, we're dropping support for PyQt5 < 5.11. 

@The-Compiler can probably fill in the details.

**Comment by The-Compiler** [comment]
There are various reasons:

- How to import the `sip` module changed
- The associated sip version introduced support for scoped enums, which would require various changes to support - I suppose you were running an older PyQt but using a newer sip or something (which is rather exotic)?
- PyQt 5.11 isn't installable from PyPI anymore, so we can't really easily run automated tests for it - IMHO, supporting a version without CI is a no-no
- Qt 5.9 was released in May 2017 and support ended in May 2020. I'm really not too keen in continuing to support an ancient Qt version 1.5 years beyond its official end of support.

**Comment by cafhach** [comment]
Thanks for you replies! The reason why we use such an archaiv PyQt version is that Anaconda does not provide any higher version number at the moment. The installed sip has version 4.19.8 

Thus I understand that support for 5.9 is not an option for you. Would you consider to officially allow users to bypass the version number check e.g. by an additional entry in `pytest.ini` (`disable_qt_version_check = true`) ? If so I could try to provide a PR for that.

**Comment by nicoddemus** [comment]
@cafhach this kind of option creates some churn which we probably want to avoid. Isn't using a previous pytest-qt version (which supports PyQt 5.9) an option for you?

**Comment by cafhach** [comment]
Hadn't thought about this option. I will try it out. :-)

**Comment by nicoddemus** [comment]
Cool, thanks. You will need to use `pytest-qt<4`, since `4.0.0` introduced the breaking changes for PyQt 5.9. 👍
