### ISSUE TITLE
Qt testing via QML based app

### ISSUE THREAD

**Issue by dmatos2012** [pytest-dev/pytest-qt#415]
Hello,
First of all, first for the amazing plugin, and the work towards this project. 
Following up on issue #251, I am trying to get my QML based app working with this plugin. Lets say you have a simple `main.qml` being
```
import QtQuick 2.15
import QtQuick.Window 2.2
import QtQuick.Controls 2.15
Window {
    width: 100
    height: 100
    title: "hello"
    Button {
        width: 600
        height: 600
        text: "mybtn"
        objectName: "btn"
    }
} , 
```
I launch this via python with
```python
app = QGuiApplication([])
engine = QQmlApplicationEngine()
engine.load(QUrl.fromLocalFile("main.qml"))
app.exec_()
```
However, as mentioned on the issue #251, via the `QQmlApplicationEngine` its only possible to grab a `QWindow` via `engine.rootObjects()[0]`, but not a **widget**, so its not possible to perform `qtbot.add_widget()`. 

If I try to test this via, 
```python
import pytest
@pytest.fixture()
def window(qtbot):
    engine = QQmlApplicationEngine()
    engine.load(QUrl("main.qml"))
    window = engine.rootObjects()[0]  # this gives a QWindow object
    # qtbot.add_widget(window)  # this fails due not being QWidget
    # window.show()
    yield window

def test_window_title(window):
    assert window.title() == "hello"
```
this test will pass, but probably by commenting out `add_widget` I will most likely stumble upon other issues If I persist. However if I try loading my QML via `QQuickWidget` as such:
```python
view = QQuickWidget()
view.setSource(QUrl.fromLocalFile("main.qml"))
```
then I can do `qbot.add_widget(view)`, but I get a warning 
```
QtWarningMsg: QQuickWidget does not support using windows as a root item. 

If you wish to create your root window from QML, consider using QQmlApplicationEngine instead. `
```
In that case, I would have to create the root window via python, and my `main.qml` only include the `Button {}`

My main questions are: 
* Is it possible to somehow use all of the functionality on this `pytest-qt` plugin while having a QML based app, via some ":hacks" or, is it ok to just try and test it without the `qbot.add_widget(QWidget)` even tho it says its highly recommended.
* If not possible which atm I think its not, could anyone perhaps guide me into supporting that here, or tell me other ways in which I can test then my python Slots, Signals etc. 

In my use case, I use python for all backend and only QML for the frontend. Please let me know if this is in the wrong repo to ask, or if someone with way more experience has already solved this, or has any other suggestions :)

OS : Ubuntu 20.04
Qt: PySide2 5.15.2

Oh , and also the workaround on issue #251 , doesnt work for me as it says `qt_api` as `AttributeError: '_QtApi' object has no attribute 'QApplication'` .

Thanks!

**Comment by nicoddemus** [comment]
Hi @dmatos2012,

I have never used `QML`, but I can answer your question regarding `add_widget`:

>  is it ok to just try and test it without the qbot.add_widget(QWidget) even tho it says its highly recommended.

It is OK. `add_widget` just adds the widget to an internal list and ensures it gets closed by the end of the test, nothing more. If you have your own mechanism to close the qml widgets at the end of the test (say via a fixture), then you are good to go. All other `pytest-qt` features always receive an explicit `QWidget` object if needed, and have no connection with the widget given to `add_widget`.

Hope this helps!

**Comment by dmatos2012** [comment]
Hi, 

Thanks for the quick response, and for the suggestion.I will try and if I succeed maybe perhaps post here for future readers. Feel free to close if you think its no longer relevant! :)

**Comment by nicoddemus** [comment]
Closing then, also consider contributing to the docs if you discover something interesting! 😁
