### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by nrbnlulu** [pytest-dev/pytest-qt#424]
tried to open pull request but got permission denied..
![image](https://user-images.githubusercontent.com/88795475/170434838-61d19603-3dae-4055-8b91-f18ed16aa5bc.png)

pyqt6 is duplicated

**Comment by nicoddemus** [comment]
Thanks for the report @nrbnlulu! 

> tried to open pull request but got permission denied..

This usual way to do this is to open a PR in your own fork. 👍 

I fixed this already, thanks again!
