### ISSUE TITLE
Feature Request: Headless Testing on Windows

### ISSUE THREAD

**Issue by adam-grant-hendry** [pytest-dev/pytest-qt#425]
Please add support for headless testing on Windows. I know `pytest-xvfb` is available, but that only works on Linux. The other alternative is settings `QT_QPA_PLATFORM=offscreen`, but certain tests fail with this (e.g. testing `QToolTip` messages appear with `isVisible()` and the text output `text()`.

**Comment by The-Compiler** [comment]
This is out of scope for pytest-qt. All pytest-qt does is give you some utilities to work with Qt, but how those do or don't display windows is up to Qt and the environment around it, not this project.
