### ISSUE TITLE
4.1 release?

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#435]
The last release [was over a year ago](https://github.com/pytest-dev/pytest-qt/blob/master/CHANGELOG.rst) and we've gotten a few new features since then - @nicoddemus what do you think about releasing 4.1 now?

I was thinking about getting #422 in first, but I don't think I will get around to it in the next couple of weeks, so I think I'd prefer a release before that.

**Comment by The-Compiler** [comment]
4.1 [is out now](https://pypi.org/project/pytest-qt/) :tada:

**Comment by nicoddemus** [comment]
Woot! Many thanks for taking care of this one!
