### ISSUE TITLE
Help with "Okaying" a message box using pytest-qt. 

### ISSUE THREAD

**Issue by CiaranWelsh** [pytest-dev/pytest-qt#440]
Hello - I'd like to ask a question if you don't mind. Given a simple message box application such as : 

```
from PyQt5.QtWidgets import QMessageBox, QWidget


def messageBoxFactory(parent : QWidget, title:str, msg:str, level="info"):
    """Display a popup of type `level` containing msg[0] (title) and msg[1] the message.

    Makes use of the full QMessageBox (rather than QMessageBox.warning, for example) because
    it is necessary to have a handle to the box later for testing.
    """
    box = None
    if level == "info":
        box = QMessageBox(QMessageBox.Information, title, msg, QMessageBox.Ok, parent)
    elif level == "warning":
        box = QMessageBox(QMessageBox.Warning, title, msg, QMessageBox.Ok, parent)
    elif level == "critical":
        box = QMessageBox(QMessageBox.Critical, title, msg, QMessageBox.Ok, parent)

    if not box:
        raise ValueError("no QMessageBox created")
    box.exec()
    return box

```
how would one go about using pytest-qt's qbot to okay the popup? Here's my best try so far which does not work since the `QMessageBox` `exec` loop is running before `qtbot` can try to press anything.
```
from PyQt5.QtWidgets import QMainWindow, QDialogButtonBox
from PyQt5.QtCore import Qt
import pytest
from pytestqt.qtbot import QtBot
from accos.view.MessageBoxFactory import messageBoxFactory

def test_mbf(qtbot: QtBot):
    main_window = QMainWindow()
    box = messageBoxFactory(main_window, "Informational Message", "Some information", level="info")
    dialogButtonBox : QDialogButtonBox = box.children()[2]
    okayBtn = dialogButtonBox.buttons()[0]
    qtbot.mouseClick(okayBtn, Qt.LeftButton, Qt.NoModifier)
```

Thanks
Ciaran

**Comment by nicoddemus** [comment]
Hey,

Modal dialogs are often a pain to test, I suggest to mock (using `monkeypatch` or `pytest-mock`) the `exec()` function. This way the message box won't even popup, and you can check in your test that `exec` has been called, something like:

```python
def test_mbf(qtbot: QtBot, mocker):
    main_window = QMainWindow()
    exec_mock = mocker.patch.object(QMessageBox, "exec")
    messageBoxFactory(main_window, "Informational Message", "Some information", level="info")
    assert exec_mock.call_count == 1 
```

**Comment by mazerab** [comment]
Hi, I have the same issue and must test that the QMessageBox can be clicked and closed to progress to the next step in my UI. Is there really no way to qtbot.mouseclick on a QMessageBox? I have many QMessageBox that get display to give instructions to the user and they must be closed to move to the next step in the UI. Thank you.

**Comment by nicoddemus** [comment]
See https://github.com/pytest-dev/pytest-qt/issues/440#issuecomment-1177820452.

I think it is possible to list all widgets, find the message box, find the button, and click on it, but TBH I don't think it is worth the trouble: just mock `exec()` like I commented.
