### ISSUE TITLE
[Feature Request] Please Support the qasync Library

### ISSUE THREAD

**Issue by teweitsai** [pytest-dev/pytest-qt#448]
It would be great that the `pytest-qt` can support the use of [qasync](https://github.com/CabbageDevelopment/qasync) library or something similar.

Sometimes, the developers may want to use the `async/await` syntax with the Python QT framework such as PySide2 or similar.

However, the `pytest-qt` could not work with the function such as the `qtbot.mouseClick()` because of the different event loops between the Qt framework and `asyncio` library (and this is the trick in the `qasync`) when the `@asyncSlot` is applied.

Thanks!

**Comment by nicoddemus** [comment]
Hi @teweitsai,

Thanks for writing!

pytest-qt mainly provides a fixture to help test Qt applications (`qtbot`), while `qasync` would demand a few more things to support it.

Probably it would be best for a separate plugin (which depends on `pytest-qt` and `qasync`) to provide the additional support.

Their own [test infrastructure](https://github.com/CabbageDevelopment/qasync/blob/master/tests) would probably be a good place to start.
