### ISSUE TITLE
Testing for Qt without pytest

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [pytest-dev/pytest-qt#449]
There is no mailinglist so I hope it is OK to ask here.

Do I assume it right that when pytest can use Qt then Pythons own `unittest` can this also?

Do you have any knowledge of projects using `unittest` for that? Searching for Qt projects is hard because most of them are C-like.

**Comment by nicoddemus** [comment]
Hi @Codeberg-AsGithubAlternative-buhtz, 

> Do I assume it right that when pytest can use Qt then Pythons own unittest can this also?

Not without some external library providing the necessary gears for that: the framework needs to at least initialize `QApplication`, and the standard `unittest` does not do that.

> Do you have any knowledge of projects using unittest for that? 

@fabioz and I published a framework based on the internal framework we had at @ESSS: [pyguiunit](https://sourceforge.net/projects/pyguiunit), however that project is unmaintained for *many and many years* and I probably does not work in modern Python + Qt versions.
