### ISSUE TITLE
QtWebEngine 6.5: Fatal Python error: Aborted / Argument list is empty, the program name is not passed to QCoreApplication. base::CommandLine cannot be properly initialized.

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#483]
With the upcoming QtWebEngine 6.5, a snippet like:

```python
from PyQt6.QtWidgets import QApplication
from PyQt6.QtWebEngineCore import QWebEngineProfile

app = QApplication([])
QWebEngineProfile()
```

fails with:

```
Argument list is empty, the program name is not passed to QCoreApplication. base::CommandLine cannot be properly initialized.
```

due to:

- [[QTBUG-110157] Incorrect command-line parsing if argc=0 - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-110157)
- [Improve error handling of argument parsing (Ibf14b11b) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/455347)
- [Yield fatal error for empty command-line arguments (If0144af8) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/457045)

Which, with pytest:

```python
import pytest

from PyQt6.QtWebEngineCore import QWebEngineProfile
from PyQt6.QtWebEngineWidgets import QWebEngineView

def test_qtwe(qapp):
    print(f"args: {qapp.arguments()}")
    QWebEngineProfile.defaultProfile()
```

just turns into:

```
test_qtwe.py Fatal Python error: Aborted
```

and a stacktrace, due to output capturing...

This is because we also default to empty args:

https://github.com/pytest-dev/pytest-qt/blob/f0dced8f7918d6a19353c2d99cc1e77fd948b6c0/src/pytestqt/plugin.py#L14-L28

As a workaround, this works:

```python
import sys
import pytest

from PyQt6.QtWebEngineCore import QWebEngineProfile
from PyQt6.QtWebEngineWidgets import QWebEngineView

@pytest.fixture(scope="session")
def qapp_args():
    return [sys.argv[0]]

def test_qtwe(qapp):
    print(f"args: {qapp.arguments()}")
    QWebEngineProfile.defaultProfile()
```

but I expect that many people run into this when Qt 6.5 comes out, [currently planned](https://wiki.qt.io/Qt_6.5_Release) for the 30th.

In addition to that, [our documentation](https://pytest-qt.readthedocs.io/en/latest/reference.html#pytestqt.plugin.qapp_args) is just wrong too. It suggests:

```python
@pytest.fixture(scope="session")
def qapp_args():
    return ["--arg"]
```

but that would mean that `--arg` is now `sys.argv[0]` (the script name), which makes no sense at all...

---

So how do we fix this? One proposal would be to always prepend `sys.argv[0]` to the given `qapp_args`. This would mean that the example is now correct, and existing testsuites would continue working with QtWebEngine 6.5 with no further changes required.

However, it's a backwards-**in**compatible change, and if someone already accounts for this in a `qapp_args`, the `argv[0]` would now be passed *twice*...

A [cursory GitHub search](https://github.com/search?q=%22def+qapp_args%22+-path%3Asrc%2Fpytestqt%2Fplugin.py+-path%3Apytestqt%2Fplugin.py+-path%3Atests%2Ftest_basics.py&type=code) reveals that projects already do this (lots of qutebrowser forks there :laughing:):

- [eddy/conftest.py at 2b257070ca15d63e31c8f53f0c538cbcddee3e7a · obdasystems/eddy](https://github.com/obdasystems/eddy/blob/2b257070ca15d63e31c8f53f0c538cbcddee3e7a/tests/conftest.py#L72)
- [COUNTER-5-Report-Tool/test_ImportFile.py at 5d70a8a8483cb0e1718fb22dbe025437d5076695 · CS-4820-Library-Project/COUNTER-5-Report-Tool](https://github.com/CS-4820-Library-Project/COUNTER-5-Report-Tool/blob/5d70a8a8483cb0e1718fb22dbe025437d5076695/tests/test_ImportFile.py#L18)

The second option would be to fix our doc examples, *and* fix the default `qapp_args` to `return [sys.argv[0]]` instead. This is technically still a backwards-incompatible change, but also clearly a bugfix for something we are doing wrong and never noticed... However, it means that projects with a custom `qapp_args` (I could only find qutebrowser) will need to adjust.

---

@nicoddemus what do you think? Do you have the capacity to fix this and cut a new release in the coming few days? Happy to do reviews and test with Qt 6.5 locally, but I'm a bit busy giving a company training between the 20th and 30th... and by the time I'm back, Qt 6.5 will already be released most likely.

**Comment by nicoddemus** [comment]
>The second option would be to fix our doc examples, and fix the default qapp_args to return [sys.argv[0]] instead. This is technically still a backwards-incompatible change, but also clearly a bugfix for something we are doing wrong and never noticed...

I prefer this, as this will fix a problem we did not notice, and also provide users with the ability to provide the full args to `QApplication`, which would not be possible in the first proposal.

> @nicoddemus what do you think? Do you have the capacity to fix this and cut a new release in the coming few days? 

I'm pretty busy this weekend myself, but I will try to get to this on Sunday.

**Comment by hakonhagland** [comment]
> However, it's a backwards-compatible change, and if someone already accounts for this in a qapp_args, the argv[0] would now be passed twice...

@The-Compiler Did you mean "incompatible" (not compatible as written)? Anyway, I didn't quite understand why it would be passed twice? If someone overrides the `qapp_args` fixture the default will not apply, or am I missing something?

**Comment by The-Compiler** [comment]
I did indeed mean "incompatible", I edited the post above.

If someone currently has:

```python
@pytest.fixture(scope="session")
def qapp_args():
    return [sys.argv[0], ...]
```

to already account for this behavior, and we do:

```python
 _qapp_instance = qapp_cls([sys.argv[0]] + qapp_args)
```

here:

https://github.com/pytest-dev/pytest-qt/blob/da33817f6f70cf3440cc1e3155c814136bd68dcd/src/pytestqt/plugin.py#L66

then the arguments passed to QApplication would be `[sys.argv[0], sys.argv[0], ...]`.

**Comment by hakonhagland** [comment]
> _qapp_instance = qapp_cls([sys.argv[0]] + qapp_args)

I am not sure I understand why we append `qapp_args` here?  Why not just use code as it is now `qapp_cls(qapp_args)`, and instead redefine `qapp_args` like proposed in https://github.com/pytest-dev/pytest-qt/pull/515 ?

**Comment by The-Compiler** [comment]
That's what my second proposal above was. You quoted from the first one.

**Comment by Sargeanthost** [comment]
Sorry if this isn't the right place/this hasn't been applied to PyQt6.6.1 yet, but this issues still happens. I can pass `sys.argv[0]` or another string in the arguments to get the script to work, but I'm not sure that's intended.
