### ISSUE TITLE
Building docs via tox fails

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#49]
From `docs/conf.py`:

```python
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'
if on_rtd:
    html_theme = 'default'
else:
    #html_theme = 'agogo'
    html_theme = 'sphinxdoc'
    # [...]
```

from `tox.ini`:

```ini
[testenv:docs]
# ...
setenv=
    READTHEDOCS=True
```

This fails when trying to build the docs locally, as it uses the `default` theme:

```
Warning, treated as error:
WARNING: 'default' html theme has been renamed to 'classic'. Please change your html_theme setting either to the new 'alabaster' default theme, or to 'classic' to keep using the old default.

ERROR: InvocationError: '/home/florian/proj/pytest-qt/.tox/docs/bin/sphinx-build -q -E -W -b html . _build'
```

I'm not sure what the best way to solve this is, as I assume `default` is valid on readthedocs and `READTHEDOCS` needs to be set so the shims are used so no Qt-backend is needed.

**Comment by The-Compiler** [comment]
After I forced the theme to `sphinxdoc`, I get this:

```
Warning, treated as error:
/home/florian/proj/pytest-qt/docs/index.rst:234: WARNING: autodoc: failed to import class 'QtBot' from module 'pytestqt.plugin'; the following exception was raised:
Traceback (most recent call last):
  File "/home/florian/proj/pytest-qt/.tox/docs/lib/python3.4/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/florian/proj/pytest-qt/pytestqt/plugin.py", line 57, in <module>
    class QtBot(object):
  File "/home/florian/proj/pytest-qt/pytestqt/plugin.py", line 49, in _inject_qtest_methods
    method = create_qtest_proxy_method(method_name)
  File "/home/florian/proj/pytest-qt/pytestqt/plugin.py", line 26, in create_qtest_proxy_method
    functools.update_wrapper(result, qtest_method)
  File "/home/florian/proj/pytest-qt/.tox/docs/lib/python3.4/functools.py", line 64, in update_wrapper
    setattr(wrapper, attr, value)
TypeError: __qualname__ must be set to a string object

ERROR: InvocationError: '/home/florian/proj/pytest-qt/.tox/docs/bin/sphinx-build -q -E -W -b html . _build'
```

**Comment by nicoddemus** [comment]
Hmmm weird. I will take a look, thanks!

**Comment by nicoddemus** [comment]
An old local virtual environment was the reason I didn't notice it before. :smile: Thanks!

**Comment by The-Compiler** [comment]
I still get the `TypeError` in the comment though.

**Comment by nicoddemus** [comment]
Hmm, I forgot to mention I ran that in Python 2.7... are you using 3.4?

Weird is that the error happens in `functools`... perhaps that name is not a `string`, but `bytes`?

**Comment by The-Compiler** [comment]
It worked fine with `basepython = python2` in `tox.ini` indeed - I'm on Arch Linux which uses Python 3 for `/usr/bin/python`.

I was confused why that error shows up when building docs only but not with real usage, and then remembered the `Mock` used so no Qt backend is needed for building the docs. Then I found out this didn't handle `__qualname__` (and `__annotations__`) and added support for that in #50 - after that, docs seem to build fine here.

**Comment by nicoddemus** [comment]
Excellent, thanks! :smile:
