### ISSUE TITLE
Pytest seg faults at process_events when I run all my pytests

### ISSUE THREAD

**Issue by sudilav** [pytest-dev/pytest-qt#496]
Hi,

I've been wracking my brain on this. The pytest framework seems unstable and undebuggable so I'm hoping you guys can help us understand what is going on here.

If I run a subset of my pytests then everything works fine, but once I either exceed a certain amount of if I just run:

```
python -m pytest
```

Then down the line (both on windows and in a linux docker) it exits with a seg fault at the exact same place everytime:

![image](https://github.com/pytest-dev/pytest-qt/assets/85935040/b68d01ae-1d9b-43dd-8aae-f78cccc1bb82)

But if I run a subset, let's say that same subset where it seg faulted:

![image](https://github.com/pytest-dev/pytest-qt/assets/85935040/790f49a6-a157-43b3-9c3f-086aefc51210)

The problem is, how do you debug something like this? If it seg faults there's no way to get in and see, I've tried using multiple faulthandler commands as has been suggested but they also seem unhelpful.

Can an expert help me debug what is going on here?

My application typically hits about the 150MB range when it's running these pytests which for my laptop, is nothing. It also seg faults at the same place on our gitlab pipeline. It's quite strange and after a week of trying multiple routes, even strace to still know diddly squat I am out of ideas.

**Comment by nicoddemus** [comment]
Hi,

> The pytest framework seems unstable and undebuggable so I'm hoping you guys can help us understand what is going on here.

To be clear, this is being caused by the code under test, not by pytest itself. Also, in general, I suggest in the future to avoid asking help from OSS maintainers (which work for free) starting with "the framework is unstable and undebuggable".

> The problem is, how do you debug something like this? If it seg faults there's no way to get in and see, I've tried using multiple faulthandler commands as has been suggested but they also seem unhelpful.

This is hard to track, I suggest using https://github.com/asottile/detect-test-pollution to at least pinpoint the tests which trigger the problem. From there, I would start to comment-out code until the problem goes away, to find the code that causes the crash.

Hope this helps!

**Comment by sudilav** [comment]
Not really:

![image](https://github.com/pytest-dev/pytest-qt/assets/85935040/068e0bb3-49a8-4ee7-a090-cb7dd1f2d70e)

How can I actually get into some form of debugging environment where I can get a stack trace with further details or anything with more details? If this was C++ I'd use gdb. That is what I mean by undebuggable, there doesn't seem to be a tool to do that kind of stuff.

**Comment by sudilav** [comment]
I've tried this, suspecting it to be a bad clean up and if so, it would avoid calling the ProcessEvents after a pytest, during clean up but no effect:

```
@pytest.fixture(autouse=True, scope="session")
def teardown(qapp):
    yield
    qapp = None
```

**Comment by nicoddemus** [comment]
> How can I actually get into some form of debugging environment where I can get a stack trace with further details or anything with more details? If this was C++ I'd use gdb. That is what I mean by undebuggable, there doesn't seem to be a tool to do that kind of stuff.

Indeed this is a problem with Python in general, because we are getting a crash on the C runtime, and Python just crashes too.

**Comment by sudilav** [comment]
Well I've just managed to get this far so far:

![image](https://github.com/pytest-dev/pytest-qt/assets/85935040/2c71a123-0a63-4dac-b015-e348127fb776)

I suspect the fault handler triggering an abort at seg fault is forwarding the core dump to abrt, how can I disable the fault handler from this method of invocation?

**Comment by nicoddemus** [comment]
You can disable the fault handler in pytest by passing `-p no:faulthandler`.

**Comment by sudilav** [comment]
Please observe the execution here. I'm in python shell so I did pytest.main() as it seems the only way to get into a gdb session is:
```
gdb $(python)
```
Which results in a shell, hence I follow with:
```
import pytest
retcode = pytest.main()
```

I worked out I could do:

```
pytest.main(['-p','no:faulthandler'])
```

While you say its my code, why is the stack trace saying the fault occurs at plugin.py where it calls app.processEvents(), none of the stack trace includes any of my code.

**Comment by nicoddemus** [comment]
`app.processEvents()` executes C++/Qt code, which is then crashing... what that C++ code is doing is anyone's guess I'm afraid. 

It might also be a bug in Qt.

**Comment by sudilav** [comment]
That's what I'm suspecting. My application is plugin based so I just disabled all the plugins and I still get the issue, of course my tests fail but it still randomly segfaults.

We've had working pipelines before though and haven't changed our docker environment so versions are consistent.

Possibly my recent refactoring has resulted in us consuming alot more memory - how can I confirm if it's a memory issue?

**Comment by nicoddemus** [comment]
> how can I confirm if it's a memory issue?

I wouldn't know, sorry.

**Comment by sudilav** [comment]
I think I may have a theory being produced on this, based off of:

https://pytest-qt.readthedocs.io/en/latest/qapplication.html

It's one of the primary changes in my refactoring practice recently, I wanted to avoid tightly coupling modules in my plugins so I use signals to have them communicate without any interlocked dependency on each other. But using Qt Signals now seems too dangerous, instead I think I'll implement a callback based methodology. Hopefully that'll fix it or at least narrow this down....

**Comment by sudilav** [comment]
Going to close for now i guess

**Comment by The-Compiler** [comment]
In your screenshot, you're calling `gdb $(python)` - in other words, you're first running Python, then running gdb and passing the *output* of Python to gdb as arguments, which makes no sense at all. Also, your Python process runs outside gdb that way, and has long terminated by the time gdb starts...

You could do `gdb python` and then start pytest from there, which would work. However, you can instead just do `gdb --args python -m pytest` (and then `run` in the `gdb` shell); or to run immediately, `gdb -ex r --args python -m pytest`.

The fact that the Python interpreter is involved makes zero difference as to how debuggable things are - gdb doesn't care how the C++ code is called, it's still C++ code being called from C in the end. However, the [Python gdb integrations](https://devguide.python.org/advanced-tools/gdb/) can sometimes help, as this teaches gdb to print Python data structures nicely when showing them.

**Comment by sudilav** [comment]
@The-Compiler Thank you for a concise answer, unfortunately this methodology doesn't work when using pyenv as the python call there is to a bash script so gdb complains that it is not a binary.

Arriving into the office and I have begun migrating signals to callbacks. It appears to be now getting a tiny bit further:

![image](https://github.com/pytest-dev/pytest-qt/assets/85935040/196e14f3-7be3-438a-b2d6-86dc1f472ab4)

Therefore I'm going to continue this attack on changing to opt out of using signals wherever possible and banish their usage across the team.

We do however have one part I don't think we can remove signals from however that worked fine before my refactoring so I'm hoping that will not need to be changed, it is a Thread that uses signals to update the Qt Window's progress bar on it's progress.

I guess the future thought is avoid signals if you can, this might explain why https://gitlab.com/pavel.krupala/pyqt-node-editor which we are using also uses callbacks rather than signals.

**Comment by The-Compiler** [comment]
> unfortunately this methodology doesn't work when using pyenv as the python call there is to a bash script so gdb complains that it is not a binary.

So use the proper binary instead (probably something like `/root/.pyenv/versions/3.9.2/bin/python` or so?).

> Therefore I'm going to continue this attack on changing to opt out of using signals wherever possible and banish their usage across the team.

That seems... silly, to say the least. Signals are a core Qt feature, and you should probably just fix whatever mistake you made while refactoring.

> I guess the future thought is avoid signals if you can, this might explain why https://gitlab.com/pavel.krupala/pyqt-node-editor which we are using also uses callbacks rather than signals.

From what I can see in the code there, they're mostly just reinventing the wheel...
