### ISSUE TITLE
[BUG] raise TypeError("Need to pass a QWidget to addWidget!")

### ISSUE THREAD

**Issue by 17Reset** [pytest-dev/pytest-qt#507]
test setup failed
qtbot = <pytestqt.qtbot.QtBot object at 0x000002787998FF50>

    @pytest.fixture
    def window(qtbot):
        window = MainWindow()
        print(isinstance(window, qt_api.QtWidgets.QWidget))
>       qtbot.addWidget(window)

qt_api.QtWidgets.QWidget is a wrong type and is not a PyQt6 QWidget

**Comment by The-Compiler** [comment]
It's impossible to help with so little information. What is `MainWindow`? What's the full output and error message you get? Most likely this is a problem with your code and not the plugin.

**Comment by 17Reset** [comment]
> It's impossible to help with so little information. What is `MainWindow`? What's the full output and error message you get? Most likely this is a problem with your code and not the plugin.

Sorry, I've fixed the problem, it was me not specifying the version to the ini file.
