### ISSUE TITLE
How to use qapp_args() ?

### ISSUE THREAD

**Issue by hakonhagland** [pytest-dev/pytest-qt#513]
According to the [documentation](https://pytest-qt.readthedocs.io/en/latest/reference.html?highlight=qapp_args#pytestqt.plugin.qapp_args) : 

![image](https://github.com/pytest-dev/pytest-qt/assets/6708379/a0eb3d10-8f00-4622-ae3e-ca1de0098f33)

I tried to override this to fixture pass custom arguments like this:

```python
import sys
import pytest
from PyQt6.QtCore import QCommandLineParser
from PyQt6.QtWidgets import QApplication

def get_positional_args(app):
    app.setApplicationName("MyApp")
    app.setApplicationVersion("0.1")
    parser = QCommandLineParser()
    parser.addHelpOption()
    parser.addVersionOption()
    parser.addPositionalArgument("my_pos_arg1", "description of my_pos_arg1")
    parser.addPositionalArgument("my_pos_arg2", "description of my_pos_arg2")
    parser.process(app)
    arguments = parser.positionalArguments()
    return arguments

if __name__ == '__main__':
    app = QApplication(sys.argv)
    args = get_positional_args(app)
    print(args)

@pytest.fixture(scope="session")
def qapp_args():
    return ["a1", "a2"]

def test_pos_args(qapp: QApplication):
    app = qapp
    args = get_positional_args(app)
    assert args[0] == "a1"

```

But this fails to return the expected `["a1", "a2"]` from `get_positional_args()`, instead it returns `["a2"]`. What am I missing?

**Comment by The-Compiler** [comment]
The first argument (`sys.argv[0]`) is the application name. Our docs are a bit misleading here, this is already tracked as part of #483.

**Comment by hakonhagland** [comment]
> The first argument is the application name.

@The-Compiler Thanks for the help, I can confirm that it works as expected if I insert a program name as the first element of the array returned by `qapp_args()`.
