### ISSUE TITLE
Reports for unexpected qWarnings should show correct line number

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#55]
Currently, if I have a file like this:

```python
96 # [...]
97
98 def test_warning():
99    qWarning("hello world")
```

pytest-qt shows a warning on line 97 (which is empty):

```
_______________________________ test_warning ________________________________
tests/utils/test_qtutils.py:97: Failure: Qt messages with level WARNING or above emitted
--------------------------- Captured Qt messages ----------------------------
QtWarningMsg: hello world
```

At the very least, I think the line number should be the function where the issue actually occured.

However, on Qt5 (with `qInstallMessageHandler` support) it'd also be possible to report the exact location in the captured log message, which would be useful.

I might submit a PR for the latter somewhen this or next week, but if you have the time, feel free to do it :wink:

**Comment by nicoddemus** [comment]
Thanks! Strange that I failed to notice this... I will try to tackle this today. :smile:
