### ISSUE TITLE
_QtApi object has no attribute QtTest

### ISSUE THREAD

**Issue by slyin87** [pytest-dev/pytest-qt#560]
Hi,

I am using PySide6. I am not sure what I am doing. I want to do Model Test for my model. 
My code:

```
from pytestqt.modeltest import ModelTester

model = WorkNodeTreeModel()
qt_modeltester = ModelTester()
model_test = qt_modeltester.check(model)
```

Then I faced this error.
HAS_QT_TESTER = hasattr(qt_api.QtTest, "QAbstractItemModelTester")
AttributeError: '_QtApi' object has no attribute 'QtTest'

**Comment by nicoddemus** [comment]
Hi @slyin87,

pytest-qt is meant to be when writing tests, not for normal production code.

Try using it in a test:

```pytest
def test(qtmodeltester):
    model = WorkNodeTreeModel()
    qt_modeltester.check(model)
```

Of course, you will need `pytest` and `pytest-qt` installed.

Closing for now, feel free to follow up with more questions.
