### ISSUE TITLE
Selecting pyqt version in individual test, as opposed to for the whole test suite.

### ISSUE THREAD

**Issue by ahobeost** [pytest-dev/pytest-qt#577]
As part of a very large project, we would like to incrementally move from pyqt5 to pyqt6.
[The solution for backwards compatibility](https://www.pythonguis.com/faq/pyqt5-vs-pyqt6/) allows this to work, just not for testing it seems).

The following two tests demonstrate what I would like to achieve and show a known issue (#437).
The issue here, is that qtbot produces a specific Qapplication (either version 5 or version 6).

```
class TestMessageBox:
    def testCreate(self, qtbot):
        print("I am before message box")

        from PyQt5 import QtWidgets as _qtw
        qtbot.addWidget(_qtw.QMessageBox())
        print("I am after message box")
        assert False

    def testCreatePyQt6(self, qtbot):
        print("I am before message box")
        from PyQt6 import QtWidgets as _qtw

        qtbot.addWidget(_qtw.QMessageBox())
        print("I am after message box")
        assert False
```

One of these (or both) will fail, depending on which api is set in the pytest.ini file:
`qt_api=pyqt5`

The other will fail with the following error code:
`Process finished with exit code -1073740791 (0xC0000409)`

It would be great if qtbot would provide a Qapplication tailored to the desired version, for example.
`qt.bot.set_version('pyqt5')`

And then the tests would be:
```
class TestMessageBox:
    def testCreate(self, qtbot):
        print("I am before message box")

        from PyQt5 import QtWidgets as _qtw
        qt.bot.set_version('pyqt5')

        qtbot.addWidget(_qtw.QMessageBox())
        print("I am after message box")
        assert False

    def testCreatePyQt6(self, qtbot):
        print("I am before message box")

        from PyQt6 import QtWidgets as _qtw
        
        qt.bot.set_version('pyqt5')
        qtbot.addWidget(_qtw.QMessageBox())
        print("I am after message box")
        assert False
```

The following workaround also exists, [which is not compatible with qtbot](https://pytest-qt.readthedocs.io/en/latest/qapplication.html):
```
def testCreatePyQt6(self, qtbot):
        print("I am before message box")

        from PyQt6 import QtWidgets as _qtw
        
        app = _qtw.QApplication([])
        qtbot.addWidget(_qtw.QMessageBox())
        print("I am after message box")
        assert False
```

**Naive implementation:**
```
class Qtbot:
    def set_version(self, api: str):
        from pytestqt.qt_compat import qt_api
        qt_api.set_qt_api(api)
```

**Comment by nicoddemus** [comment]
Hi @ahobeost,

I don't think it is possible to provide different `QApplication` instances in the same process, it acts as a singleton, and errors out if you try to create a second `QApplication`.

In your case I suggest to mark the tests differently (say `qt5` and `qt6`), and then execute them in separate `pytest` sessions:

```
pytest -m qt5 ...
pytest -m qt6 ...
```

This seems reasonable and safer than trying to use both PyQt versions in the same process.

**Comment by ahobeost** [comment]
> Hi @ahobeost,
> 
> I don't think it is possible to provide different `QApplication` instances in the same process, it acts as a singleton, and errors out if you try to create a second `QApplication`.
> 
> In your case I suggest to mark the tests differently (say `qt5` and `qt6`), and then execute them in separate `pytest` sessions:
> 
> ```
> pytest -m qt5 ...
> pytest -m qt6 ...
> ```
> 
> This seems reasonable and safer than trying to use both PyQt versions in the same process.

Thanks for the quick reply @nicoddemus.
My thinking went along the same line, in case this was a dead end.
Have a great day!

**Comment by nicoddemus** [comment]
Btw an option is to, instead of marking them both, mark just one of them, for example only add `qt6` marks to Qt6 specific tests, and then:

```
pytest -m "not qt6"
pytest -m qt6
```
