### ISSUE TITLE
waitSignal swallows exceptions with raising=True

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#59]
When `qtbot.waitSignal(..., raising=True)` is used and an exception in the with-block happens (which causes the signal to not be emitted), it's silently ignored and `SignalTimeoutError` is raised instead.

I don't really know what the best way to fix this would be (because of the existing Qt exception capturing), but I have a test case:

```diff
diff --git a/pytestqt/_tests/test_wait_signal.py b/pytestqt/_tests/test_wait_signal.py
index 13a78c7..cd5ea57 100644
--- a/pytestqt/_tests/test_wait_signal.py
+++ b/pytestqt/_tests/test_wait_signal.py
@@ -10,6 +10,29 @@ class Signaller(QtCore.QObject):
     signal_2 = Signal()
 
 
+class TestException(Exception):
+    pass
+
+
+@pytest.mark.parametrize('multiple', [True, False])
+def test_raising_other_exception(qtbot, multiple):
+    """
+    Make sure waitSignal with raising=True handles exceptions correctly.
+    """
+    signaller = Signaller()
+
+    if multiple:
+        func = qtbot.waitSignals
+        arg = [signaller.signal, signaller.signal_2]
+    else:
+        func = qtbot.waitSignal
+        arg = signaller.signal
+
+    with pytest.raises(TestException):
+        with func(arg, timeout=10, raising=True):
+            raise TestException
+
+
 def test_signal_blocker_exception(qtbot):
     """
     Make sure waitSignal without signals and timeout doesn't hang, but raises
```

**Comment by nicoddemus** [comment]
Fixed, thanks! :smile:

The problem was on the `__exit__` method, it should not try to call `wait` if an exception has occurred, as then the signal might never be triggered and then a timeout would occur, overriding the first exception.

**Comment by The-Compiler** [comment]
That was an easier fix than I thought - thanks! :+1:

What if an exception happens *during* `wait`? Will that be picked up by the custom excepthook and displayed even when the `SignalTimeoutError` occurs?

**Comment by nicoddemus** [comment]
Yes the problem was that it was overwriting the original exception. If
there's an exception inside wait(), it will prevent timeout from even being
reached. :smile:

Em sex, 12 de jun de 2015 01:36, Florian Bruhin <notifications@github.com>
escreveu:

**Comment by nicoddemus** [comment]
Hi,

Do we have an idea of when we would like have a 2.8.0 release, or at least
what we would like to see in that new version?

And about 2.7.2? I see there are a couple of fixes that are in master but
should be backported to pytest-2.7 branch before making a 2.7.2 release.

Cheers,

**Comment by The-Compiler** [comment]
It sounds like you're replying to the wrong mail - this is `pytest-qt` :wink:

**Comment by nicoddemus** [comment]
Oh dear. :sweat_smile:
