### ISSUE TITLE
Modeltest, take 2

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#62]
Continuing the discussion from https://github.com/bgr/PyQt5_modeltest/issues/3 here:

I now have a [reimplementation](http://paste.the-compiler.org/view/3fc03801) of `modeltest.py` from the C++ code  and from what I learned from the existing `modeltest.py`.

It's still very much work-in-progress, but it seems to work. As it's translated from the original .cpp code, it's licensed under LGPL 2.1 *or* LGPL 3, which should be [fully compatible with pytest-qt's LGPL3 license](https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility).

I'm currently only running the tests from `PyQt5_modeltest` against it and
those seem to work - but for licensing and other reasons (quoting the author, *Don't give too much attention to test.py, I never gave it too much thinking, it was just something to get the thing working while I was trying it out.*) I'd like to implement proper tests for it.

I also intend to make it compatible with PyQt4 and PySide - I don't think it should be very hard once there are tests, actually.

After that, I want to add a pytest fixture and release it as a pytest plugin or as part of `pytest-qt`, preferrably the later. I've thought about this again, and it doesn't make sense as a standalone thing as it uses plain `assert`s everywhere, which makes it very hard to use without pytest anyways.

Would it be okay to add that to `pytest-qt`? I imagine adding the `modeltest.py` file as-is with the Qt copyright header (and my copyright added), and then adding the fixture to `plugin.py`.

**Comment by nicoddemus** [comment]
Nice that you are moving this forward @The-Compiler! 

Certainly I would love to see this in pytest-qt, I think it would allow a lot to the project. Feel free to start a PR, and let me know if I can help in anyway! :smile: 

Cheers,
:beers:

**Comment by nicoddemus** [comment]
**cc** @kfasolin

**Comment by The-Compiler** [comment]
BTW, here's the answer I got from @bgr via mail:

> I saw that you said re-porting would be the solution, seemed like a
> bummer but you already did it, so, awesome! I'll be perfectly fine
> with deprecating this one and will probably use your version next time
> I get to mess around with this. Which might even be today because it's
> tempting :) We're using pytest as well, so it's great that this new
> one is made with it in mind from the start. I'll look into this
> pytest-qt since I didn't know about it before this github discussion
> happened.

So seems like this will make everyone happy! :+1:

**Comment by nicoddemus** [comment]
Cool!

**Comment by The-Compiler** [comment]
@nicoddemus I'm not sure anymore - are you coming to EuroPython? If so, maybe we could work on this as part of the sprints?

**Comment by nicoddemus** [comment]
> I'm not sure anymore

About what? :grin: 

> are you coming to EuroPython? If so, maybe we could work on this as part of the sprints?

I would love to go to EuroPython and work on this in a sprint with you, but I'm not going (never went to a PyCon in fact). Quite a long trip for me as I live in Brazil and already used all my vacation time this year. Perhaps another time! :smile:

**Comment by The-Compiler** [comment]
I wasn't sure if you were coming to EP or not :wink: I thought so, it's not exactly close to you...

Since you seem to have a bit more time on your hands than I do, would you like to work on some tests for this? If so, I can probably clean up the code and push a preliminary PR (in a branch in this repo) so we can discuss - and if you feel like, you could add some tests.

**Comment by nicoddemus** [comment]
Please feel free to create the branch here and we can work on it together. I never implemented a `QAbstractModel` myself thought.

**Comment by The-Compiler** [comment]
WIP-PR in #63
