### ISSUE TITLE
Give access to what arguments were passed with in the signal

### ISSUE THREAD

**Issue by billyshambrook** [pytest-dev/pytest-qt#64]
Thanks for the great plugin!

Would be awesome if when using qtbot.waitSignal, you could access any arguments that were sent in the signal e.g.

```python

with qtbot.waitSignal(worker.success) as blocker:
    pass
assert blocker.args == 'hello, world!'
```

What are your thoughts?

I'll take a stab at it if you think it's a good feature, thanks

**Comment by The-Compiler** [comment]
Sounds useful IMHO! You might want to use a [QSignalSpy](http://doc.qt.io/qt-5/qsignalspy.html) for that.

**Comment by nicoddemus** [comment]
A PR with that would be very welcome, @billyshambrook! :smile:

**Comment by The-Compiler** [comment]
I just needed that again yesterday, so I'll take a look at this.

**Comment by The-Compiler** [comment]
See #115.
