### ISSUE TITLE
Show Qt/PyQt/PySide versions in pytest_report_header

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#68]
I think it'd be useful to show the Qt/PyQt/PySide versions used in the report header.

For PyQt, this would be:

- `PyQtX.QtCore.QT_VERSION_STR` - Qt version (which PyQt was compiled against)
- `PyQtX.QtCore.qVersion()` - Qt version (runtime)
- `PyQtX.QtCore.PYQT_VERSION_STR` - PyQt version

For PySide, it seems it's:

- `PySide.QtCore.__version__` - Qt version (which PySide was compiled against)
- `PySide.QtCore.qVersion()` - Qt version (runtime)
- `PySide.__version__` - PySide version

I'd submit a PR, but my TODO list gets longer and longer instead of shorter - so feel free to work on this if you feel like, otherwise it'll probably take me some weeks :laughing:

**Comment by nicoddemus** [comment]
Thanks for looking up how to get the version for all Qt flavors! :smile:

I will probably have time to work on this today, so no worries. You think we should display all the fields you mention (compilation, runtime version, etc etc)?

**Comment by The-Compiler** [comment]
For debugging issues (like #69) I'm usually interested in the PyQt and the runtime version - but I think it shouldn't hurt to add the compile-time version as well.

**Comment by nicoddemus** [comment]
Currently the header contains:

```
qt-api: pyqt4
```

This is what I get for `PyQt4` in my current computer:

```
>>> import PyQt4.QtCore
>>> PyQt4.QtCore.qVersion()
'4.8.6'
>>> PyQt4.QtCore.QT_VERSION_STR
'4.8.4'
>>> PyQt4.QtCore.PYQT_VERSION_STR
'4.11.1'
```

How would you like to see the this information in the header? One option would be to only display some information if pytest runs in **verbose** mode.

**Comment by nicoddemus** [comment]
To follow the style used by the rest of the header, how about this?

```
============================= test session starts =============================
platform win32 -- Python 2.7.7 -- py-1.4.26 -- pytest-2.7.0
PyQt4 4.11.1 -- Qt runtime 4.8.6 -- Qt compiled 4.8.4
```

**Comment by The-Compiler** [comment]
Maybe something like `qt-api: pyqt4 - qt: 4.8.4, runtime 4.8.6 - pyqt: 4.11.1`?

Maybe `qt-api` could be removed then?

I'm not really worried it'd be too much information - the above string (55 chars) still easily fits on one line.

**Comment by nicoddemus** [comment]
Hehehe we posted nearly at the same time. :sweat_smile:

**Comment by The-Compiler** [comment]
I prefer your output - and I still think the length/verbosity is okay without `-v`.

I really like GitHub's automatic refreshing!

**Comment by nicoddemus** [comment]
I agree about the verbosity without `-v`, it really doesn't look like too much line noise.

I will work on this today, but would like to hold on the release until we sort out #67 and #69. :smile:

**Comment by The-Compiler** [comment]
Sure, this isn't something I need right away - I can always ssh to the machines and check.
