### ISSUE TITLE
Providing pyqt testenvs in tox.ini

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#75]
What about adjusting `tox.ini` so it has test environments for every Python version for `-pyside`, `-pyqt4` and `-pyqt5`, which then set `PYTEST_QT_API` correctly? For PyQt, those would probably simply use `system_site_packages = True` and rely on it being installed system-wide, for the `-pyside` envs it would install it from PyPI.

The default environment list would then be something like `py{26,27,32,33,34}-{pyside,pyqt4,pyqt5}, docs` (if I understood tox' [generative envlist](https://testrun.org/tox/latest/config.html#generative-envlist) feature correctly).

After that, we could probably adjust `.travis.yml` to use tox as well, similar to how [pytest does it](https://github.com/pytest-dev/pytest/blob/master/.travis.yml), right?

**Comment by nicoddemus** [comment]
Excellent suggestion! I will get to it! :smile:
