### ISSUE TITLE
AppVeyor

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#76]
Is there any reason there is no integration with [AppVeyor](http://www.appveyor.com/) yet? That would probably also be a good way to easily test PyQt5 until #36 is ready.

See the [script](https://github.com/The-Compiler/qutebrowser/blob/master/scripts/dev/ci_install.py#L51-L62) I use to install PyQt5 and my [appveyor.yml](https://github.com/The-Compiler/qutebrowser/blob/master/.appveyor.yml) - I guess something similar is also possible for PyQt4, and maybe PySide.

There's also [install.ps1](https://raw.githubusercontent.com/pypa/python-packaging-user-guide/master/source/code/install.ps1) from the Python Packaging Userguide which can be used to install various Python versions easily. (It comes with 3.4 and 2.7 only by default, I think)

**Comment by nicoddemus** [comment]
I just never took the time to look up how to setup AppVeyor for pytest-qt (frankly it seems a lot more work than I'm used with Travis), but certainly it is worth the effort. :smile:

Thanks for all the links!
