### ISSUE TITLE
Test fails with ignored Qt warning

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-qt#97]
I have no idea what's going on... Looking at e.g. [this build](http://qutebrowser.org:8010/builders/osx/builds/923/steps/unittests/logs/stdio), the tests fail because of a Qt message:

```
=================================== FAILURES ===================================
_____________________ test_err_windows[''-''-'exception'] ______________________
tests/unit/utils/test_error.py:75: Failure: Qt messages with level WARNING or above emitted
----------------------------- Captured Qt messages -----------------------------
None:None:0:
    QtWarningMsg: virtual void QSslSocketBackendPrivate::transmit() SSLRead failed with: -9805
None:None:0:
    QtWarningMsg: virtual void QSslSocketBackendPrivate::transmit() SSLRead failed with: -9805
None:None:0:
    QtWarningMsg: virtual void QSslSocketBackendPrivate::transmit() SSLRead failed with: -9805
None:None:0:
    QtWarningMsg: virtual void QSslSocketBackendPrivate::transmit() SSLRead failed with: -9805
None:None:0:
    QtWarningMsg: virtual void QSslSocketBackendPrivate::transmit() SSLRead failed with: -9805
None:None:0:
    QtWarningMsg: virtual void QSslSocketBackendPrivate::transmit() SSLRead failed with: -9805
```

However, this exact message is ignored in my `pytest.ini`:

```ini
qt_log_ignore =
    ^SpellCheck: .*
    ^SetProcessDpiAwareness failed: .*
    ^QWindowsWindow::setGeometryDp: Unable to set geometry .*
    ^QProcess: Destroyed while process .* is still running\.
    ^"Method "GetAll" with signature "s" on interface "org\.freedesktop\.DBus\.Properties" doesn't exist
    ^virtual void QSslSocketBackendPrivate::transmit\(\) SSL write failed with error: -9805
    ^virtual void QSslSocketBackendPrivate::transmit\(\) SSLRead failed with: -9805
```

Unfortunately I can't trigger the message reliably. When I write a test which uses the same message with a `qWarning`, it passes:

```python
def test_suppressed_qwarning():
    qWarning("virtual void QSslSocketBackendPrivate::transmit() SSLRead failed with: -9805")
```

So I wonder what's going on... any idea?

**Comment by nicoddemus** [comment]
Hmmm I just reviewed [the](https://github.com/pytest-dev/pytest-qt/blob/master/pytestqt/logging.py#L55) [relevant](https://github.com/pytest-dev/pytest-qt/blob/master/pytestqt/logging.py#L148-L151) [code] and it seems correct to me. :confused: 

[code]: https://github.com/pytest-dev/pytest-qt/blob/master/pytestqt/logging.py#L69-L70
Some ideas:

1. Try loosing up the regex a bit, for example `".*QSslSocketBackendPrivate::transmit.*SSLRead failed with:.*-9805`... perhaps there's some hidden white-space in the original message; The fact that the messages don't have the `(IGNORED)` prefix means that the regex is not matching somehow.
2. Try printing `request.config.getini('qt_log_ignore')` from inside the test to see if the regex are correct.

That's all I can think of at the moment...

**Comment by The-Compiler** [comment]
Oh, that test has a [`qt_log_ignore` marker](https://github.com/The-Compiler/qutebrowser/blob/master/tests/unit/utils/test_error.py#L75-L77) and reading the code I realized the regexes listed there *overwrite* the ones in the config rather than extending them (like I'd've expected). Though the documentation clearly states the right thing :wink:

What do you think about adding some `extend=True` parameter to the `qt_log_ignore` marker?

**Comment by nicoddemus** [comment]
That's a good idea. Would you mind creating an issue? (I'm on my mobile right now)
